"""Stable field and enum mappings for the workbench public API."""

from __future__ import annotations

from copy import deepcopy

API_CONTRACT = "workbench-api-v2.1"
CATALOG_VERSION = "workbench-field-catalog-v1.0"


def _field(field_id: str, label: str, kind: str, unit: str, nullable: bool,
           description: str, sort_supported: bool = False) -> dict:
    return {
        "field_id": field_id,
        "label": label,
        "type": kind,
        "unit": unit,
        "nullable": nullable,
        "description": description,
        "sort_supported": sort_supported,
    }


FIELD_CATALOG = (
    _field("api_contract", "接口合同", "string", "", False, "响应所遵循的公共接口合同版本"),
    _field("catalog_version", "目录版本", "string", "", False, "字段与枚举目录版本"),
    _field("publication_id", "发布版本", "string", "", False, "成功发布的稳定标识", True),
    _field("trade_date", "交易日期", "date", "日期", False, "当前数据对应的实际交易日", True),
    _field("cutoff_date", "截止日期", "date", "日期", True, "所选发布或分析的可观测截止日期", True),
    _field("revision", "发布修订号", "integer", "", True, "同一交易日内的发布修订号", True),
    _field("production_version", "生产版本", "string", "", True, "生成该发布的生产版本标识"),
    _field("source_revision_id", "输入修订号", "integer", "", True, "冻结输入的源修订标识", True),
    _field("analysis_snapshot_id", "分析快照", "string", "", True, "历史分析快照标识；未生成时为空"),
    _field("analysis_capabilities", "分析能力", "object", "", False, "API01按域返回的分析能力状态"),
    _field("capabilities", "能力状态", "object", "", False, "API02按域返回的能力状态"),
    _field("contracts", "关联合同", "object", "", False, "API02绑定的范围、报价、语义及发布合同"),
    _field("data_quality", "数据质量", "object", "", False, "公共响应的质量状态、代码及覆盖摘要"),
    _field("security_id", "股票代码", "string", "", False, "统一证券标识，格式为市场前缀加代码", True),
    _field("security_name", "股票名称", "string", "", True, "本地发布中的证券名称", True),
    _field("name", "名称", "string", "", True, "DTO通用名称字段；由具体对象解释", True),
    _field("quote_date", "报价日期", "date", "日期", False, "原始报价所属交易日", True),
    _field("quote_state", "报价状态", "enum", "", False, "报价是否有可验证的当日原始值"),
    _field("latest_price", "最新价", "number", "CNY/share", True, "兼容旧接口的原始收盘价显示字段", True),
    _field("raw_close", "原始收盘价", "number", "CNY/share", True, "未复权原始收盘价", True),
    _field("quote_ret1", "当日涨幅", "number", "fraction", True, "当前报价相对合同参考前收的简单收益", True),
    _field("RET1", "当日涨幅（兼容）", "number", "fraction", True, "旧接口兼容字段；与quote_ret1同源", True),
    _field("quote_prev_close", "参考前收", "number", "CNY/share", True, "计算当日涨幅使用的参考前收", True),
    _field("turnover_amount", "当日成交额", "number", "CNY", True, "原始成交额，不做价格口径调整", True),
    _field("amount", "成交额", "number", "CNY", True, "DTO标准成交额字段", True),
    _field("volume", "成交量", "number", "shares", True, "原始成交量", True),
    _field("last_known_price", "最近已知价", "number", "CNY/share", True, "仅在明确缺少当日报价时提供", True),
    _field("last_known_date", "最近已知日期", "date", "日期", True, "最近已知价对应日期", True),
    _field("validity", "技术有效性", "enum", "", True, "技术字段是否满足最小有效样本条件"),
    _field("quality_codes", "质量代码", "array", "", False, "数据不足、来源或覆盖情况的可解释代码"),
    _field("ma5", "5日均线", "number", "CNY/share", True, "同一价格基准下的5日均线", True),
    _field("ma10", "10日均线", "number", "CNY/share", True, "同一价格基准下的10日均线", True),
    _field("ma20", "20日均线", "number", "CNY/share", True, "同一价格基准下的20日均线", True),
    _field("ma60", "60日均线", "number", "CNY/share", True, "同一价格基准下的60日均线", True),
    _field("ma_alignment", "均线排列", "enum", "", True, "合同定义的均线排列状态"),
    _field("ret5", "5日涨幅", "number", "fraction", True, "5个有效观察的简单收益", True),
    _field("ret10", "10日涨幅", "number", "fraction", True, "10个有效观察的简单收益", True),
    _field("ret20", "20日涨幅", "number", "fraction", True, "20个有效观察的简单收益", True),
    _field("ret60", "60日涨幅", "number", "fraction", True, "60个有效观察的简单收益", True),
    _field("rps5", "5日相对强弱", "number", "fraction", True, "5日横截面相对强弱值", True),
    _field("rps10", "10日相对强弱", "number", "fraction", True, "10日横截面相对强弱值", True),
    _field("rps20", "20日相对强弱", "number", "fraction", True, "20日横截面相对强弱值", True),
    _field("rps60", "60日相对强弱", "number", "fraction", True, "60日横截面相对强弱值", True),
    _field("turnover_rate", "换手率", "number", "fraction", True, "仅来源可验证时提供", True),
    _field("sector_id", "板块代码", "string", "", True, "本地板块稳定标识", True),
    _field("sector_name", "板块名称", "string", "", True, "发布中的板块名称", True),
    _field("sector_type", "板块类型", "enum", "", True, "行业、主题或风格等受控类型"),
    _field("semantic_bucket", "语义桶", "enum", "", True, "正常属性、价格驱动、事件驱动或状态标签"),
    _field("total_member_count", "成员数", "integer", "stocks", True, "当前发布范围内的板块成员数", True),
    _field("quote_valid_count", "有效报价数", "integer", "stocks", True, "有有效当日报价的成员数", True),
    _field("factor_valid_count", "有效因子数", "integer", "stocks", True, "满足对应因子最小覆盖的成员数", True),
    _field("member_ret1_median", "成员当日涨幅中位数", "number", "fraction", True, "有效成员当日涨幅中位数", True),
    _field("breadth_ret1", "全成员上涨宽度", "number", "fraction", True, "当日全部有效成员中的上涨比例；仅作描述性统计", True),
    _field("breadth_ret1_common", "共同成员上涨宽度", "number", "fraction", True, "前后比较日共同且两日涨幅有效成员中的当日上涨比例；M10 B使用此字段", True),
    _field("breadth_ret1_common_valid_count", "共同有效成员数", "integer", "stocks", True, "计算共同成员上涨宽度的共同有效成员分母", True),
    _field("breadth_ret1_common_change_1d", "共同宽度日变化", "number", "fraction", True, "在同一前后日共同有效成员集合上计算的宽度变化", True),
    _field("breadth_ret1_common_change_1d_valid_count", "共同宽度日变化有效数", "integer", "stocks", True, "共同宽度日变化使用的共同有效成员分母", True),
    _field("breadth_ret1_common_change_3d", "共同宽度三日变化", "number", "fraction", True, "在同一当前日与三交易日前共同有效成员集合上计算的宽度变化", True),
    _field("breadth_ret1_common_change_3d_valid_count", "共同宽度三日变化有效数", "integer", "stocks", True, "共同宽度三日变化使用的共同有效成员分母", True),
    _field("strong_count", "强势成员数", "integer", "stocks", True, "当前纳入成员中强势状态为真的数量；未知状态不计为强势", True),
    _field("high20_count", "20日新高数", "integer", "stocks", True, "当前纳入成员中满足20日新高的数量", True),
    _field("high30_count", "30日新高数", "integer", "stocks", True, "当前纳入成员中满足30日新高的数量", True),
    _field("high60_count", "60日新高数", "integer", "stocks", True, "当前纳入成员中满足60日新高的数量", True),
    _field("high100_count", "100日新高数", "integer", "stocks", True, "当前纳入成员中满足100日新高的数量", True),
    _field("high20_valid_count", "20日新高有效数", "integer", "stocks", True, "20日新高判断具有已知结果的当前纳入成员数", True),
    _field("high30_valid_count", "30日新高有效数", "integer", "stocks", True, "30日新高判断具有已知结果的当前纳入成员数", True),
    _field("high60_valid_count", "60日新高有效数", "integer", "stocks", True, "60日新高判断具有已知结果的当前纳入成员数", True),
    _field("high100_valid_count", "100日新高有效数", "integer", "stocks", True, "100日新高判断具有已知结果的当前纳入成员数", True),
    _field("comparable_count", "共同可比成员数", "integer", "stocks", True, "前后两日均为成员且两日强势状态均已知的成员数", True),
    _field("previous_strong_total", "昨日强势成员总数", "integer", "stocks", True, "昨日全部纳入成员中强势状态为真的数量", True),
    _field("comparable_previous_strong", "共同可比昨日强势数", "integer", "stocks", True, "共同可比集合中昨日强势状态为真的数量", True),
    _field("retained_count", "留存强势成员数", "integer", "stocks", True, "共同可比集合中前后两日均强势的数量", True),
    _field("entered_count", "共同进入强势数", "integer", "stocks", True, "仅在共同可比集合内由非强势变为强势的数量", True),
    _field("exited_count", "共同退出强势数", "integer", "stocks", True, "仅在共同可比集合内由强势变为非强势的数量", True),
    _field("uncomparable_count", "不可比昨日强势数", "integer", "stocks", True, "昨日强势总数中不在共同可比昨日强势集合的数量", True),
    _field("comparison_coverage", "比较覆盖率", "number", "fraction", True, "共同可比成员数/昨日纳入成员数", True),
    _field("diffusion_state", "扩散状态", "enum", "", True, "共同可比成员进入与退出的确定性比较状态", True),
    _field("member_amount_sum", "成员成交额合计", "number", "CNY", True, "有效成员原始成交额合计", True),
    _field("member_amount_ratio_median_vs_prior20", "成员金额比中位数（诊断）", "number", "ratio", True, "旧成员级金额比值中位数，仅作诊断代理；不是正式金额 A", True),
    _field("sector_amount_vs_prior20", "板块金额 A", "number", "ratio", True, "固定共同成员集合的板块成交额合计/该集合过去20个主交易日合计均值；质量门未通过时为空", True),
    _field("sector_amount_comparable_sum", "板块金额 A 当前合计", "number", "CNY", True, "正式金额 A 当前日共同可比成员原始成交额合计", True),
    _field("sector_amount_prior20_mean", "板块金额 A 过去20日均值", "number", "CNY", True, "正式金额 A 分母：同一共同成员集合过去20个主交易日合计的均值", True),
    _field("amount_comparable_member_count", "金额 A 可比成员数", "integer", "stocks", True, "同时满足 H21 所有主交易日金额质量要求的共同成员数", True),
    _field("amount_target_member_count", "金额 A 目标成员数", "integer", "stocks", True, "当前日金额 A 目标成员数", True),
    _field("amount_comparable_coverage", "金额 A 当前覆盖率", "number", "fraction", True, "可比成员数/当前目标成员数", True),
    _field("amount_window_coverage", "金额 A 窗口覆盖率", "number", "fraction", True, "可比成员数/窗口内目标成员数最大值", True),
    _field("amount_target_denominator_source", "金额 A 当前分母来源", "enum", "", True, "当前覆盖率的目标成员分母来源", False),
    _field("amount_window_denominator_source", "金额 A 窗口分母来源", "enum", "", True, "窗口覆盖率的目标成员分母来源", False),
    _field("amount_basis", "金额 A 计算口径", "enum", "", True, "OBSERVED 或 RECONSTRUCTED 固定快照的正式金额 A 口径", False),
    _field("amount_quality_codes", "金额 A 质量代码", "array", "", True, "金额 A 的历史、成员、覆盖和分母质量门结果", False),
    _field("amount_excluded_member_ids", "金额 A 排除成员", "array", "", True, "因成员历史或金额质量不合格而未进入 U 的成员标识", False),
    _field("amount_member_set_hash", "金额 A 成员集合哈希", "string", "", True, "正式金额 A 实际使用集合 U 的稳定哈希", False),
    _field("amount_membership_snapshot_id", "金额 A 成员快照", "string", "", True, "RECONSTRUCTED 金额 A 使用的固定成员快照标识", False),
    _field("amount_window_start", "金额 A 窗口起点", "date", "日期", True, "H21 窗口首个主交易日", True),
    _field("amount_window_end", "金额 A 窗口终点", "date", "日期", True, "H21 窗口最后一个主交易日（当前日）", True),
    _field("amount_contract_id", "金额 A 合同", "string", "", True, "正式金额 A 的版本化计算合同", False),
    _field("sector_amount_ratio_delta_3sessions_common", "金额 A 三交易日变化", "number", "ratio", True, "同一 24 主交易日并集与共同成员集合上的当前 A 减三交易日前 A", True),
    _field("amount_comparison_evidence", "金额 A 比较证据", "object", "", True, "三交易日金额 A 比较日期、合计、基准、集合哈希、覆盖和质量门", False),
    _field("rs20_pct", "板块20日相对强弱分位", "number", "fraction", True, "板块横截面相对强弱分位", True),
    _field("display_rank", "显示排名", "integer", "rank", True, "当前页面显示排名", True),
    _field("mainline_class", "主线分类", "enum", "", False, "按主线状态合同确定的唯一分类"),
    _field("previous_class", "前一分类", "enum", "", True, "上一可观测日的主线分类"),
    _field("transition", "分类变化", "enum", "", True, "相对上一可观测日的分类变化"),
    _field("observation_days", "观察天数", "integer", "days", False, "该板块已进入主线分类计算的可观测天数", True),
    _field("valid_observation_days", "有效观察天数", "integer", "days", False, "具有有效板块RPS20分位的观察天数", True),
    _field("on_list_days", "入选天数", "object", "days", False, "5/10/20/30日窗口内达到入选阈值的天数"),
    _field("consecutive_on_list", "连续入选天数", "integer", "days", True, "截至当前连续达到入选阈值的天数", True),
    _field("current_percentile", "当前RPS20分位", "number", "fraction", True, "主线分类使用的当前板块RPS20分位", True),
    _field("current_breadth", "当前共同成员宽度", "number", "fraction", True, "主线分类使用的共同且有效成员上涨宽度", True),
    _field("current_amount_vs_prior20", "当前成交额相对20日（兼容）", "number", "ratio", True, "旧主线兼容字段；v2.4 不再将其作为正式金额 A", True),
    _field("current_sector_amount_vs_prior20", "主线当前金额 A", "number", "ratio", True, "M10 v2.4 主线使用的正式板块金额 A；质量门未通过时为空且不回退代理", True),
    _field("retention_rate", "成员留存率", "number", "fraction", True, "留存强势成员数/共同可比昨日强势数；分母为0时为空", True),
    _field("predicates", "主线判定条件", "object", "", False, "每个确定性条件的通过、失败或未知状态"),
    _field("missing_fields", "主线缺失字段", "array", "", False, "导致结果为数据不足或降级的缺失字段"),
    _field("conflict_resolution", "冲突解释", "string", "", True, "多条件同时满足或存在未知条件时的解释"),
    _field("history_basis", "历史依据", "enum", "", False, "观测历史或本地重建历史的来源口径"),
    _field("queue_name", "结构队列", "enum", "", False, "规范化结构队列名称", True),
    _field("hit", "结构命中", "boolean", "", False, "是否满足该队列的结构合同"),
    _field("tier", "队列层级", "enum", "", True, "CORE或SUPPORTED等合同层级"),
    _field("queue_rank", "队内名次", "integer", "rank", True, "未过滤完整队列中的合同名次", True),
    _field("research_band", "研究带", "enum", "", False, "研究优先带，不是交易信号"),
    _field("primary_pattern", "主结构模式", "string", "", True, "确定性规则产生的主要结构模式"),
    _field("v1_grade", "原版等级", "enum", "", True, "兼容旧发布的研究优先等级"),
    _field("association_rank", "关联排名", "integer", "rank", True, "股票与板块关联的合同排名", True),
    _field("member_rank", "板块内名次", "integer", "rank", True, "股票在所属板块内的合同名次", True),
    _field("rank_valid_count", "排名有效数", "integer", "stocks", True, "参与该排名的有效成员数", True),
    _field("eligible", "关联有效", "boolean", "", False, "是否满足关联合同的资格条件"),
    _field("reason_codes", "原因代码", "array", "", False, "关联拒绝或降级原因代码"),
    _field("contract_id", "字段合同", "string", "", False, "产生该字段的版本化合同标识"),
    _field("evidence_id", "证据标识", "string", "", True, "按需展开证据的稳定标识"),
    _field("source_refs", "来源引用", "array", "", True, "证据对应的本地来源引用"),
)

ENUM_CATALOG = {
    "capability": {
        "AVAILABLE": "可用",
        "PARTIAL": "部分可用",
        "UNAVAILABLE": "来源不可用",
        "NOT_BUILT": "尚未生成",
    },
    "quote_state": {
        "VALID": "有效报价",
        "VALID_DEGRADED": "有效但口径降级",
        "MISSING_PREVIOUS_CLOSE": "缺少参考前收",
        "UNKNOWN_CORPORATE_ACTION": "公司行为未确定",
        "MISSING": "缺少当日报价",
        "SOURCE_NOT_FROZEN": "该发布未封存原始报价",
    },
    "queue_name": {
        "STEADY_QUEUE": "稳健趋势队列",
        "PULLBACK_QUEUE": "强势回撤队列",
        "BREAKOUT_QUEUE": "突破准备队列",
        "LEADER_QUEUE": "板块龙头队列",
        "EARLY_QUEUE": "早期启动队列",
    },
    "research_band": {
        "CORE_RESEARCH": "核心观察",
        "SUPPORTED_RESEARCH": "一般观察",
        "DIAGNOSTIC_ONLY": "诊断观察",
    },
    "sector_type": {
        "INDUSTRY": "行业板块",
        "THEME": "概念板块",
        "STYLE": "风格板块",
        "OTHER": "其他板块",
    },
    "mainline_class": {
        "DATA_INSUFFICIENT": "数据不足",
        "FADING": "退潮",
        "HIGH_LEVEL_CONTRACTION": "高位收缩",
        "REACCELERATING": "再加速",
        "SUSTAINED": "持续",
        "NEW": "新晋",
        "BROADENING": "扩散",
        "OBSERVING": "观察中",
    },
    "mainline_transition": {
        "UNCHANGED": "保持不变",
        "MODEL_CHANGE": "模型合同变化",
        "BASIS_CHANGE": "历史口径变化",
        "DATA_INSUFFICIENT": "变为数据不足",
        "FADING": "变为退潮",
        "HIGH_LEVEL_CONTRACTION": "变为高位收缩",
        "REACCELERATING": "变为再加速",
        "SUSTAINED": "变为持续",
        "NEW": "变为新晋",
        "BROADENING": "变为扩散",
        "OBSERVING": "变为观察中",
    },
    "history_basis": {
        "OBSERVED": "本地观测",
        "RECONSTRUCTED": "本地重建",
    },
    "semantic_bucket": {
        "NORMAL_ATTRIBUTE": "正常属性",
        "PRICE_DRIVEN": "价格驱动标签",
        "EVENT_DRIVEN": "事件驱动标签",
        "STATUS_LABEL": "状态标签",
    },
    "tier": {"CORE": "核心层", "SUPPORTED": "支持层"},
    "validity": {"VALID": "有效", "PARTIAL": "部分有效", "INSUFFICIENT": "数据不足"},
    "diffusion_state": {"EXPANSION": "扩散", "CONTRACTION": "收缩", "STABLE": "稳定", "UNKNOWN": "未知", "DATA_UNAVAILABLE": "数据不可用"},
}


def field_catalog(api_contract: str = API_CONTRACT, language: str = "zh-CN") -> dict:
    if api_contract != API_CONTRACT:
        raise ValueError("UNSUPPORTED_API_CONTRACT")
    if language != "zh-CN":
        raise ValueError("LANGUAGE_UNSUPPORTED")
    return {
        "api_contract": API_CONTRACT,
        "catalog_version": CATALOG_VERSION,
        "language": language,
        "items": deepcopy(list(FIELD_CATALOG)),
        "enums": deepcopy(ENUM_CATALOG),
    }
