"""生成面向使用者的中文交互式日报。"""
from __future__ import annotations
import html,json,math
import pandas as pd

def _clean(value):
    if value is None:return None
    try:
        if bool(pd.isna(value)):return None
    except (TypeError,ValueError):pass
    if isinstance(value,float) and (math.isnan(value) or math.isinf(value)):return None
    if hasattr(value,"item"):
        try:
            converted=value.item()
            return str(value) if converted is value else _clean(converted)
        except Exception:pass
    return value if isinstance(value,(str,int,float,bool)) else str(value)

def _records(frame,columns):
    return [{c:_clean(row.get(c)) for c in columns} for row in frame.to_dict("records")]

def render_dashboard(cutoff,generation,market,sectors,candidates):
    m=market.iloc[0]
    scols=["sector_id","sector_name","sector_type","primary_pattern","scanner_hits","display_rank","sector_rs5_pct","sector_rs20_pct","sector_rs60_pct","sector_breadth_ret5_pos","sector_breadth_ret20_pos","sector_ret5_median","sector_ret20_median","sector_mdd20_median","sector_amount_ratio_median","coverage","total_member_count","tradable_member_count","breadth_expansion","high_concentration","low_coverage"]
    ccols=["security_id","security_name","research_priority","priority_score","research_priority_pct","effective_pattern","scanner_hits","RET5","RET20","RET60","stock_rs5_pct","stock_rs20_pct","stock_rs60_pct","adj_close","AMOUNT_RATIO20","best_sector_name","best_sector_primary_pattern","primary_leader_sector_name","primary_leader_sector_type","primary_leader_pattern","leader_sector_names","warning_codes","priority_reason_codes"]
    payload={"板块":_records(sectors,scols),"个股":_records(candidates,ccols)}
    data=json.dumps(payload,ensure_ascii=False,separators=(",",":"),default=_clean).replace("</","<\\/")
    cards=[("正常股票",m.get("normal_universe_count"),"只"),("5日上涨宽度",m.get("breadth_ret5_pos"),"pct"),("20日上涨宽度",m.get("breadth_ret20_pos"),"pct"),("站上20日均线",m.get("breadth_above_ma20"),"pct"),("市场20日中位涨幅",m.get("market_ret20_median"),"pct"),("成交活跃度",m.get("amount_ratio_5_20_median"),"num")]
    card_html="".join(f'<div class="指标卡"><span>{n}</span><strong data-value="{_clean(v)}" data-kind="{k}">--</strong></div>' for n,v,k in cards)
    grades=candidates.research_priority.value_counts().to_dict()
    empty_notice='<p class="提示">本日无符合当前规则的候选</p>' if candidates.empty else ''
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>通达信市场结构日报 {cutoff}</title>
<style>
:root{{--bg:#f3f6fb;--panel:#fff;--ink:#172033;--muted:#6b768c;--line:#e5eaf2;--red:#d94b55;--green:#169873;--blue:#315efb;--gold:#d99820}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font-family:"Microsoft YaHei","PingFang SC",sans-serif}}header{{background:linear-gradient(125deg,#172b4d,#284e82 58%,#3972ba);color:#fff;padding:28px max(24px,calc((100vw - 1500px)/2)) 24px}}h1{{margin:0 0 8px;font-size:28px}}header p{{margin:3px 0;color:#dce8fa}}main{{max-width:1500px;margin:auto;padding:20px}}.指标区{{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:18px}}.指标卡,.面板{{background:var(--panel);border:1px solid var(--line);border-radius:14px;box-shadow:0 4px 18px rgba(29,49,82,.06)}}.指标卡{{padding:15px}}.指标卡 span{{display:block;color:var(--muted);font-size:13px}}.指标卡 strong{{font-size:24px;margin-top:6px;display:block}}nav{{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}}button,select,input{{font:inherit;border:1px solid #d7deea;border-radius:9px;background:#fff;padding:9px 12px}}button{{cursor:pointer}}button.选中{{background:var(--blue);color:#fff;border-color:var(--blue)}}.面板{{padding:18px;margin-bottom:18px}}.面板 h2{{margin:0 0 6px;font-size:20px}}.说明{{color:var(--muted);font-size:13px;margin:0 0 14px}}.工具栏{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}}.表格框{{overflow:auto;max-height:650px;border:1px solid var(--line);border-radius:10px}}table{{border-collapse:collapse;width:100%;font-size:13px}}th,td{{padding:9px 10px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}}th{{position:sticky;top:0;background:#edf2fa;color:#43506a;z-index:1}}th:nth-child(-n+3),td:nth-child(-n+3){{text-align:left}}tr:hover td{{background:#f5f8ff}}.涨{{color:var(--red);font-weight:600}}.跌{{color:var(--green);font-weight:600}}.等级{{display:inline-block;border-radius:12px;padding:2px 8px;background:#eaf0ff;color:#214fd0;font-weight:700}}.隐藏{{display:none}}.联动布局{{display:grid;grid-template-columns:320px 1fr;gap:14px}}.板块列表{{max-height:650px;overflow:auto}}.板块项{{padding:10px;border-bottom:1px solid var(--line);cursor:pointer}}.板块项:hover,.板块项.选中{{background:#edf3ff}}.提示{{background:#fff8e8;border-left:4px solid var(--gold);padding:11px 14px;border-radius:6px;font-size:13px}}@media(max-width:950px){{.指标区{{grid-template-columns:repeat(2,1fr)}}.联动布局{{grid-template-columns:1fr}}}}
</style></head><body><header><h1>通达信市场结构日报</h1><p>数据截止日：{html.escape(cutoff)}　生成批次：{html.escape(str(generation))}</p><p>价格口径：通达信本地前复权　成员口径：当前通达信成员</p></header><main>
<section class="指标区">{card_html}</section>
<nav><button class="页签 选中" data-page="概览">市场概览</button><button class="页签" data-page="板块">板块总排行</button><button class="页签" data-page="个股">个股总排行</button><button class="页签" data-page="联动">板块个股联动</button></nav>
<section id="概览" class="页面 面板"><h2>今日结构概览</h2><p class="说明">先看市场宽度，再看板块和个股。红色为正值，绿色为负值。</p><div class="指标区"><div class="指标卡"><span>候选总数</span><strong>{len(candidates)}</strong></div><div class="指标卡"><span>甲加级</span><strong>{grades.get('A+',0)}</strong></div><div class="指标卡"><span>甲级</span><strong>{grades.get('A',0)}</strong></div><div class="指标卡"><span>乙级</span><strong>{grades.get('B',0)}</strong></div><div class="指标卡"><span>丙级</span><strong>{grades.get('C',0)}</strong></div></div>{empty_notice}<p class="提示">甲加、甲、乙、丙只表示当日候选池内的研究顺序，不代表上涨概率、胜率、买入评级或投资建议。</p><h2 style="margin-top:20px">领先板块</h2><div id="概览板块"></div><h2 style="margin-top:20px">领先个股</h2><div id="概览个股"></div></section>
<section id="板块" class="页面 面板 隐藏"><h2>板块总排行</h2><p class="说明">默认按20日相对强度排序，可查看全部有效板块。</p><div class="工具栏"><input id="板块搜索" placeholder="搜索板块名称或代码"><select id="板块类型"><option value="">全部板块类型</option><option value="INDUSTRY">行业板块</option><option value="THEME">题材板块</option><option value="STYLE">风格板块</option></select><select id="板块结构"><option value="">全部结构</option><option value="CURRENT_STRENGTH">当前强势</option><option value="STABILIZATION">企稳</option><option value="REACCELERATION">再加速</option><option value="NONE">暂无结构</option></select></div><div id="板块表"></div></section>
<section id="个股" class="页面 面板 隐藏"><h2>个股总排行</h2><p class="说明">默认显示甲加和甲级；点击乙级、丙级后才读取并显示较低优先级。</p><div class="工具栏"><button class="等级按钮 选中" data-grade="A+">甲加级</button><button class="等级按钮 选中" data-grade="A">甲级</button><button class="等级按钮" data-grade="B">读取乙级</button><button class="等级按钮" data-grade="C">读取丙级</button><button class="等级按钮" data-grade="ALL">全部等级</button><input id="个股搜索" placeholder="搜索股票名称或代码"><select id="个股结构"><option value="">全部结构</option><option value="STEADY_TREND">稳健趋势</option><option value="STRONG_PULLBACK">强势回撤</option><option value="BREAKOUT_PREP">突破准备</option><option value="SECTOR_LEADER">板块龙头</option><option value="EARLY_MOVER">早期启动</option></select></div><div id="个股表"></div></section>
<section id="联动" class="页面 面板 隐藏"><h2>板块与个股联动</h2><p class="说明">点击左侧板块，右侧显示与该板块关联的候选个股及其强弱排序。</p><div class="联动布局"><div id="联动板块" class="板块列表"></div><div id="联动个股"></div></div></section>
</main><script>const 数据={data};
const 映射={{INDUSTRY:'行业',THEME:'题材',STYLE:'风格',CURRENT_STRENGTH:'当前强势',STABILIZATION:'企稳',REACCELERATION:'再加速',NONE:'暂无结构',STEADY_TREND:'稳健趋势',STRONG_PULLBACK:'强势回撤',BREAKOUT_PREP:'突破准备',SECTOR_LEADER:'板块龙头',EARLY_MOVER:'早期启动','A+':'甲加','A':'甲','B':'乙','C':'丙'}};
const 名称=x=>映射[x]||x||'—', 数字=(x,d=1)=>x==null?'—':Number(x).toFixed(d), 百分比=x=>x==null?'—':(Number(x)*100).toFixed(1)+'%', 涨跌=x=>x>0?'涨':x<0?'跌':'';
document.querySelectorAll('[data-value]').forEach(e=>e.textContent=e.dataset.kind==='pct'?百分比(e.dataset.value):e.dataset.kind==='num'?数字(e.dataset.value,2):Math.round(e.dataset.value||0).toLocaleString());
const 表格=(rows,cols)=>'<div class="表格框"><table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+cols.map(c=>{{let v=c[2]?c[2](r[c[1]],r):名称(r[c[1]]);return '<td class="'+(c[3]?c[3](r[c[1]]):'')+'">'+v+'</td>'}}).join('')+'</tr>').join('')+'</tbody></table></div>';
const 板块列=[['名次','display_rank',x=>x?Math.round(x):'—'],['板块','sector_name'],['类型','sector_type'],['结构','primary_pattern'],['5日相对强度','sector_rs5_pct',百分比],['20日相对强度','sector_rs20_pct',百分比],['60日相对强度','sector_rs60_pct',百分比],['5日上涨宽度','sector_breadth_ret5_pos',百分比],['20日涨幅','sector_ret20_median',百分比,涨跌],['20日回撤','sector_mdd20_median',百分比,涨跌],['成交活跃度','sector_amount_ratio_median',x=>数字(x,2)],['覆盖率','coverage',百分比],['可交易成员','tradable_member_count',x=>x??'—']];
const 个股列=[['名次','priority_score',(x,r)=>数据.个股.indexOf(r)+1],['代码','security_id'],['名称','security_name'],['等级','research_priority',x=>'<span class="等级">'+名称(x)+'</span>'],['研究顺序分','priority_score',x=>数字(x,2)],['结构','effective_pattern'],['现价','adj_close',x=>数字(x,2)],['5日涨幅','RET5',百分比,涨跌],['20日涨幅','RET20',百分比,涨跌],['20日相对强度','stock_rs20_pct',百分比],['成交活跃度','AMOUNT_RATIO20',x=>数字(x,2)],['最佳板块','best_sector_name'],['龙头板块','primary_leader_sector_name']];
const 板块排序=()=>[...数据.板块].filter(x=>x.sector_valid!==false).sort((a,b)=>(b.sector_rs20_pct??-1)-(a.sector_rs20_pct??-1)); const 个股排序=()=>[...数据.个股].sort((a,b)=>(b.priority_score??-1)-(a.priority_score??-1));
document.getElementById('概览板块').innerHTML=表格(板块排序().slice(0,15),板块列);document.getElementById('概览个股').innerHTML=表格(个股排序().slice(0,20),个股列);
function 画板块(){{let q=document.getElementById('板块搜索').value.trim().toLowerCase(),t=document.getElementById('板块类型').value,p=document.getElementById('板块结构').value;let rows=板块排序().filter(x=>(!q||String(x.sector_name+x.sector_id).toLowerCase().includes(q))&&(!t||x.sector_type===t)&&(!p||x.primary_pattern===p));document.getElementById('板块表').innerHTML=表格(rows,板块列)}}
let 等级=new Set(['A+','A']);function 画个股(){{let q=document.getElementById('个股搜索').value.trim().toLowerCase(),p=document.getElementById('个股结构').value;let rows=个股排序().filter(x=>等级.has(x.research_priority)&&(!q||String(x.security_name+x.security_id).toLowerCase().includes(q))&&(!p||x.effective_pattern===p));document.getElementById('个股表').innerHTML=表格(rows,个股列)}}
function 关联(x,s){{return [x.best_sector_name,x.primary_leader_sector_name,...String(x.leader_sector_names||'').split('|')].includes(s.sector_name)}} function 画联动(){{let ss=板块排序().filter(s=>数据.个股.some(x=>关联(x,s)));document.getElementById('联动板块').innerHTML=ss.map((s,i)=>'<div class="板块项 '+(i===0?'选中':'')+'" data-i="'+i+'"><b>'+s.sector_name+'</b><br><small>'+名称(s.sector_type)+' · '+名称(s.primary_pattern)+' · 关联 '+数据.个股.filter(x=>关联(x,s)).length+' 只</small></div>').join('');const 选=i=>{{document.querySelectorAll('.板块项').forEach((e,j)=>e.classList.toggle('选中',i===j));document.getElementById('联动个股').innerHTML='<h3>'+ss[i].sector_name+'关联个股</h3>'+表格(个股排序().filter(x=>关联(x,ss[i])),个股列)}};document.querySelectorAll('.板块项').forEach(e=>e.onclick=()=>选(+e.dataset.i));if(ss.length)选(0)}}
document.querySelectorAll('.页签').forEach(b=>b.onclick=()=>{{document.querySelectorAll('.页签').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');document.querySelectorAll('.页面').forEach(x=>x.classList.add('隐藏'));document.getElementById(b.dataset.page).classList.remove('隐藏')}});document.querySelectorAll('.等级按钮').forEach(b=>b.onclick=()=>{{if(b.dataset.grade==='ALL'){{等级=new Set(['A+','A','B','C']);document.querySelectorAll('.等级按钮').forEach(x=>x.classList.add('选中'))}}else{{等级.has(b.dataset.grade)?等级.delete(b.dataset.grade):等级.add(b.dataset.grade);b.classList.toggle('选中')}}画个股()}});['板块搜索','板块类型','板块结构'].forEach(id=>document.getElementById(id).oninput=画板块);['个股搜索','个股结构'].forEach(id=>document.getElementById(id).oninput=画个股);画板块();画个股();画联动();</script></body></html>'''
