"""第二版结构研究工作台：只负责展示，不改变任何经济规则。"""
from __future__ import annotations
import json,math

def _clean(v):
    if v is None:return None
    try:
        if bool(v != v):return None
    except (TypeError,ValueError):pass
    if hasattr(v,"item"):
        try:return _clean(v.item())
        except Exception:pass
    return v if isinstance(v,(str,int,float,bool)) else str(v)

def _rows(frame,cols):return [{c:_clean(r.get(c)) for c in cols} for r in frame.to_dict("records")]

def render_workbench(cutoff,release_id,sectors,stocks,candidates,board,details,identity,membership,ranking):
    stock_cols=["security_id","security_name","adj_close","RET5","RET20","RET60","RS5","RS20","RS60","stock_rs5_pct","stock_rs20_pct","stock_rs60_pct","primary_pattern","scanner_hits","best_sector_name","quality_flag"]
    candidate_cols=["security_id","security_name","research_priority","priority_score","effective_pattern","best_sector_name","primary_leader_sector_name","RET5","RET20","RET60","stock_rs5_pct","stock_rs20_pct","stock_rs60_pct","adj_close"]
    board_cols=["security_id","v1_primary_pattern","v1_research_priority","v2_steady_class","steady_queue_tier","v2_pullback_class","pullback_queue_tier","v2_breakout_class","breakout_queue_tier","v2_leader_class","leader_queue_tier","v2_early_class","early_queue_tier","queue_memberships","shadow_research_band","has_data_insufficient_structure","has_style_self_reinforcement_context","has_short_term_pulse_context","has_depth_mismatch_context","has_no_contraction_context"]
    sector_cols=["sector_id","sector_name","sector_type","primary_pattern","display_rank","sector_rs5_pct","sector_rs20_pct","sector_rs60_pct","sector_breadth_ret5_pos","sector_breadth_ret20_pos","sector_ret20_median","sector_mdd20_median","sector_amount_ratio_median","coverage","tradable_member_count"]
    rank_cols=[c for c in ranking.columns if c!="security_id"]
    merged=candidates.merge(board[board_cols],on="security_id",how="left",validate="one_to_one").merge(ranking,on="security_id",how="left",validate="one_to_one")
    member=membership.merge(stocks[["security_id","security_name","stock_rs20_pct","RET20","quality_flag"]],on="security_id",how="left",validate="many_to_one")
    member["sector_member_rank"]=member.groupby("sector_id")["stock_rs20_pct"].rank(method="min",ascending=False,na_option="bottom")
    member_cols=["sector_id","sector_name","sector_type","sector_role","security_id","security_name","stock_rs20_pct","RET20","quality_flag","sector_member_rank","membership_basis"]
    payload={"板块":_rows(sectors,sector_cols),"全市场":_rows(stocks,stock_cols),"候选":_rows(merged,list(dict.fromkeys(candidate_cols+board_cols+rank_cols))),"成员":_rows(member,member_cols),"证据":{k:_rows(v,[c for c in v.columns if c!="date"]) for k,v in details.items()},"身份":identity}
    data=json.dumps(payload,ensure_ascii=False,separators=(",",":"),default=_clean).replace("</","<\\/")
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>第二版结构研究工作台 {cutoff}</title><style>
:root{{--bg:#f3f6fb;--panel:#fff;--ink:#172033;--muted:#68758d;--line:#e3e8f1;--blue:#315efb;--red:#d94b55;--green:#169873;--gold:#d99820}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font-family:"Microsoft YaHei","PingFang SC",sans-serif}}header{{padding:27px max(22px,calc((100vw - 1500px)/2));background:linear-gradient(125deg,#152746,#28598d 62%,#3d7ac0);color:#fff}}h1{{margin:0 0 8px;font-size:27px}}header p{{margin:3px 0;color:#dce9fa}}main{{max-width:1500px;margin:auto;padding:18px}}nav,.工具{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}}button,input,select{{font:inherit;padding:9px 12px;border:1px solid #d5ddea;border-radius:9px;background:#fff}}button{{cursor:pointer}}button.选中{{color:#fff;background:var(--blue);border-color:var(--blue)}}.面板{{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;margin-bottom:16px;box-shadow:0 4px 18px rgba(28,47,78,.06)}}.卡片区{{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}}.卡片{{border:1px solid var(--line);border-radius:12px;padding:13px}}.卡片 strong{{display:block;font-size:23px;margin-top:5px}}.弱{{color:var(--muted);font-size:13px}}.提示{{padding:11px 13px;background:#fff8e7;border-left:4px solid var(--gold);border-radius:7px}}.表格框{{overflow:auto;max-height:680px;border:1px solid var(--line);border-radius:10px}}table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{white-space:nowrap;padding:9px 10px;border-bottom:1px solid var(--line);text-align:right}}th{{position:sticky;top:0;background:#edf2fa;color:#40506c;z-index:1}}th:nth-child(-n+3),td:nth-child(-n+3){{text-align:left}}tr:hover td{{background:#f5f8ff}}.涨{{color:var(--red);font-weight:600}}.跌{{color:var(--green);font-weight:600}}.徽标{{display:inline-block;padding:2px 8px;border-radius:12px;background:#eaf0ff;color:#214fd0;font-weight:700}}.核心{{background:#ffe9ea;color:#b82d38}}.一般{{background:#e9f5ef;color:#14795e}}.隐藏{{display:none}}details{{text-align:left;max-width:520px}}summary{{cursor:pointer;color:#315efb}}pre{{white-space:pre-wrap;font-family:inherit;font-size:12px;color:#3f4b61}}@media(max-width:900px){{.卡片区{{grid-template-columns:repeat(2,1fr)}}}}</style></head><body>
<header><h1>第二版结构研究工作台</h1><p>数据截止日：{cutoff}　第一版发布：{release_id}</p><p>五类结构独立观察；页面排序只用于浏览，不构成跨结构优劣比较。</p></header><main><section class="面板"><div class="卡片区" id="队列卡片"></div><p class="提示">“核心观察、一般观察、诊断观察”表示证据完整程度。第一版甲加、甲、乙、丙仅作为历史评分对照，不代表上涨概率或交易评级。</p></section>
<nav><button class="页签 选中" data-page="队列">五类结构队列</button><button class="页签" data-page="板块">板块分类排行</button><button class="页签" data-page="联动">板块个股联动</button><button class="页签" data-page="全市场">全市场股票查询</button><button class="页签" data-page="说明">证据说明</button></nav>
<section id="队列" class="页面 面板"><h2>五类结构队列</h2><div class="工具" id="队列按钮"></div><div class="工具"><button class="研究带 选中" data-band="CORE_RESEARCH">核心观察</button><button class="研究带 选中" data-band="SUPPORTED_RESEARCH">一般观察</button><button class="研究带" data-band="DIAGNOSTIC_ONLY">读取诊断观察</button><input id="队列搜索" placeholder="搜索股票名称或代码"></div><p id="队列口径" class="弱"></p><div id="队列表"></div></section>
<section id="板块" class="页面 面板 隐藏"><h2>板块分类排行</h2><p class="弱">行业、题材、风格分别计算百分位和名次；切换类型后再比较。</p><div class="工具"><button class="板块类型 选中" data-type="INDUSTRY">行业</button><button class="板块类型" data-type="THEME">题材</button><button class="板块类型" data-type="STYLE">风格</button><input id="板块搜索" placeholder="搜索板块名称或代码"></div><div id="板块表"></div></section>
<section id="联动" class="页面 面板 隐藏"><h2>板块与个股联动</h2><p class="弱">关系来自截止日通达信成员快照，以稳定代码关联。当前成员不能用于历史时点回填。</p><div class="工具"><input id="联动板块搜索" placeholder="输入板块名称或代码"><input id="联动个股搜索" placeholder="输入股票名称或代码"></div><h3 id="成员标题">选择一个板块查看全部成员</h3><div id="成员表"></div><h3 id="所属标题">选择一只股票查看全部所属板块</h3><div id="所属表"></div></section>
<section id="全市场" class="页面 面板 隐藏"><h2>全市场股票查询</h2><p class="弱">包含全部正常股票。未进入候选池的股票显示“未命中结构”，不会补造研究等级。</p><div class="工具"><input id="全市场搜索" placeholder="输入股票名称或代码"><button id="查询全部">读取全部股票</button></div><div id="全市场表"><p class="提示">输入名称或代码开始查询；需要浏览全部5461只股票时点击“读取全部股票”。</p></div></section>
<section id="说明" class="页面 面板 隐藏"><h2>如何阅读证据</h2><p>点击队列表最后一列的“查看证据”，可以看到该结构的原始分类、主要因子值和诊断状态。英文代码只保存在内部数据中，页面解释使用中文。</p><p>五个队列各自按独立合同排序，不计算跨结构总分。经济证据完全相同时共享名次，股票代码只维持页面显示稳定。第一版分数仅作历史对照，不参与第二版名次。</p><div id="身份说明" class="弱"></div></section>
</main><script>const 数据={data};
const 译={{INDUSTRY:'行业',THEME:'题材',STYLE:'风格',CURRENT_STRENGTH:'当前强势',STABILIZATION:'企稳',REACCELERATION:'再加速',NONE:'暂无结构',STEADY_TREND:'稳健趋势',STRONG_PULLBACK:'强势回撤',BREAKOUT_PREP:'突破准备',SECTOR_LEADER:'板块领先',EARLY_MOVER:'早期启动',EARLY_MOVER_ONLY:'早期启动',CORE_RESEARCH:'核心观察',SUPPORTED_RESEARCH:'一般观察',DIAGNOSTIC_ONLY:'诊断观察','A+':'甲加','A':'甲','B':'乙','C':'丙',CORE:'核心',SUPPORTED:'一般',STEADY_CORE:'稳健趋势核心',STEADY_ACCEPTABLE:'稳健趋势一般',CONTINUITY_WEAK:'连续性偏弱',OUTSIDE_V1_STEADY:'未进入原稳健趋势',PULLBACK_CORE:'强势回撤核心',PULLBACK_STRUCTURE_ONLY:'回撤结构成立但成交未确认',DEPTH_MISMATCH:'回撤深度不匹配',EARLY_PULLBACK:'回撤段尚短',OUTSIDE_V1_STRONG_PULLBACK:'未进入原强势回撤',BREAKOUT_CORE:'突破准备核心',BREAKOUT_RANGE_ONLY:'区间收缩确认',BREAKOUT_VOL_ONLY:'波动收缩确认',NEAR_HIGH_NO_CONTRACTION:'接近高点但没有收缩',OUTSIDE_V1_BREAKOUT_PREP:'未进入原突破准备',LEADER_CORE:'板块领先核心',LEADER_SUPPORTED:'板块领先一般',RETURN_LEADER_ONLY:'只有收益领先',STYLE_SELF_REINFORCED:'风格自我强化',DATA_INSUFFICIENT:'数据不足',OUTSIDE_V1_SECTOR_LEADER:'未进入原板块龙头',EARLY_SUPPORTED:'早期启动一般',SHORT_TERM_PULSE:'短期脉冲',SECTOR_ALREADY_STABILIZING:'板块已经企稳',OUTSIDE_V1_EARLY_MOVER:'未进入原早期启动',OK:'正常',HARD_GATE_FAILED:'基础条件未通过'}};
const 字段={{v1_steady_trend:'原版稳健趋势',up_day_ratio20:'20日上涨日比例',up_day_valid_count:'有效上涨日数',up_day_valid_ratio:'上涨日数据覆盖率',continuity_class:'连续性分类',return_concentration_20:'20日收益集中度',pulse_class:'短期脉冲分类',v2_steady_class:'第二版稳健趋势分类',v2_steady_hit:'稳健趋势是否命中',trend_r2_20:'20日趋势稳定度',trend_r2_60:'60日趋势稳定度',mdd20:'20日最大回撤',mdd60:'60日最大回撤',ret20:'20日涨幅',ret60:'60日涨幅',rs20:'20日相对强弱',pos60:'60日区间位置',dist_high20:'距离20日高点',RET60:'60日涨幅',TREND_SLOPE_60:'60日趋势斜率',TREND_R2_60:'60日趋势稳定度',RS60:'60日相对强弱',POS60:'60日区间位置',MDD20:'20日最大回撤',DIST_HIGH20:'距离20日高点',RET5:'5日涨幅',RET20:'20日涨幅',v1_strong_pullback:'原版强势回撤',recent_peak_date_20:'20日峰值日期',recent_peak_close_20:'20日峰值价格',days_since_peak_20:'距峰值交易日数',current_drawdown_from_peak_20:'当前峰值回撤',advance_amount_mean:'上涨段平均成交额',pullback_amount_mean:'回撤段平均成交额',pullback_amount_ratio:'回撤成交比例',segment_status:'回撤分段状态',depth_status:'回撤深度状态',volume_status:'成交确认状态',v1_breakout_prep:'原版突破准备',recent_range_10:'近期10日振幅',prior_range_10:'此前10日振幅',range_contraction_ratio:'区间收缩比例',recent_realized_vol_10:'近期10日实际波动',prior_realized_vol_10:'此前10日实际波动',realized_vol_contraction_ratio:'波动收缩比例',range_status:'区间状态',vol_status:'波动状态',v1_sector_leader:'原版板块龙头',v1_primary_sector_id:'原版主板块代码',v2_primary_sector_id:'第二版板块代码',v2_primary_sector_semantic:'第二版板块语义',qualifying_sector_count:'合格板块数',economic_sector_count:'经济板块数',trend_quality_class:'趋势质量',drawdown_quality_class:'回撤质量',position_quality_class:'位置质量',persistence_quality_class:'持续性质量',quality_dimension_strong_support_count:'强质量维度数',quality_dimension_nonweak_support_count:'非弱质量维度数',independent_strong_support_count:'强质量维度数（兼容字段）',independent_nonweak_support_count:'非弱质量维度数（兼容字段）',v1_early_mover:'原版早期启动',UP_DAY_RATIO20:'20日上涨日比例',RETURN_CONCENTRATION_20:'20日收益集中度',v2_sector_context_class:'第二版板块环境',trend_support:'趋势支持',position_support:'位置支持'}};
const 名=x=>x===true?'是':x===false?'否':译[x]||(typeof x==='string'&&/^[A-Z][A-Z0-9_]+$/.test(x)?'其他诊断状态':x)||'—',数=(x,d=2)=>x==null?'—':Number(x).toFixed(d),百=x=>x==null?'—':(Number(x)*100).toFixed(1)+'%',色=x=>x>0?'涨':x<0?'跌':'';
const 队列={{稳健趋势:['steady_queue_tier','v2_steady_class','稳健','steady'],强势回撤:['pullback_queue_tier','v2_pullback_class','回撤','pullback'],突破准备:['breakout_queue_tier','v2_breakout_class','突破','breakout'],板块领先:['leader_queue_tier','v2_leader_class','板块','leader'],早期启动:['early_queue_tier','v2_early_class','早期','early']}};let 当前队列='稳健趋势',研究带=new Set(['CORE_RESEARCH','SUPPORTED_RESEARCH']),板块类型='INDUSTRY';
const 表=(rows,cols)=>'<div class="表格框"><table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+cols.map(c=>'<td class="'+(c[3]?c[3](r[c[1]]):'')+'">'+(c[2]?c[2](r[c[1]],r,i):名(r[c[1]]))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const 证据=(r,key)=>{{let e=(数据.证据[key]||[]).find(x=>x.security_id===r.security_id)||{{}};let keep=Object.entries(e).filter(([k,v])=>v!=null&&!['security_id','shadow','production_eligible','shadow_ruleset_id'].includes(k)).slice(0,18);return '<details><summary>查看证据</summary><pre>'+keep.map(([k,v])=>(字段[k]||'诊断字段')+'：'+名(v)).join('\\n')+'</pre></details>'}};
const 个股列=(key)=>{{let p=队列[当前队列][3];return [['队内名次',p+'_queue_rank',x=>数(x,0)],['同研究带名次',p+'_tier_rank',x=>数(x,0)],['代码','security_id'],['名称','security_name'],['研究带','shadow_research_band',x=>'<span class="徽标 '+(x==='CORE_RESEARCH'?'核心':x==='SUPPORTED_RESEARCH'?'一般':'')+'">'+名(x)+'</span>'],['第二版分类',队列[当前队列][1]],['第一版等级','v1_research_priority',x=>名(x)],['20日涨幅','RET20',百,色],['20日相对强度百分位','stock_rs20_pct',百],['最佳板块','best_sector_name'],['证据','',(_,r)=>证据(r,key)]]}};
function 画卡片(){{document.getElementById('队列卡片').innerHTML=Object.entries(队列).map(([n,a])=>{{let core=数据.候选.filter(x=>x[a[0]]==='CORE').length,sup=数据.候选.filter(x=>x[a[0]]==='SUPPORTED').length;return '<div class="卡片"><span>'+n+'</span><strong>'+(core+sup)+'</strong><small>核心 '+core+'　一般 '+sup+'</small></div>'}}).join('')}}
function 画队列(){{let [tier,cls,key,p]=队列[当前队列],q=document.getElementById('队列搜索').value.trim().toLowerCase();let rows=数据.候选.filter(x=>x[tier]&&研究带.has(x.shadow_research_band)&&(!q||String(x.security_name+x.security_id).toLowerCase().includes(q))).sort((a,b)=>(a[p+'_queue_rank']??1e9)-(b[p+'_queue_rank']??1e9)||a.security_id.localeCompare(b.security_id));document.getElementById('队列口径').textContent=当前队列+'独立队列，共 '+rows.length+' 只；名次只在本结构内有效，不与其他结构横向比较。';document.getElementById('队列表').innerHTML=表(rows,个股列(key))}}
function 画板块(){{let q=document.getElementById('板块搜索').value.trim().toLowerCase();let rows=数据.板块.filter(x=>x.sector_type===板块类型&&(!q||String(x.sector_name+x.sector_id).toLowerCase().includes(q))).sort((a,b)=>(b.sector_rs20_pct??-1)-(a.sector_rs20_pct??-1));document.getElementById('板块表').innerHTML=表(rows,[['同类序号','',(_,r,i)=>i+1],['板块','sector_name'],['类型','sector_type'],['结构','primary_pattern'],['5日相对强度','sector_rs5_pct',百],['20日相对强度','sector_rs20_pct',百],['60日相对强度','sector_rs60_pct',百],['20日上涨宽度','sector_breadth_ret20_pos',百],['20日涨幅','sector_ret20_median',百,色],['回撤','sector_mdd20_median',百,色],['成交活跃度','sector_amount_ratio_median',x=>数(x)],['覆盖率','coverage',百]])}}
const 候选映射=new Map(数据.候选.map(x=>[x.security_id,x]));
function 显示板块成员(sid){{let rows=数据.成员.filter(x=>x.sector_id===sid).sort((a,b)=>(a.sector_member_rank??1e9)-(b.sector_member_rank??1e9)||a.security_id.localeCompare(b.security_id)).map(x=>Object.assign({{}},x,候选映射.get(x.security_id)||{{}}));let n=rows[0]?.sector_name||sid;document.getElementById('成员标题').textContent=n+'：全部 '+rows.length+' 个当前成员';document.getElementById('成员表').innerHTML=表(rows,[['板块内名次','sector_member_rank',x=>数(x,0)],['代码','security_id'],['名称','security_name'],['20日相对强度百分位','stock_rs20_pct',百],['20日涨幅','RET20',百,色],['第二版研究带','shadow_research_band',x=>x?名(x):'未进入五类队列'],['命中队列','queue_memberships',x=>x||'—'],['数据状态','quality_flag',x=>x==='OK'?'正常':名(x)]])}}
function 显示个股板块(stock){{let rows=数据.成员.filter(x=>x.security_id===stock.security_id).sort((a,b)=>a.sector_type.localeCompare(b.sector_type)||a.sector_name.localeCompare(b.sector_name));document.getElementById('所属标题').textContent=stock.security_name+'（'+stock.security_id+'）所属板块，共 '+rows.length+' 个';document.getElementById('所属表').innerHTML=表(rows,[['板块','sector_name'],['类型','sector_type',x=>名(x)],['板块代码','sector_id'],['成员名次','sector_member_rank',x=>数(x,0)],['成员依据','membership_basis',x=>'截止日通达信成员']])}}
function 查联动板块(){{let q=document.getElementById('联动板块搜索').value.trim().toLowerCase();if(!q)return;let x=数据.板块.find(x=>String(x.sector_name+x.sector_id).toLowerCase().includes(q));if(x)显示板块成员(x.sector_id)}}
function 查联动个股(){{let q=document.getElementById('联动个股搜索').value.trim().toLowerCase();if(!q)return;let x=数据.全市场.find(x=>String(x.security_name+x.security_id).toLowerCase().includes(q));if(x)显示个股板块(x)}}
function 查市场(all=false){{let q=document.getElementById('全市场搜索').value.trim().toLowerCase();if(!q&&!all)return;let cand=new Map(数据.候选.map(x=>[x.security_id,x]));let rows=数据.全市场.filter(x=>all||String(x.security_name+x.security_id).toLowerCase().includes(q)).slice(0,all?6000:100).map(x=>Object.assign({{}},x,cand.get(x.security_id)||{{research_priority:null,shadow_research_band:null}}));document.getElementById('全市场表').innerHTML=表(rows,[['代码','security_id'],['名称','security_name'],['候选状态','shadow_research_band',x=>x?名(x):'未命中结构'],['原版等级','research_priority',x=>x?名(x):'—'],['第一版结构','primary_pattern'],['现价','adj_close',x=>数(x)],['5日涨幅','RET5',百,色],['20日涨幅','RET20',百,色],['20日相对强弱','RS20',百,色],['最佳板块','best_sector_name'],['数据质量','quality_flag',x=>x==='OK'?'正常':名(x)]])}}
document.getElementById('队列按钮').innerHTML=Object.keys(队列).map((x,i)=>'<button class="队列按钮 '+(i?'':'选中')+'" data-q="'+x+'">'+x+'</button>').join('');document.querySelectorAll('.队列按钮').forEach(b=>b.onclick=()=>{{当前队列=b.dataset.q;document.querySelectorAll('.队列按钮').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');画队列()}});document.querySelectorAll('.研究带').forEach(b=>b.onclick=()=>{{研究带.has(b.dataset.band)?研究带.delete(b.dataset.band):研究带.add(b.dataset.band);b.classList.toggle('选中');画队列()}});document.querySelectorAll('.板块类型').forEach(b=>b.onclick=()=>{{板块类型=b.dataset.type;document.querySelectorAll('.板块类型').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');画板块()}});document.querySelectorAll('.页签').forEach(b=>b.onclick=()=>{{document.querySelectorAll('.页签').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');document.querySelectorAll('.页面').forEach(x=>x.classList.add('隐藏'));document.getElementById(b.dataset.page).classList.remove('隐藏')}});document.getElementById('队列搜索').oninput=画队列;document.getElementById('板块搜索').oninput=画板块;document.getElementById('联动板块搜索').oninput=查联动板块;document.getElementById('联动个股搜索').oninput=查联动个股;document.getElementById('全市场搜索').oninput=()=>查市场(false);document.getElementById('查询全部').onclick=()=>查市场(true);document.getElementById('身份说明').textContent='工作台身份：'+数据.身份.sha256+'；队列排序合同：'+数据.身份.queue_ranking_contract+'；成员快照：'+数据.身份.membership_snapshot_version;画卡片();画队列();画板块();</script></body></html>'''
