from __future__ import annotations

import html
import json


def render_workbench(cutoff, release_id, sectors, stocks, candidates, board, details, identity, membership, ranking):
    """Render a thin API-driven workbench shell.

    Published HTML intentionally contains no market rows. Data is read from
    the publication API with bounded pagination to keep the main thread and
    DOM responsive.
    """
    config = json.dumps({"publication_id": str(release_id)}, ensure_ascii=False)
    day = html.escape(str(cutoff), quote=True)
    pub = html.escape(str(release_id), quote=True)
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>第二版结构研究工作台 {day}</title><style>
:root{{--bg:#f3f6fb;--panel:#fff;--ink:#172033;--muted:#68758d;--line:#e3e8f1;--blue:#315efb;--red:#d94b55;--green:#169873;--gold:#d99820}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font-family:"Microsoft YaHei","PingFang SC",sans-serif}}header{{padding:27px max(22px,calc((100vw - 1500px)/2));background:linear-gradient(125deg,#152746,#28598d 62%,#3d7ac0);color:#fff}}h1{{margin:0 0 8px;font-size:27px}}header p{{margin:3px 0;color:#dce9fa}}main{{max-width:1500px;margin:auto;padding:18px}}nav,.工具{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}}button,input,select{{font:inherit;padding:9px 12px;border:1px solid #d5ddea;border-radius:9px;background:#fff}}button{{cursor:pointer}}button:disabled{{cursor:wait;opacity:.65}}button.选中{{color:#fff;background:var(--blue);border-color:var(--blue)}}.面板{{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;margin-bottom:16px;box-shadow:0 4px 18px rgba(28,47,78,.06)}}.卡片区{{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}}.卡片{{border:1px solid var(--line);border-radius:12px;padding:13px}}.卡片 strong{{display:block;font-size:23px;margin-top:5px}}.弱{{color:var(--muted);font-size:13px}}.提示{{padding:11px 13px;background:#fff8e7;border-left:4px solid var(--gold);border-radius:7px}}.表格框{{overflow:auto;max-height:680px;border:1px solid var(--line);border-radius:10px}}table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{white-space:nowrap;padding:9px 10px;border-bottom:1px solid var(--line);text-align:right}}th{{position:sticky;top:0;background:#edf2fa;color:#40506c;z-index:1}}th:nth-child(-n+3),td:nth-child(-n+3){{text-align:left}}tr:hover td{{background:#f5f8ff}}.涨{{color:var(--red);font-weight:600}}.跌{{color:var(--green);font-weight:600}}.徽标{{display:inline-block;padding:2px 8px;border-radius:12px;background:#eaf0ff;color:#214fd0;font-weight:700}}.核心{{background:#ffe9ea;color:#b82d38}}.一般{{background:#e9f5ef;color:#14795e}}.隐藏{{display:none}}.联动布局{{display:grid;grid-template-columns:330px 1fr;gap:14px}}.板块列表{{max-height:680px;overflow:auto;border:1px solid var(--line);border-radius:10px}}.板块项{{padding:10px 12px;border-bottom:1px solid var(--line);cursor:pointer}}.板块项:hover,.板块项.选中{{background:#edf3ff}}.分页{{display:flex;align-items:center;gap:10px;margin-top:10px;color:var(--muted);font-size:13px}}.证据按钮{{padding:5px 9px;border:1px solid #b8c7ef;border-radius:7px;background:#f4f7ff;color:#315efb;cursor:pointer;text-decoration:none}}.证据按钮:hover{{background:#e8efff}}.证据内容{{display:block;margin:8px 0 0;white-space:pre-wrap;font-family:inherit;font-size:12px;line-height:1.6;color:#3f4b61;max-width:680px}}.错误{{color:#b42318}}@media(max-width:900px){{.卡片区{{grid-template-columns:repeat(2,1fr)}}.联动布局{{grid-template-columns:1fr}}}}</style></head><body>
<style>.联动布局{{grid-template-columns:minmax(240px,300px) minmax(0,1fr)}}.联动布局>*{{min-width:0}}.联动布局 .表格框{{width:100%;max-width:100%}}.弹窗遮罩{{position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(14,25,45,.55)}}.弹窗遮罩.隐藏{{display:none}}.证据弹窗{{position:relative;width:min(760px,calc(100vw - 32px));max-height:min(760px,calc(100vh - 48px));overflow:auto;background:#fff;border-radius:16px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.28)}}.关闭弹窗{{position:absolute;right:14px;top:12px;width:36px;height:36px;padding:0;border:0;background:transparent;color:#60708a;font-size:27px;line-height:1}}.证据内容{{margin:8px 0 0;padding:12px 14px;background:#f7f9fd;border:1px solid #e1e7f2;border-radius:10px;white-space:normal;color:#3f4b61}}.证据结论{{padding-right:36px;font-size:15px;font-weight:700;color:#213a70;margin-bottom:10px}}.证据项{{display:grid;grid-template-columns:130px 82px minmax(230px,1fr);gap:10px;padding:7px 0;border-bottom:1px dashed #dfe5ef;font-size:13px;line-height:1.5}}.证据值{{font-weight:700;color:#172033}}.证据解释{{color:var(--muted)}}body.弹窗打开{{overflow:hidden}}@media(max-width:900px){{.证据项{{grid-template-columns:110px 1fr}}.证据解释{{grid-column:1/-1}}}}</style>
<header><h1>第二版结构研究工作台</h1><p>数据截止日：{day}　发布编号：{pub}</p><p>五类结构独立观察；页面排序只用于浏览，不构成跨结构优劣比较。</p></header><main>
<section class="面板"><div class="卡片区" id="队列卡片"><p class="弱">正在读取队列统计…</p></div><p class="提示">数据按接口分页读取；“核心观察、一般观察、诊断观察”表示证据完整程度。第一版甲加、甲、乙、丙仅作为历史评分对照，不代表上涨概率或交易评级。</p></section>
<nav><button class="页签 选中" data-page="概览">今日总览</button><button class="页签" data-page="队列">五类结构队列</button><button class="页签" data-page="板块">板块分类排行</button><button class="页签" data-page="联动">板块个股联动</button><button class="页签" data-page="全市场">全市场股票查询</button><button class="页签" data-page="说明">证据说明</button></nav>
<section id="概览" class="页面 面板"><h2>领先板块</h2><p class="弱">行业、题材、股票通用板块分开展示。“成分股当日涨幅中位数”是把板块内股票当日涨幅从低到高排列后取中间值，用来表示多数成分股的典型表现，不等于板块指数涨幅。</p><div id="概览板块"></div><h2 style="margin-top:22px">优先研究个股</h2><p class="弱">按接口分页读取候选池。</p><div id="概览个股"></div></section>
<section id="队列" class="页面 面板 隐藏"><h2>五类结构队列</h2><div class="工具" id="队列按钮"></div><div class="工具"><button class="研究带 选中" data-band="CORE_RESEARCH">核心观察</button><button class="研究带 选中" data-band="SUPPORTED_RESEARCH">一般观察</button><button class="研究带" data-band="DIAGNOSTIC_ONLY">读取诊断观察</button><input id="队列搜索" placeholder="搜索股票名称或代码"></div><p id="队列口径" class="弱"></p><div id="队列表"></div></section>
<section id="板块" class="页面 面板 隐藏"><h2>板块分类排行</h2><p class="弱">行业、题材、风格分别请求并分页。</p><div class="工具"><button class="板块类型 选中" data-type="INDUSTRY">行业</button><button class="板块类型" data-type="THEME">题材</button><button class="板块类型" data-type="STYLE">风格</button><input id="板块搜索" placeholder="搜索板块名称或代码"></div><div id="板块表"></div></section>
<section id="联动" class="页面 面板 隐藏"><h2>板块与个股联动</h2><p class="弱">板块列表、成员和反查结果均按接口请求；成员按页读取。</p><div class="工具"><input id="联动板块搜索" placeholder="筛选板块名称或代码"><input id="联动个股搜索" placeholder="输入股票名称或代码反查"></div><div class="联动布局"><div id="联动板块列表" class="板块列表"></div><div><h3 id="成员标题">选择一个板块查看当前成员</h3><div id="成员表"></div><h3 id="所属标题">输入股票查看全部所属板块</h3><div id="所属表"></div></div></div></section>
<section id="全市场" class="页面 面板 隐藏"><h2>全市场股票查询</h2><p class="弱">输入名称或代码后按页读取；不会一次性加载全部股票。</p><div class="工具"><input id="全市场搜索" placeholder="输入名称或代码"><button id="查询全部">读取股票</button></div><div id="全市场表"><p class="提示">输入名称或代码开始查询。</p></div></section>
<section id="说明" class="页面 面板 隐藏"><h2>如何阅读证据</h2><p>点击队列表的“查看证据”，按需读取该结构的原始分类、主要因子值和诊断状态。</p><p>五个队列各自按独立合同排序，不计算跨结构总分。第一版分数仅作历史对照，不参与第二版名次。</p><div id="身份说明" class="弱">正在读取工作台身份…</div></section>
</main><div id="证据遮罩" class="弹窗遮罩 隐藏" role="dialog" aria-modal="true" aria-labelledby="证据标题"><div class="证据弹窗"><button id="关闭证据" class="关闭弹窗" aria-label="关闭证据">×</button><h2 id="证据标题">结构证据</h2><div id="证据弹窗内容"></div></div></div><script>const 配置={config};
const 译={{INDUSTRY:'行业',THEME:'题材',STYLE:'风格',CURRENT_STRENGTH:'当前强势',STABILIZATION:'企稳',REACCELERATION:'再加速',NONE:'暂无结构',STEADY_TREND:'稳健趋势',STRONG_PULLBACK:'强势回撤',BREAKOUT_PREP:'突破准备',SECTOR_LEADER:'板块领先',EARLY_MOVER:'早期启动',EARLY_MOVER_ONLY:'早期启动',STEADY_QUEUE:'稳健趋势队列',PULLBACK_QUEUE:'强势回撤队列',BREAKOUT_QUEUE:'突破准备队列',LEADER_QUEUE:'板块领先队列',EARLY_QUEUE:'早期启动队列',CORE_RESEARCH:'核心观察',SUPPORTED_RESEARCH:'一般观察',DIAGNOSTIC_ONLY:'诊断观察','A+':'甲加','A':'甲','B':'乙','C':'丙',CORE:'核心',SUPPORTED:'一般',OK:'正常',STEADY_CORE:'稳健趋势核心',STEADY_ACCEPTABLE:'稳健趋势一般',PULLBACK_CORE:'强势回撤核心',BREAKOUT_CORE:'突破准备核心',LEADER_CORE:'板块领先核心',EARLY_SUPPORTED:'早期启动一般',DATA_INSUFFICIENT:'数据不足',CONTINUITY_STRONG:'连续性强',CONTINUITY_MODERATE:'连续性中等',CONTINUITY_WEAK:'连续性偏弱',PULSE_LOW:'短期脉冲低',PULSE_MODERATE:'短期脉冲中等',PULSE_HIGH:'短期脉冲高',CURRENT_TDX_MEMBERSHIP:'当前通达信成员'}};
const 字段={{v1_steady_trend:'原版稳健趋势',up_day_ratio20:'20日上涨日比例',up_day_valid_count:'有效上涨日数',up_day_valid_ratio:'上涨日数据覆盖率',continuity_class:'连续性分类',return_concentration_20:'20日收益集中度',pulse_class:'短期脉冲分类',v2_steady_class:'第二版稳健趋势分类',v2_steady_hit:'稳健趋势是否命中',trend_r2_20:'20日趋势稳定度',trend_r2_60:'60日趋势稳定度',mdd20:'20日最大回撤',mdd60:'60日最大回撤',ret20:'20日涨幅',ret60:'60日涨幅',rs20:'20日相对强弱',pos60:'60日区间位置',dist_high20:'距离20日高点',RET60:'60日涨幅',TREND_SLOPE_60:'60日趋势斜率',RS60:'60日相对强弱',POS60:'60日区间位置',MDD20:'20日最大回撤',DIST_HIGH20:'距离20日高点',RET5:'5日涨幅',RET20:'20日涨幅',v1_strong_pullback:'原版强势回撤',recent_peak_date_20:'20日峰值日期',recent_peak_close_20:'20日峰值价格',days_since_peak_20:'距峰值交易日数',current_drawdown_from_peak_20:'当前峰值回撤',pullback_amount_ratio:'回撤成交比例',segment_status:'回撤分段状态',depth_status:'回撤深度状态',volume_status:'成交确认状态',v1_breakout_prep:'原版突破准备',recent_range_10:'近期10日振幅',prior_range_10:'此前10日振幅',range_contraction_ratio:'区间收缩比例',recent_realized_vol_10:'近期10日实际波动',prior_realized_vol_10:'此前10日实际波动',realized_vol_contraction_ratio:'波动收缩比例',range_status:'区间状态',vol_status:'波动状态',v1_sector_leader:'原版板块龙头',v1_primary_sector_id:'原版主板块代码',v2_primary_sector_id:'第二版板块代码',v2_primary_sector_semantic:'第二版板块语义',qualifying_sector_count:'合格板块数',economic_sector_count:'经济板块数',trend_quality_class:'趋势质量',drawdown_quality_class:'回撤质量',position_quality_class:'位置质量',persistence_quality_class:'持续性质量',quality_dimension_strong_support_count:'强质量维度数',quality_dimension_nonweak_support_count:'非弱质量维度数',v1_early_mover:'原版早期启动',UP_DAY_RATIO20:'20日上涨日比例',RETURN_CONCENTRATION_20:'20日收益集中度',v2_sector_context_class:'第二版板块环境',trend_support:'趋势支持',position_support:'位置支持'}};
const 转义=x=>String(x??'—').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
const 名称=x=>转义(译[x]??x??'—'),数=(x,d=2)=>x==null||x===''?'—':Number(x).toFixed(d),百=x=>x==null||x===''?'—':(Number(x)*100).toFixed(1)+'%',金额=x=>{{if(x==null||x===''||!Number.isFinite(Number(x)))return '—';let n=Number(x),base=n>=1e12?1e12:n>=1e8?1e8:n>=1e4?1e4:1,unit=base===1e12?'万亿':base===1e8?'亿':base===1e4?'万':'元',v=n/base;return v.toFixed(v>=100?0:v>=10?1:2)+unit}},涨跌=x=>Number(x)>0?'涨':Number(x)<0?'跌':'',队列显示=x=>x?String(x).split('|').filter(Boolean).map(v=>名称(v)).join('、')||'—':'—';
const 表=(rows,cols)=>'<div class="表格框"><table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+cols.map(c=>'<td class="'+(c[3]?c[3](r[c[1]],r):'')+'">'+(c[2]?c[2](r[c[1]],r,i):名称(r[c[1]]))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
async function api(path){{let response=await fetch(path);let value=await response.json();if(!response.ok)throw Error(value.message||value.code||'读取失败');return value}}
const 页=(page,size,total)=>'<div class="分页"><button '+(page<=1?'disabled':'')+' data-page-action="prev">上一页</button><span>第 '+page+' 页，共 '+(total||0)+' 条</span><button '+(page*size>=total?'disabled':'')+' data-page-action="next">下一页</button></div>';
const 队列={{稳健趋势:['STEADY','steady','v2_steady_class'],强势回撤:['PULLBACK','pullback','v2_pullback_class'],突破准备:['BREAKOUT','breakout','v2_breakout_class'],板块领先:['LEADER','leader','v2_leader_class'],早期启动:['EARLY','early','v2_early_class']}};let 当前队列='稳健趋势',队列页=1,研究带=new Set(['CORE_RESEARCH','SUPPORTED_RESEARCH']),板块类型='INDUSTRY',板块页=1,联动页=1,成员页=1,市场页=1;
const overviewSectorCols=[['板块','sector_name'],['类型','sector_type',x=>名称(x)],['结构','primary_pattern',x=>名称(x)],['成分股当日涨幅中位数','sector_ret1_median',百,涨跌],['成分股当日成交额合计','sector_turnover_amount',金额],['20日相对强度','sector_rs20_pct',百],['20日上涨宽度','sector_breadth_ret20_pos',百],['20日涨幅','sector_ret20_median',百,涨跌],['成分股数','total_member_count',x=>数(x,0)],['覆盖率','coverage',百]];
const 文本列表=x=>Array.isArray(x)&&x.length?x.map(转义).join('、'):'—',摘要列表=x=>Array.isArray(x)&&x.length?'<span title="'+转义(x.join('、'))+'">'+x.slice(0,3).map(转义).join('、')+(x.length>3?' 等'+x.length+'项':'')+'</span>':'—',关联板块=(x,r)=>x?'<b>'+转义(x)+'</b><small class="弱" style="display:block;white-space:normal;min-width:240px;max-width:320px;margin-top:4px">'+转义(r.strength_sector_reason)+'</small>':'<span class="弱">暂无可确认</span>';
const candidateCols=[['代码','security_id'],['名称','security_name'],['最新价','latest_price',x=>数(x,2)],['当日涨幅','RET1',百,涨跌],['当日成交额','turnover_amount',金额],['第一版等级','research_priority',x=>名称(x)],['研究顺序分','priority_score',x=>数(x)],['主要结构','effective_pattern',x=>名称(x)],['20日涨幅','RET20',百,涨跌],['20日相对强度百分位','stock_rs20_pct',百],['当前强势关联板块','strength_sector_name',关联板块],['其他强势关联','other_strength_sectors',文本列表],['行情标签','market_tags',摘要列表]];
async function 画卡片(){{let values=await Promise.all(Object.values(队列).map(x=>api('/api/queues?publication_id='+encodeURIComponent(配置.publication_id)+'&queue='+x[0]+'&page=1&page_size=1')));document.getElementById('队列卡片').innerHTML=values.map((x,i)=>'<div class="卡片"><span>'+Object.keys(队列)[i]+'</span><strong>'+x.total+'</strong></div>').join('')}}
async function 画概览(){{try{{let types=[['INDUSTRY','行业板块',10],['THEME','概念板块',10],['STYLE','股票通用板块',5]],sectors=await Promise.all(types.map(t=>api('/api/sectors?publication_id='+encodeURIComponent(配置.publication_id)+'&type='+t[0]+'&page=1&page_size='+t[2]))),candidate=await api('/api/candidates?publication_id='+encodeURIComponent(配置.publication_id)+'&page=1&page_size=20');document.getElementById('概览板块').innerHTML=sectors.map((x,i)=>'<h3>'+types[i][1]+'</h3>'+表(x.items,overviewSectorCols)).join('');document.getElementById('概览个股').innerHTML=表(candidate.items,candidateCols)}}catch(e){{错误('概览',e)}}}}
function 队列条件(){{return [...研究带].join(',')||'__NONE__'}}
function 证据按钮(r,key){{return '<button class="证据按钮" data-queue="'+key+'" data-security="'+encodeURIComponent(r.security_id)+'" data-name="'+encodeURIComponent(r.security_name||r.security_id)+'">查看证据</button>'}}
const 证据分类={{steady:['稳健趋势','v2_steady_class'],pullback:['强势回撤','v2_pullback_class'],breakout:['突破准备','v2_breakout_class'],leader:['板块领先','v2_leader_class'],early:['早期启动','v2_early_class']}};
const 证据百分比=x=>x==null||x===''?'—':(Number(x)*100).toFixed(1)+'%';
function 友好证据(item,key){{let meta=证据分类[key]||['当前结构',''],classification=meta[1]&&item[meta[1]]?名称(item[meta[1]]):'已进入该结构队列',rows=[];const add=(label,value,help)=>{{if(value!=null&&value!=='')rows.push([label,证据百分比(value),help])}};add('近20日涨跌',item.ret20??item.RET20,'过去20个交易日累计涨跌，只描述历史表现。');add('近60日涨跌',item.ret60??item.RET60,'过去60个交易日累计涨跌，用于观察较长周期。');add('近20日最大回撤',item.mdd20??item.MDD20,'期间从阶段高点到随后低点的最大回落；越接近0，回落越小。');add('近60日最大回撤',item.mdd60??item.MDD60,'过去60个交易日内经历的最大阶段回落。');add('距20日高点',item.dist_high20??item.DIST_HIGH20,'例如 -6.7% 表示当前价比近20日最高价低约6.7%。');add('20日上涨日占比',item.up_day_ratio20??item.UP_DAY_RATIO20,'过去20个有效交易日中，收涨日所占比例。');add('20日趋势稳定度',item.trend_r2_20??item.TREND_R2_20,'数值越高，过去20日走势越接近稳定趋势。');let tags=[];if(item.continuity_class)tags.push('走势连续性：'+名称(item.continuity_class));if(item.pulse_class)tags.push('短期脉冲：'+名称(item.pulse_class));return '<div class="证据内容"><div class="证据结论">'+meta[0]+'判断：'+classification+(tags.length?'；'+tags.join('；'):'')+'</div>'+rows.map(r=>'<div class="证据项"><span>'+r[0]+'</span><span class="证据值">'+r[1]+'</span><span class="证据解释">'+r[2]+'</span></div>').join('')+'<div class="弱" style="margin-top:10px">这些数值用于解释当前结构，不代表未来涨跌或交易建议。</div></div>'}}
function 关闭证据弹窗(){{document.getElementById('证据遮罩').classList.add('隐藏');document.body.classList.remove('弹窗打开')}}
async function 读取证据(button){{let queue=button.dataset.queue,security=decodeURIComponent(button.dataset.security),name=decodeURIComponent(button.dataset.name||button.dataset.security),overlay=document.getElementById('证据遮罩'),content=document.getElementById('证据弹窗内容');button.disabled=true;button.textContent='正在读取…';document.getElementById('证据标题').textContent=name+' · 结构证据';content.innerHTML='<p class="弱">正在读取证据…</p>';overlay.classList.remove('隐藏');document.body.classList.add('弹窗打开');try{{let result=await api('/api/evidence?publication_id='+encodeURIComponent(配置.publication_id)+'&queue='+encodeURIComponent(queue)+'&security_id='+encodeURIComponent(security));content.innerHTML=result.item?友好证据(result.item,queue):'<div class="证据内容">暂无可展示证据</div>'}}catch(e){{content.innerHTML='<p class="错误">证据读取失败，请关闭后重试。</p>'}}finally{{button.disabled=false;button.textContent='查看证据'}}}}
async function 画队列(){{let [apiQueue,key,cls]=队列[当前队列],q=document.getElementById('队列搜索').value.trim(),band=队列条件();try{{let x=await api('/api/queues?publication_id='+encodeURIComponent(配置.publication_id)+'&queue='+apiQueue+'&page='+队列页+'&page_size=50&band='+encodeURIComponent(band)+'&q='+encodeURIComponent(q)),cols=[['A股队内名次','a_share_queue_rank',x=>数(x,0)],['同研究带名次',''+key+'_tier_rank',x=>数(x,0)],['代码','security_id'],['名称','security_name'],['最新价','latest_price',x=>数(x,2)],['当日涨幅','RET1',百,涨跌],['当日成交额','turnover_amount',金额],['研究带','shadow_research_band',x=>'<span class="徽标 '+(x==='CORE_RESEARCH'?'核心':x==='SUPPORTED_RESEARCH'?'一般':'')+'">'+名称(x)+'</span>'],['第二版分类',cls,x=>名称(x)],['第一版等级','v1_research_priority',x=>名称(x)],['20日涨幅','RET20',百,涨跌],['最佳板块','best_sector_name'],['证据','',(_,r)=>证据按钮(r,key)]];let root=document.getElementById('队列表');root.innerHTML=表(x.items,cols)+页(x.page,x.page_size,x.total);root.querySelector('[data-page-action="prev"]').onclick=()=>{{队列页--;画队列()}};root.querySelector('[data-page-action="next"]').onclick=()=>{{队列页++;画队列()}};document.getElementById('队列口径').textContent=当前队列+'独立队列，仅含沪深北A股并严格按结构合同名次升序；第 '+x.page+' 页，共 '+x.total+' 只。'}}catch(e){{错误('队列',e)}}}}
async function 画板块(){{let q=document.getElementById('板块搜索').value.trim();try{{let x=await api('/api/sectors?publication_id='+encodeURIComponent(配置.publication_id)+'&type='+板块类型+'&q='+encodeURIComponent(q)+'&page='+板块页+'&page_size=50'),root=document.getElementById('板块表');root.innerHTML=表(x.items,[['同类序号','',(_,r,i)=>(x.page-1)*x.page_size+i+1],...overviewSectorCols])+页(x.page,x.page_size,x.total);root.querySelector('[data-page-action="prev"]').onclick=()=>{{板块页--;画板块()}};root.querySelector('[data-page-action="next"]').onclick=()=>{{板块页++;画板块()}}}}catch(e){{错误('板块',e)}}}}
let 联动板块结果=[];async function 画联动板块列表(){{let q=document.getElementById('联动板块搜索').value.trim();try{{let x=await api('/api/sectors?publication_id='+encodeURIComponent(配置.publication_id)+'&q='+encodeURIComponent(q)+'&page='+联动页+'&page_size=50'),root=document.getElementById('联动板块列表');联动板块结果=x.items;root.innerHTML=联动板块结果.map((s,i)=>'<div class="板块项" data-i="'+i+'"><b>'+名称(s.sector_name)+'</b><br><small>'+名称(s.sector_type)+' · '+名称(s.primary_pattern)+' · 板块内 '+数(s.total_member_count,0)+' 只</small></div>').join('')+页(x.page,x.page_size,x.total);root.querySelectorAll('.板块项').forEach(e=>e.onclick=()=>{{root.querySelectorAll('.板块项').forEach(z=>z.classList.remove('选中'));e.classList.add('选中');成员页=1;画成员(联动板块结果[+e.dataset.i].sector_id)}});root.querySelector('[data-page-action="prev"]').onclick=()=>{{联动页--;画联动板块列表()}};root.querySelector('[data-page-action="next"]').onclick=()=>{{联动页++;画联动板块列表()}};if(联动板块结果.length)root.querySelector('.板块项').click()}}catch(e){{错误('联动板块',e)}}}}
async function 画成员(sid){{try{{let x=await api('/api/linkage?publication_id='+encodeURIComponent(配置.publication_id)+'&sector_id='+encodeURIComponent(sid)+'&page='+成员页+'&page_size=100'),root=document.getElementById('成员表');document.getElementById('成员标题').textContent='板块内共 '+(x.sector_member_count??x.total)+' 只 A 股；当前第 '+x.page+' 页';root.innerHTML=表(x.items,[['板块内名次','sector_member_rank',x=>数(x,0)],['代码','security_id'],['名称','security_name'],['最新价','latest_price',x=>数(x,2)],['当日涨幅','RET1',百,涨跌],['当日成交额','turnover_amount',金额],['20日相对强度百分位','stock_rs20_pct',百],['20日涨幅','RET20',百,涨跌],['研究带','shadow_research_band',x=>x?名称(x):'未进入五类队列'],['命中队列','queue_memberships',队列显示],['数据状态','quality_flag',x=>x==='OK'?'正常':名称(x)]])+页(x.page,x.page_size,x.total);root.querySelector('[data-page-action="prev"]').onclick=()=>{{成员页--;画成员(sid)}};root.querySelector('[data-page-action="next"]').onclick=()=>{{成员页++;画成员(sid)}}}}catch(e){{错误('成员',e)}}}}
async function 查联动个股(){{let q=document.getElementById('联动个股搜索').value.trim();if(!q){{document.getElementById('所属表').innerHTML='';return}}try{{let x=await api('/api/stocks?publication_id='+encodeURIComponent(配置.publication_id)+'&q='+encodeURIComponent(q)+'&page=1&page_size=10');if(!x.items.length){{document.getElementById('所属标题').textContent='没有找到匹配股票';document.getElementById('所属表').innerHTML='';return}}let stock=x.items[0],linked=await api('/api/linkage?publication_id='+encodeURIComponent(配置.publication_id)+'&security_id='+encodeURIComponent(stock.security_id)+'&page=1&page_size=100');document.getElementById('所属标题').textContent=stock.security_name+'（'+stock.security_id+'）所属板块，共 '+linked.total+' 个';document.getElementById('所属表').innerHTML=表(linked.items,[['板块','sector_name'],['类型','sector_type',x=>名称(x)],['板块代码','sector_id'],['成员名次','sector_member_rank',x=>数(x,0)],['成员依据','membership_basis',x=>名称(x)]])}}catch(e){{错误('股票反查',e)}}}}
async function 查市场(all=false){{let q=document.getElementById('全市场搜索').value.trim();if(!q&&!all){{document.getElementById('全市场表').innerHTML='<p class="提示">输入名称或代码开始查询。默认范围仅含沪深北 A 股。</p>';return}}try{{let x=await api('/api/stocks?publication_id='+encodeURIComponent(配置.publication_id)+'&q='+encodeURIComponent(q)+'&page='+市场页+'&page_size=100'),root=document.getElementById('全市场表');root.innerHTML=表(x.items,[['代码','security_id'],['名称','security_name'],['最新价','latest_price',x=>数(x,2)],['当日涨幅','RET1',百,涨跌],['当日成交额','turnover_amount',金额],['20日涨幅','RET20',百,涨跌],['20日相对强度','RS20',百,涨跌],['最佳板块','best_sector_name'],['数据质量','quality_flag',x=>x==='OK'?'正常':名称(x)]])+页(x.page,x.page_size,x.total);root.querySelector('[data-page-action="prev"]').onclick=()=>{{市场页--;查市场(all)}};root.querySelector('[data-page-action="next"]').onclick=()=>{{市场页++;查市场(all)}}}}catch(e){{错误('全市场',e)}}}}
async function 说明(){{try{{let x=await api('/api/identity?publication_id='+encodeURIComponent(配置.publication_id));document.getElementById('身份说明').textContent='工作台身份：'+(x.source_identity_sha256||'—')+'；接口合同：'+x.api_contract+'；成员快照：'+(x.membership_snapshot_id||'—')}}catch(e){{错误('身份',e)}}}}
function 错误(title,e){{let element=document.querySelector('.页面:not(.隐藏)');if(element)element.insertAdjacentHTML('afterbegin','<p class="提示 错误">'+转义(title+'读取失败：'+e.message)+'</p>')}}
document.getElementById('队列按钮').innerHTML=Object.keys(队列).map((x,i)=>'<button class="队列按钮 '+(i?'':'选中')+'" data-q="'+x+'">'+x+'</button>').join('');document.querySelectorAll('.队列按钮').forEach(b=>b.onclick=()=>{{当前队列=b.dataset.q;队列页=1;document.querySelectorAll('.队列按钮').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');画队列()}});document.querySelectorAll('.研究带').forEach(b=>b.onclick=()=>{{研究带.has(b.dataset.band)?研究带.delete(b.dataset.band):研究带.add(b.dataset.band);b.classList.toggle('选中');队列页=1;画队列()}});document.querySelectorAll('.板块类型').forEach(b=>b.onclick=()=>{{板块类型=b.dataset.type;板块页=1;document.querySelectorAll('.板块类型').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');画板块()}});document.querySelectorAll('.页签').forEach(b=>b.onclick=()=>{{document.querySelectorAll('.页签').forEach(x=>x.classList.remove('选中'));b.classList.add('选中');document.querySelectorAll('.页面').forEach(x=>x.classList.add('隐藏'));document.getElementById(b.dataset.page).classList.remove('隐藏');if(b.dataset.page==='队列')画队列();if(b.dataset.page==='板块')画板块();if(b.dataset.page==='联动')画联动板块列表();if(b.dataset.page==='说明')说明()}});document.getElementById('队列表').addEventListener('click',event=>{{let button=event.target.closest('.证据按钮');if(button)读取证据(button)}});document.getElementById('关闭证据').onclick=关闭证据弹窗;document.getElementById('证据遮罩').onclick=event=>{{if(event.target===event.currentTarget)关闭证据弹窗()}};document.addEventListener('keydown',event=>{{if(event.key==='Escape')关闭证据弹窗()}});document.getElementById('队列搜索').oninput=()=>{{队列页=1;画队列()}};document.getElementById('板块搜索').oninput=()=>{{板块页=1;画板块()}};document.getElementById('联动板块搜索').oninput=()=>{{联动页=1;画联动板块列表()}};document.getElementById('联动个股搜索').oninput=查联动个股;document.getElementById('全市场搜索').oninput=()=>{{市场页=1;查市场(false)}};document.getElementById('查询全部').onclick=()=>{{市场页=1;查市场(true)}};画卡片();画概览();</script></body></html>'''
