-- V4-16 R23 isolated engineering migration V1; never production apply.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS shadow_source_readiness_receipts(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_source_readiness_receipts_no_update BEFORE UPDATE ON shadow_source_readiness_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_source_readiness_receipts_no_delete BEFORE DELETE ON shadow_source_readiness_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_observation_slots(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_observation_slots_no_update BEFORE UPDATE ON shadow_observation_slots BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_observation_slots_no_delete BEFORE DELETE ON shadow_observation_slots BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_source_freeze_manifests(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_source_freeze_manifests_no_update BEFORE UPDATE ON shadow_source_freeze_manifests BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_source_freeze_manifests_no_delete BEFORE DELETE ON shadow_source_freeze_manifests BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_publications(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_publications_no_update BEFORE UPDATE ON shadow_publications BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_publications_no_delete BEFORE DELETE ON shadow_publications BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_state_heads(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_state_heads_no_update BEFORE UPDATE ON shadow_state_heads BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_state_heads_no_delete BEFORE DELETE ON shadow_state_heads BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_observations(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_observations_no_update BEFORE UPDATE ON shadow_observations BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_observations_no_delete BEFORE DELETE ON shadow_observations BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_first_enrollments(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_first_enrollments_no_update BEFORE UPDATE ON shadow_first_enrollments BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_first_enrollments_no_delete BEFORE DELETE ON shadow_first_enrollments BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_membership_snapshots(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_membership_snapshots_no_update BEFORE UPDATE ON shadow_membership_snapshots BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_membership_snapshots_no_delete BEFORE DELETE ON shadow_membership_snapshots BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_due_outbox(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_due_outbox_no_update BEFORE UPDATE ON shadow_due_outbox BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_due_outbox_no_delete BEFORE DELETE ON shadow_due_outbox BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_outcome_revisions(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_outcome_revisions_no_update BEFORE UPDATE ON shadow_outcome_revisions BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_outcome_revisions_no_delete BEFORE DELETE ON shadow_outcome_revisions BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_health_receipts(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_health_receipts_no_update BEFORE UPDATE ON shadow_health_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_health_receipts_no_delete BEFORE DELETE ON shadow_health_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_artifacts(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_artifacts_no_update BEFORE UPDATE ON shadow_artifacts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_artifacts_no_delete BEFORE DELETE ON shadow_artifacts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_transaction_receipts(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_transaction_receipts_no_update BEFORE UPDATE ON shadow_transaction_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_transaction_receipts_no_delete BEFORE DELETE ON shadow_transaction_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_control_receipts(id TEXT PRIMARY KEY, namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'), evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'), payload TEXT NOT NULL CHECK(json_valid(payload)), digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_control_receipts_no_update BEFORE UPDATE ON shadow_control_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_control_receipts_no_delete BEFORE DELETE ON shadow_control_receipts BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TABLE IF NOT EXISTS shadow_publication_heads(slot_id TEXT PRIMARY KEY, publication_id TEXT NOT NULL REFERENCES shadow_publications(id), revision INTEGER NOT NULL CHECK(revision>0));
CREATE TRIGGER IF NOT EXISTS shadow_head_cas BEFORE UPDATE ON shadow_publication_heads WHEN NEW.slot_id!=OLD.slot_id OR NEW.revision!=OLD.revision+1 BEGIN SELECT RAISE(ABORT,'HEAD_CAS'); END;
CREATE TRIGGER IF NOT EXISTS shadow_head_no_delete BEFORE DELETE ON shadow_publication_heads BEGIN SELECT RAISE(ABORT,'HEAD_DELETE_FORBIDDEN'); END;
CREATE UNIQUE INDEX IF NOT EXISTS shadow_receipt_identity ON shadow_source_readiness_receipts(json_extract(payload,'$.source_identity'),json_extract(payload,'$.source_revision'),json_extract(payload,'$.target_trade_date'));
CREATE UNIQUE INDEX IF NOT EXISTS shadow_slot_revision ON shadow_observation_slots(json_extract(payload,'$.slot_id'),json_extract(payload,'$.revision'));
CREATE UNIQUE INDEX IF NOT EXISTS shadow_pub_revision ON shadow_publications(json_extract(payload,'$.slot_id'),json_extract(payload,'$.revision'));
CREATE UNIQUE INDEX IF NOT EXISTS shadow_original_event ON shadow_first_enrollments(json_extract(payload,'$.logical_event_id'));
CREATE UNIQUE INDEX IF NOT EXISTS shadow_due_identity ON shadow_due_outbox(json_extract(payload,'$.enrollment_id'),json_extract(payload,'$.horizon'));
CREATE UNIQUE INDEX IF NOT EXISTS shadow_artifact_identity ON shadow_artifacts(json_extract(payload,'$.kind'),json_extract(payload,'$.key'));
PRAGMA user_version=1;
CREATE TABLE IF NOT EXISTS shadow_runtime_operations(id TEXT PRIMARY KEY,namespace TEXT NOT NULL CHECK(namespace='SHADOW_V4'),evidence_origin TEXT NOT NULL CHECK(evidence_origin='ENGINEERING_FIXTURE'),payload TEXT NOT NULL CHECK(json_valid(payload)),digest TEXT NOT NULL CHECK(length(digest)=64));
CREATE TRIGGER IF NOT EXISTS shadow_operations_no_update BEFORE UPDATE ON shadow_runtime_operations BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS shadow_operations_no_delete BEFORE DELETE ON shadow_runtime_operations BEGIN SELECT RAISE(ABORT,'APPEND_ONLY'); END;
