"""Contract design only: never launches Shadow, enrollment, publication or settlement."""
from scripts.r22_io import *
from scripts.validate_pre16_finalization import validate as entry_gate

def build(root=ROOT):
    assert entry_gate(root)['PRE16_EXTERNAL_ACCEPTANCE_FORMALIZATION']=='PASS_LOCAL'
    assert read('reports/pre16_finalization/FINALIZATION_GATE.json',root)['GLOBAL_V4_16_CONTRACT_ENTRY_BLOCKERS']==[]
    v15=read('data/v4/V4_15_ACCEPTED_HEAD.json',root)
    inputs={k:ref(p,root) for k,p in dict(v15='data/v4/V4_15_ACCEPTED_HEAD.json',stage='data/v4/V4_STAGE_ACCEPTED_HEAD.json',data='data/v4/V4_DATA_ACCEPTED_HEAD.json',current_stage='config/v4_current_stage_authority_v2.json',audit_head=HEAD,audit_config=CONFIG,governance_acceptance=ACCEPT,canonical_issue_map='reports/pre16_finalization/CANONICAL_ISSUE_MAP.json',blocking_scope_matrix='reports/pre16_finalization/BLOCKING_SCOPE_MATRIX.json',architecture=ARCH,r21_external_audit=R21_AUDIT,phase0='reports/v4_phase0/V4_PHASE0_FINAL_RECEIPT_R5_20260928.json',cohort='config/v4_15_cohort_contract_v1.json',parameters='config/v4_parameter_registry_v1.json',due='config/v4_15_due_planner_contract_v1.json',revision='config/v4_15_settlement_revision_contract_v1.json',readback='config/v4_15_settlement_readback_contract_v1.json',status='config/v4_15_outcome_status_contract_v1.json').items()}
    inputs.update(v15_package=v15['bindings']['contract_package'],calendar=v15['bindings']['calendar'],membership=v15['bindings']['membership'],forward_projection=v15['bindings']['forward_projection'])
    common=dict(version='1.0.0',execution_baseline=BASE,status='CONTRACT_FROZEN_LOCAL_PENDING_EXTERNAL_AUDIT',accepted_predecessor=inputs['v15'],model_parameter_identity=dict(model_contract_id='DIGEST_CODE_AST_PARAMETERS_SOURCE_SEMANTICS',parameter_set_id='EXACT_ACCEPTED_PARAMETER_SET',change='NEW_MODEL_ID_AND_AFFECTED_LINEAGE_BOUNDARY'),source_authority=inputs,time_semantics=dict(timezone='Asia/Shanghai',timestamp_storage='UTC_RFC3339',market_dates='EXACT_ACCEPTED_CALENDAR_ONLY'),namespace='SHADOW_V4',PIT_rules=dict(observed='RUNTIME_REAL_FREEZE_AND_EXACT_VISIBILITY_PROOF_ONLY',reconstruction_cannot_upgrade=True),UNKNOWN_degradation='FAIL_CLOSED_AFFECTED_CAPABILITY; UNKNOWN_HARD_REQUIREMENT_NEVER_PASSES',idempotency='FROZEN_COMPOSITE_IDENTITIES_AND_EXACT_CONTENT_DIGEST',revision_behavior='APPEND_ONLY; ORIGINAL_IDENTITIES_AND_FROZEN_T0_IMMUTABLE',negative_vectors='config/v4_16_machine_vectors_v1.json',acceptance_criteria='INDEPENDENT_CONTRACT_COMPLETENESS_ONLY; NO_RUNTIME_GRANT',production=False,shadow=False,focus=False,V4_16=False,runtime_implemented=False,runtime_authorized=False,REAL_SHADOW_OBSERVATIONS=0,SHADOW_STABLE='NOT_GRANTED',PROVISIONAL_FORWARD_EVIDENCE='NOT_GRANTED',FORWARD_SUPPORTED='NOT_GRANTED')
    contracts={}
    def put(name,**body):
        value=dict(common,contract_id=name.upper(),**body);path='config/'+name+'.json';atomic(path,value,root);contracts[name]=ref(path,root)
    slot_fields=['trade_date','model_contract_id','parameter_set_id','state_lineage_id','execution_mode','namespace','scheduled_cutoff_at','observation_deadline','source_provider_available_at','system_available_at','computation_started_at','computation_finished_at','accepted_at','slot_status','publication_id','core_revision','source_manifest_digest','capability_scope']
    # Existing cohort explicitly delegates to unset V4-00C deadline policy.
    search=subprocess.run(['git','grep','-n','-I','-E','scheduled_cutoff|observation_deadline|publication_deadline',BASE,'--','config','reports/v4_phase0','data/v4/V4_STAGE_ACCEPTED_HEAD.json'],cwd=root,capture_output=True)
    assert search.returncode in [0,1]
    atomic('reports/r22/CUTOFF_AUTHORITY_INVENTORY.json',dict(execution_baseline=BASE,command=search.args,matches=search.stdout.decode('utf8').splitlines(),reviewed_bindings=[inputs['phase0'],inputs['stage'],inputs['cohort'],inputs['parameters'],inputs['architecture']],finding='NO_EXACT_ACCEPTED_SCHEDULED_CUTOFF_AND_OBSERVATION_DEADLINE_VALUES; V4-15 delegates unset policy to V4-00C',status='BLOCKED_AFFECTED_SCOPE',affected_scope='REALTIME_OBSERVATION_SLOT_AND_ORIGINAL_REALTIME_ENROLLMENT',scheduled_cutoff_at=None,observation_deadline=None,numeric_times_invented=False),root)
    atomic('reports/r22/R22_CLOCK_AUTHORITY_REPAIR_01.json',dict(audit_id='R22_CLOCK_AUTHORITY_REPAIR_01',priority='P0_AFFECTED_SCOPE',status='OPEN_CONTRACT_REPAIR_REQUIREMENT',version='1.0.0',scope='Accepted V4-00C scheduled cutoff and observation publication deadline',engineering_block=False,runtime_observation_block=True,evidence=ref('reports/r22/CUTOFF_AUTHORITY_INVENTORY.json',root),required_closure='SEPARATE_VERSIONED_ACCEPTED_CLOCK_CONTRACT_WITH_MARKET_CALENDAR_TIMEZONE_UTC_AND_EXACT_EXTERNAL_AUTHORITY; NO_CONVENIENT_TIME',global_governance_blocker=False),root)
    put('v4_16_observation_slot_contract_v1',slot_key=['model_contract_id','state_lineage_id','trade_date'],fields=slot_fields,clock_authority=dict(status='BLOCKED_AFFECTED_SCOPE',scheduled_cutoff_at=None,observation_deadline=None,accepted_clock_binding=None,timezone='Asia/Shanghai',stored_timestamp='UTC',repair_requirement=ref('reports/r22/R22_CLOCK_AUTHORITY_REPAIR_01.json',root)),first_original_rule='FIRST_COMPLIANT_ACCEPTED_PUBLICATION_WITHIN_ACCEPTED_DEADLINE_ONLY',visibility_order=['source_provider_available_at <= system_available_at','system_available_at <= scheduled_cutoff_at','computation_started_at >= frozen_input_time','computation_started_at <= computation_finished_at <= accepted_at <= observation_deadline'],source_freeze_fields=['calendar_identity','universe_identity','membership_identity','consumed_source_key_revision_digest','model_contract_id','parameter_digest','source_manifest_digest','prior_session_state_head','scheduled_cutoff_at'],slot_states=['BLOCKED_MISSING_ACCEPTED_CLOCK_AUTHORITY','ACCEPTED_ON_TIME','MISSED_OBSERVATION_SLOT'],no_clock='BLOCK_REALTIME_ENROLLMENT_NO_PIT_CLAIM',late_missing='MISSED_OBSERVATION_SLOT; LATER_BACKFILL_RECONSTRUCTED_ONLY',original_samples_per_slot=1,reset_observation_start=False,same_day_revision_parent='REVISION_DIFF_ONLY; NEVER_PREVIOUS_MARKET_SESSION')
    put('v4_16_shadow_namespace_contract_v1',required_identity=['model_contract_id','execution_mode','namespace','publication_id','core_revision','state_lineage_id'],execution_mode='SHADOW',read_namespace='SHADOW_V4',write_namespace='SHADOW_V4',legacy_namespace='PRODUCTION_LEGACY',legacy_writes=False,legacy_prior_reads=False,prior_session_state_head=['previous_market_session','accepted_publication_id','core_revision','logical_digest','model_contract_id','state_lineage_id','namespace'],prior_rule='EXACT_PREVIOUS_MARKET_SESSION_ACCEPTED_SHADOW_HEAD; SAME_PREDECESSOR_ALL_SAME_DAY_REVISIONS',missing_prior='EXPLICIT_GAP; NO_SKIP_DAY_YESTERDAY; NO_STATE_UPGRADE_OR_EXIT_UNTIL_ORDERED_REPAIR_OR_ACCEPTED_INITIALIZATION_BOUNDARY',prior_correction='NEW_CORRECTED_RECONSTRUCTION_LINEAGE; NEVER_MUTATE_FROZEN_T',namespace_date_lock=['namespace','trade_date','model_contract_id','state_lineage_id'],acceptance_transaction=['STAGING_INVISIBLE','QUALITY_IDENTITY_COVERAGE_CHECK','CONSUMED_MANIFEST_COHORT_OUTBOX_ATOMIC_WRITE','ACCEPTED_HEAD_CAS','COMMIT_VISIBLE'],failed_acceptance='WHOLE_BATCH_INVISIBLE; NO_VISIBLE_ENROLLMENT_BEFORE_HEAD_ACCEPTED',legacy_production_continues=True,production_focus_changes=False,default_UI_changes=False,rollback=dict(action='STOP_NEW_SHADOW_ACCEPTANCE_AND_SWITCH_ONLY_SHADOW_READER_CONFIGURATION',preserve=['legacy_production','accepted_publications','observations','T0','pending_settlements','source_manifests','revision_audit_trail'],drill_required_before_stable=True,formal_DB_migration_apply=False))
    put('v4_16_settlement_worker_contract_v1',execution_order=['ACCEPTED_SHADOW_PUBLICATION','DUE_PLANNER','DUE_QUEUE_OUTBOX','ACCEPTED_FUTURE_DATA_HEAD','SETTLEMENT','APPEND_EVALUATION_REVISION','READBACK'],queue_key=['namespace','model_contract_id','state_lineage_id','enrollment_id','horizon','due_trade_date','outcome_contract_id'],delivery_key=['queue_key','evaluation_source_digest'],result_key=['enrollment_id','horizon','outcome_contract_id','evaluation_source_digest'],horizons=[1,3,5,10,20],due_calendar=inputs['calendar'],future_read_guard='EXACT_ACCEPTED_SOURCE_AUTHORITY_AND_MARKET_SESSION_DUE_AND_AVAILABLE; NO_PRE_DUE_READ',unavailable_endpoint='PENDING_DUE_SOURCE_UNAVAILABLE_WITH_REASON; NOT_ZERO_OR_RIGHT_CENSOR',worker_trigger='DAILY_AFTER_ACCEPTED_SOURCE_AVAILABILITY; DURABLE_OUTBOX_RETRY_INDEPENDENT_OF_CORE_ACCEPTANCE',queue_semantics=dict(delivery='AT_LEAST_ONCE',result='EXACT_SOURCE_IDEMPOTENT',claim='COMPARE_AND_SET_QUEUE_ITEM',ack='ONLY_AFTER_IMMUTABLE_RESULT_REVISION_ACCEPTED',failure='RETRY_WITH_BACKLOG_REASON_NO_SOURCE_FALLBACK',correction='NEW_EVALUATION_SOURCE_DIGEST_APPENDS_REVISION'),preserve=['T0','enrollment_id','control_assignment_ids','benchmark_ids','FIRST_OBSERVED','first_observed_result'],readback=['FIRST_OBSERVED','LATEST_VALIDATED','LATEST_CORRECTED','pending_due_items','evaluation_revision_history'],settle_invalidated_exited=True,settle_UI_excluded=True,raw_provider_fallback=False,suspension_moves_horizon=False,recompute_core_formulas=False,formulas_authority=inputs['v15_package'],controls_benchmark_identity='FREEZE_T0; NO_REDRAW_NO_FUTURE_REFILL_NO_RENORMALIZATION',maturity_debt=dict(CURRENT_REAL_MATURITY_EVIDENCE='NONE',PROVED_HORIZONS=[],UNPROVED_HORIZONS=[1,3,5,10,20],increment='ONLY_ACCEPTED_V4_15_REAL_DUE_ENDPOINT_RECEIPT_AND_DEBT_VALIDATOR; NOT_VECTOR_OR_REPLAY'))
    health_fields=['status','capability_scope','trade_date','model_contract_id','parameter_digest','slot_status','source_quality','publication_status','temporal_leakage_status','duplicate_episode_status','state_integrity_status','P0_violations','settlement_backlog']
    capabilities=['STOCK_CORE','STOCK_SECTOR_DEPENDENT','SECTOR_STAGE','ROTATION','SECTOR_RISK_CHANGE']
    put('v4_16_shadow_health_contract_v1',capabilities=capabilities,receipt_key=['model_contract_id','state_lineage_id','trade_date','capability_scope'],fields=health_fields,propagation='FAILED_SHARED_DEPENDENCY_ONLY_ITS_REGISTERED_CONSUMERS; DO_NOT_OVERWRITE_INDEPENDENT_VALID_CAPABILITY',stability=dict(required_real_consecutive_sessions=20,same_model_required=True,temporal_leakage_max=0,duplicate_episode_corruption_max=0,core_identity_P0_violations_max=0,rollback_drill_required=True,missed_or_unevaluable_session='BREAK_CONSECUTIVE_STREAK; NEVER_COUNT_OR_SKIP',P0_or_model_parameter_change='RESET_AFFECTED_WINDOW_AND_SHARED_DEPENDENCY_CONSUMERS',replay_vector_backfill_counts=False,receipts=['all_scheduled_market_slots','on_time_acceptance_count','consecutive_market_sessions','window_start','reset_reason','rollback_receipt','dependency_digest']),stock_provisional=dict(unique_signal_dates=5,unique_stock_positive_events=30,horizon=5,quality='OBSERVED_ONLY',positive_events=['FIRST_PREWATCH','REENTRY_PREWATCH','NEW_CONFIRMED'],counts=['unique_signal_dates','unique_stock_positive_events','T5_OBSERVED_count','controls_quality','benchmark_quality'],revision_counts_twice=False,INVALIDATION_counts_positive=False,settlement_P0_allowed=False),sector_rotation_provisional=dict(per_event_type=['SECTOR_FIRST_PREWATCH','SECTOR_NEW_WARM','SECTOR_NEW_CONFIRMED','ROTATION_PULSE','ROTATION_ACCEPTED','ROTATION_FAILED'],counters=['unique_episode_count','unique_signal_dates','matured_events','T5_path_quality','state_outcome_quality'],minimum_numeric_values=None,minimum_authority=inputs['parameters'],failed_counts_as_positive=False,pulse_substitutes_accepted=False,insufficient_policy='SHADOW_ONLY_FOR_SCOPE',sector_risk_gate='SEPARATE_EVENT_COMPLETENESS_AND_SECTOR_PATH_VALIDATION'),real_accumulation_blocks_unrelated_engineering=False)
    put('v4_16_realtime_shadow_contract_v1',evidence_origin_enum=['PIT_OBSERVED','RECONSTRUCTED_ASOF','RECONSTRUCTED_CORRECTED','DIAGNOSTIC_NON_PIT'],execution_mode_enum=['PRODUCTION','SHADOW','REPLAY'],future_original_observation=dict(evidence_origin='PIT_OBSERVED',execution_mode='SHADOW',namespace='SHADOW_V4',requires='EXACT_ACCEPTED_CLOCK_SLOT_SOURCE_VISIBILITY_AND_AUTHORIZED_FUTURE_RUNTIME'),reconstruction_upgrade=False,cohort=dict(authority=inputs['cohort'],population='ALL_FINAL_ELIGIBLE_ACCEPTED_OWNER_EVENTS',enrollment_key=['logical_event_id','cohort_namespace'],ignore_selection=['Focus','homepage_display_cap','manual_pin','UI_filter','ranking_visibility'],stock_warm='NOT_APPLICABLE_NO_ACCEPTED_OWNER',original_rule='FIRST_REALTIME_ASSERTED_IN_FIRST_COMPLIANT_SLOT_ONLY',revision_action='APPEND_CORRECTED_OR_RETRACTED_OBSERVATION; SOURCE_CORRECTION',preserve=['T0','enrollment_id','control_assignment_ids','benchmark_ids','FIRST_OBSERVED'],latest_validated='APPEND_PROJECTION_ONLY',corrected_cohort='SEPARATE_CORRECTED_RECONSTRUCTION_NAMESPACE'),membership=dict(daily_snapshots=['industry_membership_snapshot','concept_membership_snapshot','sector_type_snapshot'],append_only=True,observed_requires='ACTUAL_RUNTIME_CAPTURE_VISIBLE_BY_FROZEN_CUTOFF_IN_AUTHORIZED_SHADOW_SLOT',future_basis='PIT_OBSERVED',historical_backfill_basis='EXISTING_RECONSTRUCTED_OR_DIAGNOSTIC; NEVER_PIT_OBSERVED',key=['model_contract_id','state_lineage_id','trade_date','snapshot_type','source_revision_digest']),optional_BaoStock=dict(role='SUPPLEMENTAL_ONLY',failure_blocks_pure_core=False,enrichment_mutates_core=False,strict_binding_promoted=False),FEP_feedback=False,capability_blocks={k:read(HEAD,root)['entries'][k] for k in ['A04_H21_CONSUMER','A04_HISTORICAL_AMOUNT_A','A08_CURRENT_RUNTIME']},model_boundary='NEW_ID_LINEAGE_AND_COHORT; OLD_EPISODES_PENDING_OUTCOMES_KEEP_SETTLING',forbidden_feedback_edges=['Focus -> enrollment','UI Top-K -> enrollment','Forward outcome -> T0 state','FEP prediction -> Core/Radar','Corrected outcome -> T0','future source -> same-day decision'],runtime_start_gate='FUTURE_INDEPENDENT_EXTERNAL_CONTRACT_AUDIT_AND_EXPLICIT_RUNTIME_TASK; R22_FREEZE_DOES_NOT_AUTHORIZE_SHADOW')
    # Hand-authored design expectations, never executed as real observations.
    scenarios=[
      ('ON_TIME_FIRST_SLOT',{'authorized_future_runtime':True,'accepted_clock_fixture':True,'exact_previous_shadow_session':True,'source_visible_by_cutoff':True,'accepted_before_deadline':True},{'classification':'PIT_OBSERVED','original_enrollments':1,'namespace':'SHADOW_V4'}),
      ('LATE_BACKFILL',{'accepted_before_deadline':False},{'slot':'MISSED_OBSERVATION_SLOT','classification':'RECONSTRUCTED_ASOF','original_enrollments':0}),
      ('SAME_DAY_R2',{'revision':2},{'append_observation':True,'new_original_enrollments':0,'preserve_T0':True}),
      ('LEGACY_PRIOR',{'prior_namespace':'PRODUCTION_LEGACY'},{'reject':'NAMESPACE_PRIOR_MISMATCH'}),
      ('MISSING_PREVIOUS_SHADOW_SESSION',{'previous_market_session_accepted':False},{'status':'GAP_FAIL_CLOSED','skip_day_yesterday':False}),
      ('MODEL_PARAMETER_CHANGE',{'parameter_digest_changed':True},{'new_lineage':True,'reset_affected_window':True,'old_observations_immutable':True}),
      ('HISTORICAL_REPLAY',{'mode':'REPLAY','origin':'RECONSTRUCTED_ASOF'},{'real_shadow_session_increment':0,'original_realtime_enrollments':0}),
      ('FOCUS_UI_EXCLUSION',{'visible':False},{'eligible_enrollment_unchanged':True,'settlement_continues':True}),
      ('PRE_DUE_ENDPOINT',{'market_session_due':False},{'reject':'FUTURE_SOURCE_READ_BEFORE_DUE','future_read_count':0}),
      ('DUE_SOURCE_UNAVAILABLE',{'market_session_due':True,'endpoint_accepted':False},{'status':'PENDING_DUE_SOURCE_UNAVAILABLE','return_value':None,'explicit_reason':True}),
      ('SETTLEMENT_RERUN',{'same_evaluation_source_digest':True},{'new_result_revisions':0,'idempotent':True}),
      ('CORRECTED_EVALUATION_SOURCE',{'evaluation_source_digest_changed':True},{'append_result_revision':True,'first_observed_unchanged':True}),
      ('CURRENT_MEMBERSHIP_BACKFILL',{'membership':'CURRENT_MEMBERSHIP_BACKFILL'},{'PIT_OBSERVED':False,'diagnostic_or_reconstructed':True}),
      ('BAOSTOCK_UNAVAILABLE',{'optional_BaoStock_available':False},{'pure_core_continues':True,'enrichment':'UNKNOWN'}),
      ('CAPABILITY_ISOLATION',{'capability_A_blocked':True,'capability_B_independent':True},{'A':'BLOCKED_AFFECTED_SCOPE','B':'INDEPENDENTLY_TESTABLE'}),
      ('P0_STATE_VIOLATION',{'P0':True},{'affected_window_reset':True,'stable_pass':False}),
      ('MISSED_MARKET_SESSION',{'on_time_accepted':False},{'consecutive_streak':0,'real_session_increment':0}),
      ('LEGACY_PRODUCTION_ISOLATION',{'shadow_contract_processing':True},{'legacy_writes':0,'legacy_focus_changed':False,'legacy_default_UI_changed':False}),
      ('SOURCE_CORRECTION_AFTER_ENROLLMENT',{'source_correction':True},{'T0_unchanged':True,'controls_unchanged':True,'benchmark_unchanged':True,'append_only':True}),
      ('DUPLICATE_LOGICAL_EPISODE',{'duplicate_episode_corruption':True},{'status':'P0_FAIL','stable_pass':False}),
      ('UNSET_CLOCK_AUTHORITY',{'accepted_clock_authority':None},{'status':'BLOCKED_AFFECTED_SCOPE','PIT_OBSERVED':False,'original_realtime_enrollments':0}),
      ('GOVERNANCE_CAPABILITY_DEBT',{'issue':'A08_CURRENT_RUNTIME'},{'contract_entry_blocked':False,'affected_PREWATCH_shadow_active':False}),
      ('ENGINEERING_MATURITY_VECTOR',{'evidence':'ENGINEERING_VECTOR_ONLY'},{'real_maturity_increment':0,'historical_PIT_granted':False})]
    put('v4_16_machine_vectors_v1',evidence_class='ENGINEERING_DESIGN_EXPECTATIONS_ONLY_NOT_REAL_OBSERVATIONS',future_runtime_helpers_used=False,expected_authorship='INDEPENDENT_HAND_AUTHORED_PRE_RUNTIME',conditional_clock_vectors='ON_TIME_FIRST_SLOT IS CONDITIONAL ON A FUTURE ACCEPTED_CLOCK; CURRENT_REAL_SLOT_REMAINS_BLOCKED',vectors=[dict(vector_id='R22-MV-%02d'%(i+1),scenario=s,inputs=x,expected=y,actual_runtime_executed=False) for i,(s,x,y) in enumerate(scenarios)])
    fields={f:dict(field_id=f,owner_contract='V4_16_OBSERVATION_SLOT_CONTRACT_V1',data_type='UTC_RFC3339_TIMESTAMP' if f.endswith('_at') or f=='observation_deadline' else 'FROZEN_IDENTITY_OR_ENUM',UNKNOWN='BLOCK_AFFECTED_SCOPE; NEVER_SYNTHESIZE',time_basis='FROZEN_SLOT') for f in slot_fields}
    for f in health_fields:
        fields.setdefault(f,dict(field_id=f,owner_contract='V4_16_SHADOW_HEALTH_CONTRACT_V1',data_type='CAPABILITY_SCOPED_RECEIPT',UNKNOWN='NOT_A_STABILITY_PASS',time_basis='ACTUAL_MARKET_SESSION_RECEIPT'))
    atomic('config/v4_16_field_registry_v1.json',dict(contract_id='V4_16_FIELD_REGISTRY_V1',version='1.0.0',fields=fields,contract_design_only=True),root)
    package=dict(contract_id='V4_16_CONTRACT_PACKAGE_V1',version='1.0.0',execution_baseline=BASE,status='PASS_READY_FOR_EXTERNAL_AUDIT',contracts=contracts,field_registry=ref('config/v4_16_field_registry_v1.json',root),entry_authority=inputs,phase0_gate=ref('reports/pre16_finalization/FINALIZATION_GATE.json',root),current_audit_config=inputs['audit_config'],current_audit_head=inputs['audit_head'],slot_capability='BLOCKED_AFFECTED_SCOPE_PENDING_ACCEPTED_CLOCK',dag=['FROZEN_ACCEPTED_AUTHORITY -> OBSERVATION_SLOT -> SOURCE_FREEZE -> ACCEPTED_SHADOW_PUBLICATION -> COMPLETE_COHORT -> DURABLE_DUE_OUTBOX -> ACCEPTED_FUTURE_SOURCE -> OUTCOME_REVISION -> READBACK'],non_edges=['PRODUCTION_LEGACY_PRIOR -> SHADOW_V4_PRIOR','Focus -> enrollment','UI Top-K -> enrollment','Forward outcome -> T0 state','FEP prediction -> Core/Radar','Corrected outcome -> T0','future source -> same-day decision'],source_capability_matrix=dict(clock='BLOCKED_AFFECTED_SCOPE',stock_warm='NOT_APPLICABLE_NO_ACCEPTED_OWNER',Amount_A_H21='BLOCKED_FORMAL_CONSUMER',historical_Amount_A='UNAVAILABLE_FORMAL_CONSUMER',A08_current_PREWATCH='OPEN_EXTERNAL_REAUDIT_NOT_ACTIVE_IN_SHADOW',BaoStock='OPTIONAL_SUPPLEMENTAL_ONLY',membership='FUTURE_OBSERVED_CAPTURE_ONLY; HISTORICAL_NOT_PIT',real_maturity='NOT_GRANTED',marked_benchmark='BLOCKED_UNSET_ACCEPTED_NUMERIC_GATES'),storage_design=dict(apply_permission=False,records=['observation_slots','source_freeze_manifests','accepted_publications','complete_daily_ledgers','logical_event_observations','first_observed_enrollments','daily_membership_snapshots','due_outbox','outcome_revisions','capability_health_receipts'],append_only=True,transaction='PUBLICATION_MANIFEST_COHORT_OUTBOX_ACCEPTED_HEAD_CAS_ATOMIC',foreign_keys='EXACT_PUBLICATION_MODEL_LINEAGE_SOURCE_DIGEST_REFERENCES',migration='DESIGN_ONLY_NO_FORMAL_DB_APPLY'),production=False,shadow=False,focus=False,V4_16=False,runtime_implemented=False,runtime_authorized=False,REAL_SHADOW_OBSERVATIONS=0,NEXT='STOP_WAIT_R22_INDEPENDENT_EXTERNAL_AUDIT')
    atomic('config/v4_16_contract_package_v1.json',package,root)
    print('R22 contract freeze written; current observation-clock capability is explicitly blocked')
if __name__=='__main__':build()
