"""R22R1 contract writer; no observation/publication/runtime execution."""
from copy import deepcopy
from scripts.r22r1_io import *
DESCRIPTION='GOV_PRE16_01 and GOV_PRE16_02 are externally closed and no longer block contract/runtime entry. This authority grants no runtime permission. A04/A08 capability-only limitations remain unchanged; future runtime requires independent external authorization.'
def build(root=ROOT):
    accepted=dict(contract_id='V4_16_CONTRACT_ACCEPTED_HEAD_R1',version='1.0.0',acceptance_scope='CONTRACT_FREEZE_ONLY',audited_remote_head=BASE,tested_source='2456f6cdae99431bb475f077d4eaccd5f24c3b75',tested_tag='refs/tags/codex/r22-contract-tested-source-20261004-r1',external_decision='PASS_FINAL_V4_16_CONTRACT_FREEZE_CAPABILITY_SCOPED',external_authority=ref(AUDIT,root),package=ref('config/v4_16_contract_package_v1.json',root),candidate_seal=ref('reports/r22/V4_16_CONTRACT_CANDIDATE_SEAL.json',root),runtime_authorized=False,production=False,shadow=False,focus=False,V4_16=False)
    atomic(ACCEPT,accepted,root)
    clock=dict(contract_id='V4_16_CLOCK_CONTRACT_V1',version='1.0.0',policy_origin='POST_REV4_V4_16_EXTERNAL_GOVERNANCE_POLICY',historical_v4_00c_claim=False,execution_baseline=BASE,status='CLOCK_BOUND_CANDIDATE_PENDING_EXTERNAL_AUDIT',external_policy=ref(AUDIT,root),task=ref('docs/evidence/r22r1/V4_16_R22R1_CLOCK_AUTHORITY_AND_GOVERNANCE_NORMALIZATION_TASK_20261004.md',root),timezone='Asia/Shanghai',timestamp_storage='UTC_RFC3339',scheduled_source_cutoff_local='21:00:00',observation_publication_deadline_local='22:30:00',scheduled_source_cutoff_utc='13:00:00Z',observation_publication_deadline_utc='14:30:00Z',market_session_only=True,calendar_authority=read('data/v4/V4_15_ACCEPTED_HEAD.json',root)['bindings']['calendar'],values_are='EX_ANTE_POLICY_NOT_HISTORICAL_AVAILABILITY',source_provider_available_at='EARLIEST_PROJECT_OBSERVED_AUTHORITATIVE_READINESS_FOR_EXACT_CONSUMED_MANDATORY_SOURCE',remote_receipt='FIRST_ACCEPTED_PROVIDER_READINESS_OBSERVATION_RECEIPT',local_receipt='ACCEPTED_LOCAL_OBSERVATION_ACQUISITION_RECEIPT',system_available_at='EXACT_BYTES_LOCALLY_AVAILABLE_AND_REQUIRED_ACCEPTANCE_INTEGRITY_PASSED',visibility_order=['source_provider_available_at <= system_available_at <= scheduled_cutoff_at < observation_deadline','system_available_at <= computation_started_at <= computation_finished_at <= accepted_at <= observation_deadline'],publication_before_cutoff_allowed=True,backdating_allowed=False,missing_late_mandatory='MISSED_OBSERVATION_SLOT; PIT_OBSERVED=false; RECONSTRUCTED_ASOF_OR_CORRECTED_ONLY',optional_baostock='SUPPLEMENTAL_ONLY; CANNOT_MOVE_CORE_CLOCK_OR_INVALIDATE_PURE_CORE',revision_rule=dict(new_version_required=True,new_policy_identity_required=True,reset_affected_shadow_stability_window=True,rewrite_old_slots=False),runtime_authorized=False,real_shadow_observations=0,production=False,shadow=False,focus=False,V4_16=False)
    atomic(CLOCK,clock,root)
    slot=deepcopy(read('config/v4_16_observation_slot_contract_v1.json',root))
    slot.update(contract_id='V4_16_OBSERVATION_SLOT_CONTRACT_V2',version='2.0.0',execution_baseline=BASE,status='CLOCK_BOUND_CANDIDATE',predecessor=ref('config/v4_16_observation_slot_contract_v1.json',root),clock_authority=dict(status='CLOCK_BOUND_CANDIDATE',contract=ref(CLOCK,root),timezone='Asia/Shanghai',timestamp_storage='UTC_RFC3339',scheduled_source_cutoff_local='21:00:00',observation_publication_deadline_local='22:30:00'),activation_gate='R22R1_INDEPENDENT_EXTERNAL_AUDIT_AND_SEPARATE_RUNTIME_AUTHORIZATION_REQUIRED',slot_states=['ACCEPTED_ON_TIME','MISSED_OBSERVATION_SLOT'],no_clock_rule='MISSING_OR_UNACCEPTED_CLOCK_BLOCKS_REALTIME_ENROLLMENT_NO_PIT_CLAIM')
    atomic(SLOT,slot,root)
    h=deepcopy(read('data/v4/V4_CROSS_STAGE_CURRENT_AUDIT_HEAD_V2.json',root))
    h.update(contract_id='V4_CROSS_STAGE_CURRENT_AUDIT_HEAD_V3',version='3.0.0',descriptive_normalization_predecessor=ref('data/v4/V4_CROSS_STAGE_CURRENT_AUDIT_HEAD_V2.json',root),normalization_status='V3_NORMALIZED_CANDIDATE',NEXT='STOP_WAIT_R22R1_INDEPENDENT_EXTERNAL_AUDIT')
    h['blocking_schema']['runtime_activation_dependency']=DESCRIPTION
    h['entries']['GOV_PRE16_01']['scope']=DESCRIPTION
    h['entries']['GOV_PRE16_01']['limitations']=['Externally closed governance does not block V4-16 contract/runtime entry','No runtime permission; capability limitations and evidence bindings unchanged']
    atomic(HEAD,h,root)
    c=deepcopy(read('config/v4_cross_stage_current_audit_authority_v2.json',root))
    c.update(contract_id='V4_CROSS_STAGE_CURRENT_AUDIT_AUTHORITY_V3',version='3.0.0',current_head=ref(HEAD,root),descriptive_normalization_predecessor=ref('config/v4_cross_stage_current_audit_authority_v2.json',root),normalization_status='V3_NORMALIZED_CANDIDATE',historical_predecessor_semantics='V1/V2 are immutable historical authorities; V3 is descriptive normalization candidate only; no permission transition')
    c['blocking_schema']['runtime_activation_dependency']=DESCRIPTION
    atomic(CONFIG,c,root)
if __name__=='__main__':build()
