"""External clock acceptance; separate disabled runtime activation authority."""
from scripts.r23_io import *
def build():
    paths=['config/v4_16_clock_contract_v1.json','config/v4_16_observation_slot_contract_v2.json','data/v4/V4_CROSS_STAGE_CURRENT_AUDIT_HEAD_V3.json','config/v4_cross_stage_current_audit_authority_v3.json','data/v4/V4_16_CONTRACT_ACCEPTED_HEAD_R1.json','data/v4/V4_15_ACCEPTED_HEAD.json','data/v4/V4_DATA_ACCEPTED_HEAD.json','data/v4/V4_STAGE_ACCEPTED_HEAD.json']
    accepted=dict(contract_id='V4_16_CLOCK_GOVERNANCE_ACCEPTED_HEAD_R1',audited_remote_head=BASE,tested_source='319d598ef372ac52829083567e41188a15c053a3',immutable_tested_tag='refs/tags/codex/r22r1-clock-tested-source-20261004-r1',external_decision='PASS_FINAL_CLOCK_AUTHORITY_AND_GOVERNANCE_NORMALIZATION',scope='CLOCK_VISIBILITY_SLOT_CONTRACT_AND_DESCRIPTIVE_GOVERNANCE_ONLY',external_authority=ref(AUDIT),bindings=[ref(p) for p in paths],runtime_engineering_entry=True,runtime_authorized=False,real_shadow_authorized=False,closed_finding='R22_CLOCK_AUTHORITY_REPAIR_01',production=False,shadow=False,focus=False,V4_16=False)
    atomic(ACCEPT,accepted)
    activation=dict(contract_id='V4_16_RUNTIME_ACTIVATION_AUTHORITY_V1',version='1.0.0',status='ENGINEERING_CANDIDATE_DISABLED',external_clock_acceptance=ref(ACCEPT),runtime_authorized=False,real_shadow_authorized=False,allowed_modes=['CONTRACT_TEST','ENGINEERING_FIXTURE','DRY_RUN_NO_ACCEPT'],real_shadow_entry='FAIL_BEFORE_SOURCE_READ_OR_DATABASE_OPEN',future_activation_requires='NEW_VERSIONED_EXTERNALLY_ACCEPTED_AUTHORITY; ENVIRONMENT_FLAGS_NEVER_GRANT_PERMISSION',real_shadow_observations=0,PIT_OBSERVED_REAL_SAMPLES=0,production=False,shadow=False,focus=False,V4_16=False)
    atomic(AUTH,activation)
    owners=read('config/v4_current_stage_authority_v2.json')['immutable_owner_heads']
    modules=['v4_12_structure_engine','v4_13_profile_runtime','v4_14_full_dag','v4_14_precall_runtime','v4_15_radar_cohort','v4_15_settlement']
    # Names are resolved explicitly below, never by glob/version/mtime discovery.
    module_paths=['src/workbench_analysis/'+n+'.py' for n in modules]
    module_paths+=['src/v4/stock_prewatch.py','src/v4/confirmation.py','src/v4/confirmation_events.py','src/workbench_analysis/v4_current_stage_authority.py','src/workbench_analysis/v4_14_replay_io.py','src/workbench_analysis/v4_portable_exact.py']
    deps=dict(contract_id='V4_16_RUNTIME_DEPENDENCIES_V1',version='1.0.0',execution_baseline=BASE,bindings=[ref(p) for p in paths]+[ref(AUTH),ref(ACCEPT),ref('config/v4_current_stage_authority_v2.json'),ref('config/v4_16_settlement_worker_contract_v1.json'),ref('config/v4_16_shadow_health_contract_v1.json'),ref('config/v4_16_shadow_namespace_contract_v1.json'),ref('migrations/v4_16_r23_shadow_v1.sql')]+[ref(p) for p in module_paths],owner_heads={k:v for k,v in owners.items() if k in ['v4_10','v4_11','v4_12','v4_13','v4_14']},blocked_capabilities=['A04_H21_CONSUMER','A04_HISTORICAL_AMOUNT_A','A08_CURRENT_RUNTIME'],current_audit_head=ref('data/v4/V4_CROSS_STAGE_CURRENT_AUDIT_HEAD_V3.json'),clock=ref('config/v4_16_clock_contract_v1.json'),slot=ref('config/v4_16_observation_slot_contract_v2.json'),activation=ref(AUTH),accepted_data=ref('data/v4/V4_DATA_ACCEPTED_HEAD.json'),migration=ref('migrations/v4_16_r23_shadow_v1.sql'),fixture_registry=ref('config/v4_16_r23_engineering_fixtures_v1.json'),accepted_producer_scope='EXACT_V4_10_TO_14_OWNER_FIXTURE_OUTPUTS; V4_15_RADAR_COHORT_AND_SETTLEMENT_EXECUTABLE_ADAPTERS; NO_BUSINESS_REIMPLEMENTATION',runtime_authorized=False)
    deps['bindings'].append(ref('data/v4/V4_EXACT_BYTE_PORTABILITY_REGISTRY_R1.json'))
    atomic(DEPS,deps)
if __name__=='__main__':build()
