"""Static R1.1 repair oracle, with adversarial values never generated by reducer."""
from copy import deepcopy
import json
from pathlib import Path
from src.v4.state_identity import digest,state_id
from scripts.v4_10_r1_1_fixtures import (adapt_r1_input,synthetic_input,accepted_bundle,accepted_prior_fixture,
    boundary_descriptor,refresh,envelope,policy,calendar,full_prior)
ROOT=Path(__file__).resolve().parents[1]

def build_vectors():
    old=json.loads((ROOT/'config/v4_10_machine_vectors_v1.json').read_text(encoding='utf8'))['vectors']
    rows=[]
    for v in old:
        v=deepcopy(v);v['input']=adapt_r1_input(v['input']);v['kind']='API';v['coverage'].append('existing_reducer_semantics')
        rows.append(v)
    def add(name,x,tag,error=None,expected=None,setup=None):
        rows.append(dict(id=name,kind='API',input=x,expected=expected or {},expected_error=error,coverage=[tag],ledger_setup=setup))
    prior,prior_manifests=accepted_prior_fixture()
    base,manifests=accepted_bundle(prior=prior)
    setup=dict(manifests=prior_manifests+manifests,prior=prior)
    def altered_prior(field=None,value=None,remove=False):
        x=deepcopy(base)
        if remove:x['prior_state'].pop(field)
        elif field:x['prior_state'][field]=value
        x['prior_state']['publication_id']=state_id(x['prior_state'])
        x['prior_state_binding'].update(publication_id=x['prior_state']['publication_id'],payload_digest=digest(x['prior_state']))
        return x
    add('partial_prior_payload_rejected_in_accepted_mode',altered_prior('matched_predicates',remove=True),'prior_full_schema_authenticity','PRIOR_FULL_SCHEMA_REQUIRED',setup=setup)
    add('self_consistent_fake_prior_digest_rejected',altered_prior('transition_reasons',['CALLER_FORGED_PRIOR']),'prior_full_schema_authenticity','PRIOR_NOT_IN_TRUSTED_ENGINEERING_PUBLICATION',setup=setup)
    x=deepcopy(base);x['prior_state']['publication_id']='V4_10:'+'a'*64;x['prior_state_binding'].update(publication_id=x['prior_state']['publication_id'],payload_digest=digest(x['prior_state']))
    add('prior_content_address_publication_id_mismatch_rejected',x,'prior_content_address_identity','PRIOR_CONTENT_ADDRESS_IDENTITY_MISMATCH',setup=setup)
    add('prior_missing_calendar_publication_rejected',altered_prior('calendar_publication_id',remove=True),'prior_full_schema_authenticity','PRIOR_FULL_SCHEMA_REQUIRED',setup=setup)
    # Calendar negatives use fully authentic published prior and mutate current binding/mapping.
    x=deepcopy(base);x['calendar_binding']['lineage_id']='wrong'
    add('prior_calendar_identity_mismatch_rejected',x,'calendar_lineage_binding','CALENDAR_IDENTITY_MISMATCH',setup=setup)
    x=deepcopy(base);x['trade_date']='2026-09-29'
    add('prior_trade_date_session_index_inconsistent_rejected',x,'calendar_lineage_binding','TRADE_DATE_SESSION_INDEX_INCONSISTENT',setup=setup)
    x,ms=accepted_bundle(19,prior)
    add('same_day_revision_exact_session_binding_pass',x,'calendar_lineage_binding',expected=dict(state_freshness='STALE',final_eligibility='UNKNOWN'),setup=dict(manifests=prior_manifests+ms,prior=prior))
    add('prior_session_transition_bound_calendar_pass',deepcopy(base),'prior_content_address_identity',expected=dict(final_eligibility='UNKNOWN',maturity='NONE'),setup=setup)
    x=altered_prior('mode','SYNTHETIC_CONTRACT_VECTOR')
    add('synthetic_prior_cannot_enter_accepted_mode',x,'prior_full_schema_authenticity','SYNTHETIC_PRIOR_IN_ACCEPTED_MODE',setup=setup)
    x=deepcopy(base);x['prior_state_binding']['ledger_id']='caller-ledger'
    add('wrong_prior_ledger_identity_rejected',x,'prior_full_schema_authenticity','PRIOR_NOT_IN_TRUSTED_ENGINEERING_PUBLICATION',setup=setup)
    x=synthetic_input();x['model_boundary']=True
    add('bare_true_model_boundary_rejected',x,'model_boundary_authorization','MODEL_BOUNDARY_UNAUTHORIZED')
    b,m=boundary_descriptor(prior,base['trade_date'],False)
    boundary=deepcopy(base);boundary['model_boundary']=b
    bsetup=dict(manifests=prior_manifests+manifests+[m],prior=prior)
    add('authorized_boundary_pass',deepcopy(boundary),'model_boundary_authorization',expected=dict(parent_episode_id=None),setup=bsetup)
    x=deepcopy(boundary);x['model_boundary'].pop('migration_manifest_id')
    add('boundary_missing_manifest_rejected',x,'model_boundary_authorization','MODEL_BOUNDARY_MANIFEST_REQUIRED',setup=bsetup)
    for field,value in [('from_model_contract_id','WRONG_FROM'),('to_model_contract_id','WRONG_TO'),('effective_trade_date','2026-09-29')]:
        x=deepcopy(boundary);x['model_boundary'][field]=value
        add('boundary_wrong_'+field+'_rejected',x,'model_boundary_authorization','MODEL_BOUNDARY_UNAUTHORIZED',setup=bsetup)
    x=deepcopy(boundary);x['model_boundary']['migration_manifest_sha256']='0'*64
    add('boundary_manifest_digest_mismatch_rejected',x,'model_boundary_authorization','BOUNDARY_MANIFEST_DIGEST_MISMATCH',setup=bsetup)
    x=deepcopy(boundary);x['model_boundary']['publication_id']='V4_10_INPUT:absent'
    add('boundary_unpublished_manifest_rejected',x,'model_boundary_authorization','INPUT_PUBLICATION_NOT_IN_TRUSTED_LEDGER',setup=bsetup)
    for field,value in [('core_price_damage','TRUE'),('risk','EXTREME'),('delta3',99),('suspended','TRUE')]:
        x=deepcopy(base);f=x['input_provenance'][field];f['value']=value;f['source_field_payload']['value']=value;f['source_output_digest']=digest(f['source_field_payload'])
        add('unbound_'+field+'_cannot_change_state',refresh(x),'hard_invalidation_provenance' if field=='core_price_damage' else 'state_input_field_provenance',
            'FIELD_NOT_IN_TRUSTED_PUBLICATION',setup=setup)
    x=deepcopy(base);x['input_provenance']['core_price_damage']['producer_contract_id']='WRONG_PRODUCER'
    add('wrong_core_price_damage_producer_rejected',refresh(x),'hard_invalidation_provenance','FIELD_PRODUCER_LINEAGE_MISMATCH',setup=setup)
    for field in ['frozen_invalidation','episode_invalidation_contract_id','followup_complete','scenario']:
        x=deepcopy(base);d=policy()['fields'][field]
        value='TRUE' if field in ('frozen_invalidation','followup_complete') else 'UNACCEPTED_EPISODE_CONTRACT' if field=='episode_invalidation_contract_id' else 'LAUNCH_CONFIRM'
        dates={s['session_index']:s['trade_date'] for s in calendar(False)['sessions']}
        f=envelope(field,value,'IMPLEMENTED',d,20,dates);f['publication_id']=x['input_publication_ids'][0]
        x['input_provenance'][field]=f
        add(field+'_true_before_owner_producer_rejected',refresh(x),'followup_owner_gate' if field=='followup_complete' else 'hard_invalidation_provenance' if field=='frozen_invalidation' else 'state_input_field_provenance',
            'OWNER_PRODUCER_NOT_IMPLEMENTED',setup=setup)
    for suffix in ['wrong_publication','contract_matches_but_unbound']:
        x=deepcopy(base);f=x['input_provenance']['frozen_invalidation'];f.update(value='TRUE',quality='KNOWN',status='IMPLEMENTED',publication_id='UNBOUND_INVALIDATION')
        f['source_field_payload']=dict(field='frozen_invalidation',value='TRUE',session_index=19,trade_date='2026-09-25',episode_id='old',invalidation_contract_id='MATCHING_FROZEN_CONTRACT')
        f['source_output_digest']=digest(f['source_field_payload'])
        add('invalidation_'+suffix+'_rejected',refresh(x),'hard_invalidation_provenance','OWNER_PRODUCER_NOT_IMPLEMENTED',setup=setup)
    x=deepcopy(base);x['input_provenance']['frozen_invalidation']['value']='FALSE'
    add('not_implemented_fact_never_coerced_false',refresh(x),'hard_invalidation_provenance','NOT_IMPLEMENTED_FACT_MUST_REMAIN_UNKNOWN',setup=setup)
    # Sector metric provenance rejection in explicit synthetic mode still requires exact membership.
    x=synthetic_input('SECTOR');x['input_provenance']['dq5']['publication_id']='SYNTHETIC_FACTS:UNBOUND'
    add('unbound_dq5_cannot_move_sector_health_or_expiry',refresh(x),'state_input_field_provenance','FIELD_PUBLICATION_EXACT_MEMBERSHIP_REQUIRED')
    x=deepcopy(base);f=x['input_provenance']['risk'];f['producer_parameter_set_id']='wrong'
    add('wrong_risk_parameter_rejected',refresh(x),'state_input_field_provenance','FIELD_PRODUCER_LINEAGE_MISMATCH',setup=setup)
    x=deepcopy(base);f=x['input_provenance']['delta3'];f['time_role']='T-1'
    add('wrong_delta3_time_role_rejected',refresh(x),'state_input_field_provenance','FIELD_PROVENANCE_POLICY_MISMATCH',setup=setup)
    x=deepcopy(base);x['input_provenance']['risk']['system_available_at']='2026-09-29T01:00:00Z'
    add('future_available_fact_rejected',refresh(x),'state_input_field_provenance','FIELD_NOT_IN_TRUSTED_PUBLICATION',setup=setup)
    x,ms=accepted_bundle();m=ms[1]
    for f in m['fields'].values():f['system_available_at']='2026-09-29T01:00:00Z'
    pub='V4_10_INPUT:'+digest(m)
    for f in x['input_provenance'].values():
        if f['status']=='IMPLEMENTED':f.update(publication_id=pub,system_available_at='2026-09-29T01:00:00Z')
    x['input_publication_ids']=[pub]
    add('published_future_timestamp_still_unavailable_at_T',refresh(x),'state_input_field_provenance','FIELD_TIME_AVAILABILITY_MISMATCH',setup=dict(manifests=ms,prior=None))
    x,ms=accepted_bundle();x['entity_type']='SECTOR';ms[1]['entity_type']='SECTOR'
    pub='V4_10_INPUT:'+digest(ms[1])
    for f in x['input_provenance'].values():
        if f['status']=='IMPLEMENTED':f['publication_id']=pub
    x['input_publication_ids']=[pub]
    add('registered_stock_producer_relabelled_sector_rejected',refresh(x),'state_input_field_provenance','FIELD_PRODUCER_ENTITY_SCOPE_MISMATCH',setup=dict(manifests=ms,prior=None))
    for name,ids in [('string','prefix-PUB-suffix'),('empty',[]),('empty_id',['']),('duplicate',['PUB','PUB']),('nested',[['PUB']]),('nonstr',[1])]:
        x=synthetic_input();x['input_publication_ids']=ids
        add('input_publication_ids_'+name+'_rejected',x,'input_publication_manifest_shape','INPUT_PUBLICATION_MANIFEST_SHAPE_INVALID')
    x=deepcopy(base);x['input_provenance']['core_price_damage']['publication_id']=x['input_publication_ids'][0][10:25]
    add('exact_publication_membership_no_substring_match',refresh(x),'input_publication_manifest_shape','FIELD_PRODUCER_LINEAGE_MISMATCH',setup=setup)
    x=synthetic_input();x['input_publication_manifest_digest']='wrong'
    add('input_manifest_digest_wrong_rejected',x,'input_publication_manifest_shape','INPUT_PUBLICATION_MANIFEST_DIGEST_MISMATCH')
    for name in ['direct_sql_forged_payload_digest','direct_sql_forged_state_publication_id','direct_sql_producer_lineage_mismatch','direct_sql_calendar_binding_mismatch']:
        rows.append(dict(id=name,kind='SQL',coverage=['db_payload_identity_guard'],expected_rejected=True))
    return rows
