"""Build-time verbatim extraction from pinned accepted historical domain statements."""
import ast
import hashlib
import json
import sys
import textwrap
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from scripts.build_v4_08_r2_membership_evidence import atomic_bytes,atomic_json

def segment(path,start,end):
    data=(ROOT/path).read_bytes();s=data.decode('utf8')
    a=s.index(start); b=s.index(end,a)
    lines=s[:a].count('\n')+1
    block=textwrap.dedent(s[a:b])
    return block,dict(path=path,sha256=hashlib.sha256(data).hexdigest(),start_line=lines,
                      end_line=s[:b].count('\n'),extracted_statements_sha256=hashlib.sha256(block.encode()).hexdigest())

def extract():
    status,rs=segment('scripts/build_v4_02_dated_trading_status.py',
        '                if row.get("source_bar_present") is True:\n', '                encoded = json.dumps(output_row')
    # The first matching block is in the output loop, rather than the earlier input inventory.
    st,ri=segment('scripts/build_v4_02_full_market_isst.py','                            value = {\n',
                  '                            encoded = json.dumps(value')
    period,rp=segment('scripts/build_v4_02_formal_periods.py','                        agg = period_aggs[kind].setdefault(',
                      '\n            if not day_rows:')
    price,rpl=segment('scripts/build_v4_02_price_limits.py','            if status == "SUSPENDED":\n',
                     '            _write(target, output_digest, result)\n            row_count += 1\n            counts')
    # Price contains a CLI early-write/continue in the listing branch. Translate only I/O control into return.
    a=price.index('        _write(target, output_digest, result)')
    b=price.index('        continue',a)+len('        continue')
    price=price[:a]+'        return result'+price[b:]
    source='''"""Frozen extracted domain kernels. Generated by extract_dm01_domain_r1; no CLI calls."""\nfrom collections import Counter\nfrom decimal import Decimal\nimport hashlib\nimport json\nfrom scripts.build_v4_02_price_limits import board_rule_key\n\ndef classify_dated_status(row, facts):\n    code = row['source_security_key'].lower()\n    date = row['trade_date']\n    missing_classification = Counter()\n    is_st_counts = Counter()\n    is_st_security_coverage = set()\n    actual_provider_status_conflicts = 0\n    actual_provider_status_conflict_rows = []\n'''
    source+=textwrap.indent(status,'    ')+'    return output_row, actual_provider_status_conflict_rows\n\n'
    source+='def dated_isst_fact(member, day, provider_row, binding_revision):\n'
    source+=textwrap.indent(st,'    ')+'    return value\n\n'
    source+='def accumulate_period_bar(period_aggs, kind, pkey, basis, d, prices, volume, amount):\n'
    source+=textwrap.indent(period,'    ')+'    return agg\n\n'
    source+='''def evaluate_price_base(result, status, row, is_st, state, reference, events, service,\n                        delist_dates_by_id, ambiguous_listing_date, first_listing_session_by_id, session_index):\n    security_id = result['security_id']\n    board = result['board_scope']\n    day = result['trade_date'].replace('-', '')\n    samples = {}\n    boundary_days = set()\n'''
    source+=textwrap.indent(price,'    ')+'    return result\n'
    ast.parse(source)
    output='src/workbench_analysis/dm01_extracted_domain_r1.py'
    atomic_bytes(ROOT/output,source.encode('utf8'))
    atomic_json(ROOT/'config/dm01_domain_extraction_r1.json',dict(contract_id='DM01_DOMAIN_EXTRACTION_R1',
        status='EXACT_SOURCE_STATEMENTS_EXTRACTED_IO_CONTROL_ONLY_TRANSFORMED',sources=[rs,ri,rp,rpl],
        output=dict(path=output,sha256=hashlib.sha256(source.encode()).hexdigest()),
        transformations=['dedent into pure callable','supply original locals as parameters',
                         'listing branch CLI write/count/continue becomes return result'],
        original_historical_files_modified=False,domain_formulas_changed=False))

if __name__=='__main__': extract()
