"""Field-local scope matrix, PIT inventory and honest open engineering ledger."""
from immediate_r3_common import *
from audit_immediate_r3_amount_owner import csvwrite
from collections import Counter
def main():
    h=load('data/v4/V4_OPERATIONAL_RESEARCH_HEAD.json');day=h['accepted_trade_date'];alg=load(OUT/'02_P0_ALG/P0_ALG_ORACLE_RESULT.json');amount=load(OUT/'04_P0_AMOUNT/P0_AMOUNT_ORACLE_RESULT.json');old=load('docs/evidence/core_algo_ui_r2_20261010/REMAINING_WORK_LEDGER.json');snap=load(h['membership_snapshot'])
    exceptions=[r for r in amount['rows'] if r['classification']=='INSUFFICIENT_EVIDENCE'];samples=[]
    for verdict in amount['counts']:
        candidates=[r for r in amount['rows'] if r['classification']==verdict];samples.extend(sorted(candidates,key=lambda r:abs(r['delta'] or 0),reverse=True)[:3])
    for r in exceptions[:10]:
        if r not in samples:samples.append(r)
    csvwrite(OUT/'04_P0_AMOUNT/P0_AMOUNT_EXCEPTION_SAMPLES.csv',samples)
    datecounts={d:dict(Counter(r['classification'] for r in amount['rows'] if r['trade_date']==d)) for d in sorted({r['trade_date'] for r in amount['rows']})}
    write(OUT/'04_P0_AMOUNT/P0_AMOUNT_AUDIT_STATUS.json',dict(issue_id='M10/DD-A05/R3',status='AMOUNT_A_OPEN_PRECISE_BLOCKER',compared=amount['compared'],different=amount['different'],classification_counts=amount['counts'],by_date=datecounts,remaining_unclassified=len(exceptions),next_action='Acquire provider calculation/rounding evidence for exact non-binary32 differences; preserve formal primary Native',sector_Amount_A='Separate accepted PIT h21 observation ledger; latest membership cannot satisfy historical PIT',authority_changed=False))
    markdown(OUT/'02_P0_ALG/P0_ALG_TRANSITION_CASES.md',f'# Transition evidence R3\n\n{len(alg["transition_traces"])} dated real rows over five sessions; holiday gap uses bound session indexes. Full traces are in result JSON. Required unknown retains prior state, hard invalidation precedes same-day confirmation, health and expiry remain distinct axes.\n\nNamed FIXTURE_ONLY cases: same-day invalidation/confirmation conflict; same-session reentry forbidden; same facts with/without prior state; unavailable frozen denominator. These are engineered counterexamples, not observed market events. REAL_REENTRY_NOT_OBSERVED.\n\nRotation producer on 10/09 uses a target-coordinate rebuilt 10/08 prior in the same candidate tree. Published 10/08 files use a different coordinate identity. The exact rebuilt prior hash and episode are now exported; old published price coordinates must never be mixed silently. This is corrected replay lineage, not historical as-recorded recurrence.\n')
    markdown(OUT/'02_P0_ALG/P0_ALG_FIX_REPORT.md',f'# Independent incremental algorithm audit\n\n{alg["checks"]} comparisons, {alg["errors"]} differences; counts {json.dumps(alg["counts"])}. 45 selected IDs, 223 D0 and 223 D2 rows, seven large/small industry/concept sectors, 1,600 current LOO pairs. Scope: listed raw D0 equations and classifier gates, D2 business axes/counters, native median/breadth, existing basket/pulse/retention and current non-target median relative values.\n\nNO_CHANGE_REQUIRED_WITH_EVIDENCE for checked business formulas. Initial apparent differences were oracle input errors: OBSERVED quality must be retained; ret1 requires only previous close; target-coordinate reconstructed prior differs from published prior.\n\nOPEN: ATR/structural upstream input proof, first pulse baseline upstream proof, complete LOO cross-section ranks/recursive episodes, historical first availability and real reentry. Small-package zero differences is not a whole-market proof.\n')
    producers=['src/workbench_analysis/v4_15_radar_cohort.py','src/workbench_analysis/v4_15_forward_r2.py','src/workbench_analysis/v4_15_settlement_successor.py','src/workbench_analysis/validation_cohort_read_contract_r3.py']
    fields=['signal_event_at_T0','cohort_enrollment_id','frozen_signal_version','eligible_at_T0','asof_first_available','benchmark','no_lookahead','path_observation','maturity_schedule','T1/T3/T5_result','right_censor_reason','settlement_owner','FEP_model_version','permission_gate','BFF_route']
    write(OUT/'05_P1_COHORT/P1_COHORT_CAPABILITY_INVENTORY.json',dict(T0=day,fields=[dict(field=f,status='PRODUCER_EXISTS_OWNER_MISSING' if f not in ('FEP_model_version','permission_gate','asof_first_available') else 'MODEL_OR_PERMISSION_NOT_READY' if f in ('FEP_model_version','permission_gate') else 'NO_ASOF_ENROLLMENT',producer=producers,accepted_current_owner=None,route='/api/v4/forward',responsible_layer='AUTHORITY' if f=='permission_gate' else 'INPUT_MISSING / OWNER_BUILD') for f in fields],existing_focus_path_owner=h['owners'][day]['forward'],focus_is_cohort=False,producers=[binding(p) for p in producers],production_enabled=False))
    markdown(OUT/'05_P1_COHORT/P1_FEP_NOT_READY_CONTRACT.md','# FEP R3 capability boundary\n\nREV4 §90 governs frozen T0 features, prior active model, separately available labels, namespace and per-capability grants. Current operational head supplies no legal independent cohort/model Owner. CAPABILITY_NOT_READY. No training, probability prediction, Priority replacement, Focus write or production grant is introduced.\n\nThe new pure read contract validates aware first availability, immutable event identity, distinct episode events, cutoff, deduplication and official-session maturity. It does not backfill historical enrollment. Existing Forward R2 price/affine/suspension/delisting/settlement producers exist and were regression-tested as declared fixtures.\n')
    inventory=[]
    for d in h['published_sessions']:
        for family,ref in h['owners'][d].items():
            inventory.append(dict(trade_date=d,family=family,owner=ref,source_capture=h['source_registry'][d],scope='LATEST_RECONSTRUCTED' if family in ('sector','rotation','relative_sector','seed') else 'CORRECTED',AS_RECORDED=False,first_available_at='NOT_PROVEN_FOR_HISTORICAL_T0',membership_observed_at=snap['membership_observed_at'],membership_basis='TDX_LATEST_MEMBER_RETRO_V1',PIT_verdict='HISTORICAL_PIT_NOT_VERIFIABLE',survivorship_bias_risk=True))
    write(OUT/'07_PIT_INVENTORY/PIT_EVIDENCE_INVENTORY.json',dict(status='COMPLETE_SCOPED',items=inventory,strict_head=binding('data/v4/V4_DATA_ACCEPTED_HEAD.json'),strict_scope='Existing separately accepted head only; no permission expansion',missing_dates='No additional actual sessions invented'))
    markdown(OUT/'07_PIT_INVENTORY/PIT_GAPS_FOR_FUTURE_COLLECTION.md','# Historical PIT gaps\n\nThe five current research dates have corrected/latest-member Owners and hash-bound captures. 10/09 member capture cannot prove 9/28 members. Source ingestion timestamps are not historical first availability. Future collection must preserve original first capture, source payload, member/identity versions, effective date and actual grant. It cannot rewrite old first-availability facts. Strict Head remains separate and unchanged.\n')
    issues=[dict(issue_id='AUDIT-CORE-R2-01/R3-UPSTREAM',status='OPEN_CURRENT_ENGINEERING',scope='Full D0 classifier/ATR/structure predicates; full LOO rank and prior baskets',evidence='02_P0_ALG/P0_ALG_FIX_REPORT.md',wait_real_day=False,next_action='Export remaining exact prior inputs and independently reproduce missing predicate families'),dict(issue_id='PRODUCT-R2-02/R3-SECTOR-D2',status='SOURCE_NOT_PRESENT',scope='Sector maturity/health dated publication',evidence='03_P0_OWNER/P0_OWNER_GAP_ROOT_CAUSE.csv',wait_real_day=False,next_action='Version sector real interface admission and required detector manifest; isolated candidate only'),dict(issue_id='PRODUCT-R2-02/R3-MEMBER27',status='NOT_VERIFIABLE',scope='27 unbound source IDs',evidence='03_P0_OWNER/P0_OWNER_MEMBER_27_DISPOSITION.csv',wait_real_day=False,next_action='Obtain official dated identity bytes for each ID'),dict(issue_id='M10/DD-A05/R3',status='OPEN_PRECISE_BLOCKER',scope='Unexplained cross-source amount differences and sector authority',evidence='04_P0_AMOUNT/P0_AMOUNT_AUDIT_STATUS.json',wait_real_day=False,next_action='Provider calculation/representation evidence for residuals; no primary switch'),dict(issue_id='FORWARD-R2-04/R3',status='NO_ASOF_ENROLLMENT_CAPABILITY_NOT_READY',scope='Current independent cohort and FEP model/grant',evidence='05_P1_COHORT/P1_COHORT_CAPABILITY_INVENTORY.json',wait_real_day=False,next_action='Read only a legally frozen enrollment/model publication after independent authority gate'),dict(issue_id='DAILY-R2-03',status='WAIT_REAL_DAY',scope='10/12 actual successor',evidence='R2 original ledger',wait_real_day=True,next_action='Use existing DD R2.2 after actual source readiness'),dict(issue_id='EXTERNAL-R2-05/R3',status='EXTERNAL_RECHECK_REQUESTED',scope='Independent review and strict PIT/full FP13/14',evidence='00_EXECUTION_RESULT_R3.md',wait_real_day=False,next_action='Independent reviewer signs scoped verdict; Codex cannot sign')]
    write(OUT/'08_REMAINING_LEDGER.json',dict(inherited_R2=old,appended_R3=issues,overall='ENGINEERING_SCOPE_OPEN_NOT_COMPLETE',external_acceptance='NOT_GRANTED'))
    axes=['FORMULA_OR_LOGIC','CURRENT_DATA','API_BINDING','UI_BEHAVIOR','HISTORICAL_PIT','FUTURE_OUTCOME'];rows=[]
    for feature in ('D0','D2','Rotation','LOO','sector.maturity','sector.health','member27','AmountA','Cohort','FEP','UI.six_entries'):
        rows.append(dict(feature=feature,trade_date=day,verdicts=dict(zip(axes,['PASS_SCOPED' if feature in ('D0','D2','Rotation','LOO') else 'SEE_FIELD_EVIDENCE','HASH_BOUND' if feature not in ('sector.maturity','sector.health','Cohort','FEP') else 'SOURCE_NOT_PRESENT','SEE_API_AUDIT','SEE_BROWSER_RECORDS','NOT_VERIFIABLE_LATEST_RECONSTRUCTED','WAIT_REAL_DAY_OR_VALIDATION_ONGOING'])),code_sha=git('rev-parse','HEAD'),owner_sha=sha('data/v4/V4_OPERATIONAL_RESEARCH_HEAD.json'),external='NOT_GRANTED'))
    write(OUT/'01_SCOPE_AND_AUTHORITY_MATRIX.json',dict(axes=axes,rows=rows,authority='CURRENT_SNAPSHOT_WORK_ONLY'))
    print(json.dumps(dict(amount_by_date=datecounts,PIT_items=len(inventory),remaining_items=len(issues))))
if __name__=='__main__':main()
