"""Freeze Replay Gate B specifications and literal vectors, never execute replay."""
from pathlib import Path
import json
from scripts.prepare_r17_governance import ROOT,put,bind,atomic
P='config/v4_14_'
UPGRADE='docs/evidence/A_SHARE_RESEARCH_SYSTEM_V4_2_2_FINAL_EXECUTABLE_CONTRACT_REV4_FEP_R2_20260930.md'
DIMENSIONS=['same_day_feedback','state_transition_legality','hysteresis','expiry','direct_prewatch_confirmed','rotation_pulse_accepted_failed','support_reclaim_retest_break','confirmation_persistent_suppression','multi_sector_dedup','unknown_propagation','no_duplicate_event_episode','same_day_revision_predecessor','cross_process_previous_session','future_publication_leakage','revision_append_only','deterministic_replay','historical_pit_evidence']
BOOKS=['config/v4_10_machine_vectors_r1_2.json','config/v4_12_machine_vectors_v1.json','config/v4_12_time_counter_vectors_r2_1.json','config/v4_08_rotation_machine_vectors_v2.json','config/v4_13_machine_vectors_v1_1.json']
OWNER_CONTRACTS=['config/v4_10_research_state_contract_r1_2.json','config/v4_10_machine_ast_r1_2.json','config/v4_10_parameter_set_r1_2.json','config/v4_11_entry_contracts_r1.json','config/v4_11_confirmation_machine_ast_v1.json','config/v4_11_confirmation_parameter_set_v1.json','config/v4_12_structure_event_contract_v1.json','config/v4_12_machine_ast_v1.json','config/v4_12_parameter_set_v1.json','config/v4_08_rotation_core_contract_r5.json','config/v4_13_dag_edge_registry_v1_1.json','config/v4_13_projection_v1_2.json']
FILES=['replay_gate_b_contract_v1','replay_case_registry_v1','temporal_non_edge_registry_v1','quality_degradation_v1','machine_vectors_v1']
def literal_pairs():
    # These expectations are authored from frozen owner contracts, not computed
    # by the future V4-14 runtime. Negative cases carry an explicit wrong claim.
    return {
      'same_day_feedback':(dict(edges=[['F0','A','T'],['D0','D2','T']],raw_before='TRUE'),dict(raw_after='TRUE'),dict(edges=[['D3','A','T']]),'SAME_DAY_FEEDBACK_FORBIDDEN'),
      'state_transition_legality':(dict(entity_type='STOCK',prior_maturity='PREWATCH',confirmed='TRUE',trusted_source=True),dict(maturity='CONFIRMED',episode='E1'),dict(entity_type='STOCK',claimed_maturity='WARM'),'ILLEGAL_STOCK_WARM'),
      'hysteresis':(dict(prior_maturity='PREWATCH',raw_maturity='NONE',adjacent_evaluable_sessions=1,required_known=True),dict(maturity='PREWATCH',downgrade_count=1),dict(claimed_maturity='NONE',adjacent_evaluable_sessions=1),'PREMATURE_DOWNGRADE'),
      'expiry':(dict(prior_maturity='PREWATCH',expiry_count_before=9,evaluable=True,improvement_pp=0),dict(maturity='NONE',tracking='FOLLOWUP',expiry_count=10),dict(evaluable=False,claimed_expiry_count=10),'UNKNOWN_OR_SUSPENSION_CANNOT_ADVANCE_EXPIRY'),
      'direct_prewatch_confirmed':(dict(prior_maturity='PREWATCH',confirmed='TRUE',hard_damage='FALSE',required_known=True),dict(maturity='CONFIRMED',mandatory_wait_sessions=0),dict(claimed_wait_sessions=1),'FORCED_UPGRADE_WAIT_FORBIDDEN'),
      'rotation_pulse_accepted_failed':(dict(accepted_predicate_oracle='R1B',expired_branch=dict(prior_state='ROTATION_PULSE',episode_exists=True,pulse_age_sessions=6,accepted=False,required_known=True)),dict(accepted_branch='ROTATION_ACCEPTED',failed_branch='ROTATION_FAILED',branches_mutually_exclusive=True),dict(claimed_accepted_with_failed_breadth=True),'ROTATION_ACCEPTANCE_REQUIRES_FROZEN_OWNER_PREDICATES'),
      'support_reclaim_retest_break':(dict(anchor='A1',owner_trace_refs=['S05_no_separation','S01','S05_hold','S05_retest','S05_confirm','S03'],coordinate='EXACT_ACCEPTED_AFFINE_BASIS'),dict(trace=['TESTING','RECLAIMED','HELD_TENTATIVE','RETESTING','HELD_CONFIRMED','BROKEN'],anchor='A1'),dict(claimed_retest_without_separation=True),'RETEST_REQUIRES_FROZEN_SEPARATION_RULE'),
      'confirmation_persistent_suppression':(dict(prior_session_confirmed=True,current_confirmed=True,scenario_changed=False,weakened=False),dict(event_class='PERSISTENT_CONFIRMED',new_actionable_event=False,new_episode=False),dict(claimed_new_event=True),'UNCHANGED_PERSISTENT_CANNOT_CREATE_NEW_ACTIONABLE_EVENT'),
      'multi_sector_dedup':(dict(security='S1',sectors=['I1','C1','C2'],publication='PUB1'),dict(logical_security_event_count=1,sector_context_count=3),dict(claimed_security_event_count=3),'SECTOR_MEMBERSHIP_CANNOT_MULTIPLY_SECURITY_EVENTS'),
      'unknown_propagation':(dict(required_quality='UNKNOWN',prior_maturity='PREWATCH',prior_expiry_count=9,unaffected_relation_quality='KNOWN'),dict(final_eligibility='UNKNOWN',maturity='PREWATCH',expiry_count=9,unaffected_relation_quality='KNOWN'),dict(claimed_required_fact='FALSE'),'UNKNOWN_MUST_NOT_BECOME_FALSE'),
      'no_duplicate_event_episode':(dict(logical_event_key=['V4','MODEL1','S1','E1','NEW_CONFIRMED','2026-09-30'],runs=2),dict(logical_event_count=1,episode_count=1,episode_id='E1'),dict(claimed_episode_id_on_continuation='E2'),'CONTINUATION_CANNOT_CREATE_NEW_EPISODE'),
      'same_day_revision_predecessor':(dict(calendar=['2026-09-28','2026-09-29','2026-09-30'],target='2026-09-30',revisions=['r1','r2'],previous_dates=['2026-09-29','2026-09-29'],previous_manifest_digests=['a'*64,'a'*64]),dict(previous_dates=['2026-09-29','2026-09-29'],previous_manifest_digests=['a'*64,'a'*64],event_classes=['NEW_CONFIRMED','NEW_CONFIRMED']),dict(previous_dates=['2026-09-29','2026-09-30']),'SAME_DAY_REVISION_IS_NOT_PREVIOUS_SESSION'),
      'cross_process_previous_session':(dict(producer_pid=101,consumer_pid=102,producer_exited=True,persisted_manifest_digest='b'*64,readback_manifest_digest='b'*64,previous_date='2026-09-29',target='2026-09-30'),dict(readback='EXACT_PERSISTED_PREVIOUS_SESSION',memory_prior_used=False),dict(producer_pid=101,consumer_pid=101),'IN_MEMORY_CONTINUITY_DOES_NOT_PROVE_CROSS_PROCESS_REPLAY'),
      'future_publication_leakage':(dict(target='2026-09-30',max_source_trade_date='2026-09-30',source_asof='2026-09-30T15:00:00+08:00',available_at='2026-09-30T15:30:00+08:00',cutoff='2026-09-30T16:00:00+08:00'),dict(temporal_admission='ALLOW'),dict(available_at='2026-10-01T00:00:00+08:00'),'FUTURE_AVAILABILITY_FORBIDDEN_AT_T0'),
      'revision_append_only':(dict(old_revision='r1',new_revision='r2',old_sha_before='c'*64,old_sha_after='c'*64),dict(old_revision_immutable=True,new_revision_separate=True),dict(old_sha_after='d'*64),'OLD_REVISION_OVERWRITE_FORBIDDEN'),
      'deterministic_replay':(dict(frozen_input_digest='e'*64,run1_output_digest='f'*64,run2_output_digest='f'*64),dict(output_digest_equal=True,duplicate_side_effects=0),dict(run2_output_digest='1'*64),'FROZEN_REPLAY_DIGEST_MISMATCH'),
      'historical_pit_evidence':(dict(claimed_evidence_class='ENGINEERING_SYNTHETIC',historical_source_missing=True,current_membership_backfill=True),dict(evidence_class='ENGINEERING_SYNTHETIC',historical_effectiveness='NOT_VERIFIABLE',affected_quality='DEGRADED'),dict(claimed_evidence_class='HISTORICAL_PIT_EFFECTIVENESS'),'CURRENT_MEMBERSHIP_IS_NOT_HISTORICAL_PIT')}
def freeze():
    b=json.loads((ROOT/'reports/r17b/completion_gate.json').read_bytes());assert b['R17B_V4_13_ACCEPTED_HEAD_PROMOTION']=='PASS'
    assert b['independent_gate']['status']=='PASS' and b['test_totals']['failed']==0 and b['test_totals']['deselected']==0
    assert bind(UPGRADE)['sha256']=='203ff46075b4039d1e2d45d54fd76ce09509535739cd6aaef4dc394de1015205'
    text=(ROOT/UPGRADE).read_text(encoding='utf8')
    sections={}
    for n in [53,54,78,80,81]:
        start=text.index('# '+str(n)+'.');end=text.index('# '+str(n+1)+'.',start);part=text[start:end]
        import hashlib
        sections[str(n)]=dict(authority=bind(UPGRADE),section='# '+str(n),normalized_excerpt_sha256=hashlib.sha256(part.encode()).hexdigest(),read=True)
    protected={p:bind(p) for p in ['AGENTS.md','data/v4/V4_STAGE_ACCEPTED_HEAD.json','data/v4/V4_DATA_ACCEPTED_HEAD.json','data/v4/V4_12_ACCEPTED_HEAD.json','data/v4/V4_13_ACCEPTED_HEAD.json']}
    put('reports/r17c/stage_contract.json',dict(contract_id='R17C_V4_14_CONTRACT_FREEZE_ENTRY_V1',baseline='f12315bf8e3142aa44e9068c5895004c35c4e23c',entry_gate=bind('reports/r17b/completion_gate.json'),task=bind('docs/evidence/r17/V4_R17C_V4_14_REPLAY_GATE_B_CONTRACT_FREEZE_ENTRY_TASK_20261003.md'),master=bind('docs/evidence/r17/V4_NEXT_ROUND_EXECUTION_MASTER_R17_20261003.md'),sections_read=sections,protected=protected,scope='CONTRACT_FREEZE_ONLY',V4_14_RUNTIME='NOT_IMPLEMENTED',ALGORITHM_STATE_REPLAY_PASS='NOT_GRANTED',NEXT='STOP_WAIT_INDEPENDENT_EXTERNAL_AUDIT'))
    heads=['data/v4/V4_04_ACCEPTED_HEAD.json','data/v4/V4_05_ACCEPTED_HEAD.json','data/v4/V4_07_ACCEPTED_HEAD.json','data/v4/V4_08_ACCEPTED_HEAD_AMENDED_R1.json','data/v4/V4_08_PIT_MEMBERSHIP_ACCEPTED_HEAD_R1.json','data/v4/V4_09_ACCEPTED_HEAD.json','data/v4/V4_10_ACCEPTED_HEAD.json','data/v4/V4_11_ACCEPTED_HEAD.json','data/v4/V4_12_ACCEPTED_HEAD.json','data/v4/V4_13_ACCEPTED_HEAD.json','data/v4/V4_DATA_ACCEPTED_HEAD.json']
    sources=[bind(p) for p in [UPGRADE,*heads,*OWNER_CONTRACTS,*BOOKS]]
    def base(name):return dict(contract_id='V4_14_'+name.upper(),version='1.0.0',status='CONTRACT_FREEZE_ONLY',source_bindings=sources,time_role='FROZEN_TARGET_SESSION_AND_EXACT_PREVIOUS_ACCEPTED_MARKET_SESSION',required_history='OWNER_REQUIRED_WINDOWS_PLUS_EXACT_T_MINUS_1_PERSISTED_PUBLICATIONS; NO_SAME_DAY_PREDECESSOR',unknown_semantics='UNKNOWN_NEVER_FALSE; COMPONENT_SCOPED_DEGRADED_OR_NOT_VERIFIABLE',negative_cases=[d+'_negative' for d in DIMENSIONS],acceptance_criteria='COMPLETE_INDEPENDENT_FROZEN_CONTRACT_BEFORE_RUNTIME; EXTERNAL_AUDIT_STILL_REQUIRED',runtime_implemented=False,production=False,shadow=False,focus=False,global_mandatory_adoption=False,ALGORITHM_STATE_REPLAY_PASS='NOT_GRANTED')
    vectors=[]
    for d,(good,expected,bad,reason) in literal_pairs().items():
        for polarity,inp,exp in [('positive',good,dict(verdict='ADMIT_CONTRACT_CASE',required_behavior=expected)),('negative',dict(good,**bad),dict(verdict='REJECT_CONTRACT_VIOLATION',reason=reason))]:
            vectors.append(dict(id=d+'_'+polarity,dimension=d,polarity=polarity,evidence_class='ENGINEERING_SYNTHETIC',input=inp,expected=exp,expected_origin='HAND_AUTHORED_FROZEN_OWNER_SEMANTICS_NOT_FUTURE_RUNTIME'))
    extra=[('future_price',dict(max_source_trade_date='2026-10-01'),'MAX_SOURCE_TRADE_DATE_AFTER_TARGET'),('future_membership',dict(membership_effective_date='2026-10-01'),'FUTURE_MEMBERSHIP_FORBIDDEN'),('membership_available_late',dict(membership_effective_date='2026-09-29',membership_available_at='2026-10-01T00:00:00+08:00'),'MEMBERSHIP_AVAILABILITY_AFTER_CUTOFF'),('future_state',dict(prior_state_trade_date='2026-10-01'),'FUTURE_STATE_FORBIDDEN'),('future_focus_outcome',dict(source_namespace='FUTURE_FOCUS_OUTCOME'),'FOCUS_OUTCOME_IS_NOT_ALGORITHM_INPUT'),('weekly_friday_on_monday',dict(target='2026-09-28',source_asof='2026-10-02'),'WEEKLY_ASOF_LEAKAGE'),('month_end_on_midmonth',dict(target='2026-09-15',source_asof='2026-09-30'),'MONTHLY_ASOF_LEAKAGE'),('future_adjustment_revision',dict(knowledge_lineage='AS_RECORDED',adjustment_available_at='2026-10-01'),'AS_RECORDED_ADJUSTMENT_LEAKAGE'),('supplemental_after_core_cutoff',dict(provider_asof='2026-10-01',consumer='CORE'),'SUPPLEMENTAL_CANNOT_CHANGE_ACCEPTED_CORE')]
    positive_temporal={
        'future_price':dict(target='2026-09-30',max_source_trade_date='2026-09-30'),
        'future_membership':dict(target='2026-09-30',membership_effective_date='2026-09-29'),
        'membership_available_late':dict(target='2026-09-30',membership_effective_date='2026-09-29',membership_available_at='2026-09-30T15:00:00+08:00',cutoff='2026-09-30T16:00:00+08:00'),
        'future_state':dict(target='2026-09-30',prior_state_trade_date='2026-09-29'),
        'future_focus_outcome':dict(target='2026-09-30',source_namespace='ACCEPTED_OWNER_FACTS'),
        'weekly_friday_on_monday':dict(target='2026-09-28',source_asof='2026-09-28'),
        'month_end_on_midmonth':dict(target='2026-09-15',source_asof='2026-09-15'),
        'future_adjustment_revision':dict(target='2026-09-30',knowledge_lineage='AS_RECORDED',adjustment_available_at='2026-09-29',adjustment_revision_exact=True),
        'supplemental_after_core_cutoff':dict(target='2026-09-30',provider_asof='2026-09-30',consumer='SUPPLEMENTAL_ONLY',accepted_core_digest_unchanged=True)}
    for name,inp,reason in extra:
        vectors.append(dict(id=name+'_negative',dimension='future_publication_leakage',polarity='negative',evidence_class='ENGINEERING_SYNTHETIC',input=dict(target='2026-09-30',**inp) if 'target' not in inp else inp,expected=dict(verdict='REJECT_CONTRACT_VIOLATION',reason=reason),expected_origin='HAND_AUTHORED_BASELINE_SECTION_54'))
        vectors.append(dict(id=name+'_positive',dimension='future_publication_leakage',polarity='positive',evidence_class='ENGINEERING_SYNTHETIC',input=positive_temporal[name],expected=dict(verdict='ADMIT_CONTRACT_CASE',required_behavior=dict(temporal_admission='ALLOW_WITH_EXACT_OWNER_PROOFS')),expected_origin='HAND_AUTHORED_BASELINE_SECTION_54'))
    for name,dimension,inp,reason in [
        ('previous_calendar_day_is_not_market_session','same_day_revision_predecessor',dict(target='2026-09-28',calendar=['2026-09-24','2026-09-25','2026-09-28'],claimed_previous='2026-09-27'),'PREVIOUS_ACCEPTED_MARKET_SESSION_REQUIRED'),
        ('revision_previous_manifest_diverges','same_day_revision_predecessor',dict(target='2026-09-30',previous_manifest_digests=['a'*64,'b'*64]),'SAME_DAY_REVISIONS_MUST_SHARE_EXACT_PREVIOUS_MANIFEST'),
        ('readback_hash_mismatch','cross_process_previous_session',dict(persisted_manifest_digest='a'*64,readback_manifest_digest='b'*64),'EXACT_PERSISTED_READBACK_DIGEST_REQUIRED'),
        ('producer_did_not_exit','cross_process_previous_session',dict(producer_exited=False),'PRODUCER_EXIT_BEFORE_FRESH_PROCESS_REQUIRED'),
        ('consumer_started_before_exit','cross_process_previous_session',dict(producer_exit_at='2026-09-29T17:00:00+08:00',consumer_start_at='2026-09-29T16:59:00+08:00'),'CONSUMER_START_MUST_FOLLOW_PRODUCER_EXIT'),
        ('prior_readback_wrong_date','cross_process_previous_session',dict(target='2026-09-30',previous_market_session='2026-09-29',readback_date='2026-09-28'),'PREVIOUS_PUBLICATION_EXACT_DATE_REQUIRED'),
        ('real_capability_unknown_promoted_ready','unknown_propagation',dict(accepted_capability='UNKNOWN',claimed_capability='READY'),'REAL_CAPABILITY_DEGRADATION_MUST_BE_PRESERVED')]:
        vectors.append(dict(id=name+'_negative',dimension=dimension,polarity='negative',evidence_class='ENGINEERING_SYNTHETIC',input=inp,expected=dict(verdict='REJECT_CONTRACT_VIOLATION',reason=reason),expected_origin='HAND_AUTHORED_TEMPORAL_AND_CAPABILITY_CONTRACT'))
    vectors.append(dict(id='previous_market_session_weekend_positive',dimension='same_day_revision_predecessor',polarity='positive',evidence_class='ENGINEERING_SYNTHETIC',input=dict(target='2026-09-28',calendar=['2026-09-24','2026-09-25','2026-09-28'],revisions=['r1','r2']),expected=dict(verdict='ADMIT_CONTRACT_CASE',required_behavior=dict(previous_dates=['2026-09-25','2026-09-25'])),expected_origin='HAND_AUTHORED_ACCEPTED_MARKET_CALENDAR_RULE'))
    v=base('machine_vectors_v1');v.update(expected_generation='LITERAL_BEFORE_RUNTIME',vectors=vectors,owner_oracle_books=[bind(p) for p in BOOKS]);put(P+'machine_vectors_v1.json',v)
    cases=base('replay_case_registry_v1');cases.update(dimensions=DIMENSIONS,cases=[dict(case_id=d,positive=d+'_positive',negative=d+'_negative',vector_ids=[v['id'] for v in vectors if v['dimension']==d],acceptance_scope='CONTRACT_FROZEN_NOT_RUNTIME_PASS',owner_oracle_books=[bind(p) for p in BOOKS],failure_scope='AFFECTED_COMPONENT_ONLY') for d in DIMENSIONS],baseline_test_matrix=dict(data=['session_mismatch','publication_date_mismatch','stale_source','missing_membership','provider_budget_exhausted','turnover_soft_binding','partial_history'],a_share_rules=['ST','main_board_limit','growth_board_limit','suspension','resumption','new_listing','delisting','adjustment_identity_change'],prewatch=['weak_market_emergence','passive_defense','sector_absent_stock_seed','multi_sector','old_leader_deceleration','low_volatility_defensive_bias'],sector=['small_5_member','broad_80_member','one_stock_driven','overlapping_concepts','PIT_membership_change'],state=['threshold_epsilon','flapping','data_gap','hard_damage','expiry','direct_prewatch_confirmed','reentry','model_boundary'],forward=dict(scope='REFERENCE_ONLY_V4_15_NOT_AUTHORIZED',cases=['right_censor','complete_controls','all_eligible_denominator','hidden_display_still_settled','reconstructed_vs_real_forward'])));put(P+'replay_case_registry_v1.json',cases)
    dag=json.loads((ROOT/'config/v4_13_dag_edge_registry_v1_1.json').read_bytes());temporal=base('temporal_non_edge_registry_v1')
    required=[dict(producer='D2',consumer='D2',field='frozen_prior_state',time_role='T_MINUS_1',owner=bind('data/v4/V4_10_ACCEPTED_HEAD.json')),dict(producer='D0',consumer='EVENT_DIFF',field='confirmation_facts',time_role='T',owner=bind('data/v4/V4_11_ACCEPTED_HEAD.json')),dict(producer='D2',consumer='EVENT_DIFF',field='final_state',time_role='T',owner=bind('data/v4/V4_11_ACCEPTED_HEAD.json')),dict(producer='D2',consumer='EVENT_DIFF',field='frozen_prior_final_state',time_role='T_MINUS_1',owner=bind('data/v4/V4_11_ACCEPTED_HEAD.json')),dict(producer='D2',consumer='GATE_B_OBSERVATION',field='state_readback',time_role='T',owner=bind('data/v4/V4_10_ACCEPTED_HEAD.json')),dict(producer='D3',consumer='GATE_B_OBSERVATION',field='profile_context_readback',time_role='T',owner=bind('data/v4/V4_13_ACCEPTED_HEAD.json'))]
    forbidden=dag['forbidden_edges']+[[a,b,'T'] for a,b in [('D3','A'),('D3','B0'),('D3','B1'),('D3','B2'),('D3','C'),('D3','D0'),('D3','D1'),('D3','D2'),('D1','C'),('D2','A'),('D2','B0'),('D2','B1'),('D2','B2'),('D2','C'),('EVENT_DIFF','D0')]]+[['T_PLUS_1','T0','ANY'],['FUTURE_PUBLICATION','T0','ANY'],['FUTURE_MEMBERSHIP','T0','ANY'],['SAME_DAY_REVISION_PARENT','PREVIOUS_SESSION','ANY']]
    temporal.update(owner_dag=bind('config/v4_13_dag_edge_registry_v1_1.json'),owner_edges=dag['edges'],replay_required_edges=required,forbidden_edges=forbidden,aliases=dict(PROFILE='D3_READ_ONLY_PROFILE_PROJECTION',CONTEXT='D3_TARGET_EXCLUDED_CONTEXT_BRANCH',CORE_V4_04='F0_CORE',NATIVE_V4_05='F0_NATIVE',BASE_SEED_V4_07='A'),branch_semantics='D0_AND_D1_ARE_PARALLEL_FACT_BRANCHES_FEEDING_D2; D3_PROFILE_CONTEXT_IS_READ_ONLY; OBSERVATION_JOIN_IS_NOT_QUALIFICATION_FEEDBACK',cross_day=dict(required_sequence=['T_MINUS_1_PERSISTED_PUBLICATION','PRODUCER_PROCESS_EXIT','T_FRESH_PROCESS_START','EXACT_T_MINUS_1_READBACK','T_STATE_TRANSITION'],must_record=['producer_pid','consumer_pid','producer_exit_at','consumer_start_at','publication_path','publication_sha256','publication_bytes','publication_id','calendar_binding','previous_market_session','readback_sha256','output_digest'],same_day_revisions=dict(revisions=['r1','r2'],same_exact_previous_date=True,same_exact_previous_manifest=True,no_r1_to_r2_prior=True,new_stays_new=True),same_date_revision_selection='FROZEN_EXACT_PREVIOUS_SESSION_MANIFEST_AT_T_BUILD_ENTRY; NUMERIC_REVISION_ASOF_CUTOFF',memory_prior_is_proof=False,missing_previous_state='UNKNOWN_NOT_FABRICATED_NONE',wrong_hash_or_date='REJECT'),availability_predicate='max_source_trade_date<=target AND source_asof<=cutoff AND available_at<=cutoff AND membership_effective_at<=target AND membership_available_at<=cutoff');put(P+'temporal_non_edge_registry_v1.json',temporal)
    temporal['canonical_nodes']=dict(PROFILE='D3',CONTEXT='D3_CONTEXT',CORE_V4_04='F0',NATIVE_V4_05='F0',BASE_SEED_V4_07='A')
    temporal['cross_day']['previous_session_algorithm']='EXACT_ACCEPTED_MARKET_CALENDAR_POSITION_BEFORE_TARGET_WITH_FROZEN_ACCEPTED_PUBLICATION_REF; NOT_CIVIL_DAY_SUBTRACTION'
    put(P+'temporal_non_edge_registry_v1.json',temporal)
    quality=base('quality_degradation_v1');quality.update(evidence_classes=dict(ENGINEERING_SYNTHETIC=dict(proves=['topology','hysteresis','expiry','unknown','dedup','revision','cross_process_harness_contract'],cannot_claim=['real_signal_READY','historical_PIT_effectiveness','ALGORITHM_STATE_REPLAY_PASS']),REAL_ACCEPTED_SOURCE_CAPABILITY_SCOPED=dict(required=['exact_accepted_head','exact_publication','source_identity','target_date','available_at','cutoff','component_capability'],historical_effectiveness_implied=False),HISTORICAL_PIT_EFFECTIVENESS=dict(required=['price_PIT','universe_PIT','membership_PIT','source_identity','availability_cutoff','AS_RECORDED_adjustment_revision'],current_membership_backfill_allowed=False,all_prerequisites_must_be_proven=True)),failure_policy=dict(missing_source='UNKNOWN',missing_membership='UNKNOWN',missing_availability='NOT_VERIFIABLE',missing_history='DEGRADED',current_membership_historical_claim='REJECT_NOT_HISTORICAL_PIT',unknown_to_false=False,unaffected_components='REMAIN_INDEPENDENTLY_TESTABLE'),real_current_scope=dict(trade_date='2026-09-30',knowledge_lineage='RECONSTRUCTED_CORRECTED',AS_RECORDED=False,real_signal='DEGRADED_BY_ACCEPTED_UPSTREAM_CAPABILITY',historical_LOO='NOT_VERIFIABLE',legacy_B2='NOT_IMPLEMENTED',historical_pit_effectiveness='NOT_GRANTED'));put(P+'quality_degradation_v1.json',quality)
    gate=base('replay_gate_b_contract_v1');gate.update(baseline_sections=sections,entry=bind('reports/r17b/completion_gate.json'),contract_package=[bind(P+n+'.json') for n in FILES[1:]],required_dimensions=DIMENSIONS,field_registry=[dict(field=f,producer=p,time_role=t,source_binding=bind(s),quality='OWNER_EXACT_NO_COERCION') for f,p,t,s in [('max_source_trade_date','ALL_FACT_PROVIDERS','SOURCE_TRADE_DATE',UPGRADE),('source_asof','ALL_FACT_PROVIDERS','SOURCE_ASOF',UPGRADE),('available_at','ALL_FACT_PROVIDERS','KNOWLEDGE_TIME',UPGRADE),('calendar_binding','MARKET_CALENDAR','ACCEPTED_SESSION_LINEAGE','data/v4/V4_DATA_ACCEPTED_HEAD.json'),('seed_qualification','A','T_ONLY','data/v4/V4_07_ACCEPTED_HEAD.json'),('sector_qualification','B0_B2','T_ONLY','data/v4/V4_08_ACCEPTED_HEAD_AMENDED_R1.json'),('stock_prewatch_raw','C','T_ONLY','data/v4/V4_09_ACCEPTED_HEAD.json'),('confirmation','D0','T_BEFORE_D2','data/v4/V4_11_ACCEPTED_HEAD.json'),('structure','D1','T_AND_FROZEN_T_MINUS_1','data/v4/V4_12_ACCEPTED_HEAD.json'),('final_state','D2','T_FROM_FACTS_AND_FROZEN_PREVIOUS_SESSION','data/v4/V4_10_ACCEPTED_HEAD.json'),('state_event','EVENT_DIFF','AFTER_D2_T_COMPARE_PREVIOUS_SESSION','data/v4/V4_11_ACCEPTED_HEAD.json'),('profile_context','D3','T_READ_ONLY','data/v4/V4_13_ACCEPTED_HEAD.json'),('episode_id','D2','IMMUTABLE_LOGICAL_EPISODE','data/v4/V4_10_ACCEPTED_HEAD.json')]],identity_rules=dict(event_logical_key=['model_namespace','model_contract_id','parameter_set_id','entity_type','entity_id','episode_id','event_type','signal_market_date'],event_revision_key=['logical_event_id','observation_revision'],episode_continuation='SAME_ID_UNTIL_FORMAL_EXIT',new_episode='ONLY_FROZEN_OWNER_REENTRY_OR_AUTHORIZED_MODEL_BOUNDARY; LINK_PARENT_EPISODE',multi_sector='ONE_SECURITY_LOGICAL_EVENT_PER_PUBLICATION; CONTEXTS_REMAIN_DISTINCT',unchanged_persistent='DIAGNOSTIC_ONLY_NO_NEW_ACTIONABLE_EVENT_OR_EPISODE',old_revisions='APPEND_ONLY_BYTE_IMMUTABLE'),runtime_completion_requirements=['all_dimension_independent_oracles','full_temporal_DAG_and_non_edges','actual_cross_process_persisted_readback','exact_same_previous_session_for_r1_r2','append_only_idempotent_revisions','capability_scoped_real_source_readback','temporal_leakage_matrix','deterministic_digests','rollback_receipt','independent_external_audit'],runtime_authorization='NOT_GRANTED_THIS_ROUND',local_completion_claim='PASS_READY_FOR_EXTERNAL_AUDIT_ONLY',V4_14_ACCEPTED_HEAD='FORBIDDEN',NEXT='STOP_WAIT_INDEPENDENT_EXTERNAL_AUDIT');put(P+'replay_gate_b_contract_v1.json',gate)
    witnesses=base('owner_oracle_witnesses_v1');records=[]
    selections={
        BOOKS[0]:['stock_prior_warm_reject','downgrade_NONE_day1','downgrade_NONE_day2','break_UNKNOWN','break_SUSPENSION','downgrade_same_session_revision','expiry_9','expiry_10','expiry_improvement_2.99','expiry_improvement_3','expiry_pause_UNKNOWN','expiry_same_session_revision','upgrade_immediate','hard_core_price_damage','unknown_PREWATCH','reentry_session_20','reentry_session_21','same_day_revision_exact_session_binding_pass','prior_session_transition_bound_calendar_pass','wrong_prior_ledger_identity_rejected','published_future_timestamp_still_unavailable_at_T'],
        BOOKS[1]:['S05_no_separation','S01','S05_hold','S05_retest','S05_confirm','S03','S04_missing','B03_t1','B03_t2','D03'],
        BOOKS[3]:['R1A','R1B','R2','R3'],
        BOOKS[4]:['R15-01','R15-03','R15-10','R15-11','R15-12']}
    for path,names in selections.items():
        rows=json.loads((ROOT/path).read_bytes())['vectors']
        for name in names:
            idx=next(i for i,r in enumerate(rows) if r.get('id',r.get('vector_id'))==name)
            records.append(dict(source=bind(path),pointer='/vectors/'+str(idx),vector_id=name,independent_frozen_record=rows[idx]))
    witnesses.update(records=records,expectation_origin='PREEXISTING_INDEPENDENT_OWNER_BOOKS_EXACT_COPY_NO_RUNTIME_EVALUATOR',purpose='BOUND_FULL_INPUT_AND_EXPECTED_OUTPUT_WITNESSES_FOR_FUTURE_REPLAY_ORACLE')
    put('reports/r17c/owner_oracle_witnesses.json',witnesses)
    gate['owner_oracle_witnesses']=bind('reports/r17c/owner_oracle_witnesses.json')
    put(P+'replay_gate_b_contract_v1.json',gate)
    put('reports/r17c/contract_freeze_manifest.json',dict(contract_id='R17C_CONTRACT_FREEZE_MANIFEST_V1',contracts=[bind(P+n+'.json') for n in FILES],stage_contract=bind('reports/r17c/stage_contract.json'),vector_count=len(vectors),dimensions=len(DIMENSIONS),expected_origin='HAND_AUTHORED_PLUS_BOUND_PREEXISTING_INDEPENDENT_OWNER_ORACLES',V4_14_RUNTIME='NOT_IMPLEMENTED',ALGORITHM_STATE_REPLAY_PASS='NOT_GRANTED',NEXT='STOP_WAIT_INDEPENDENT_EXTERNAL_AUDIT'))
    print('R17C_CONTRACT_PACKAGE_FROZEN',len(vectors),'vectors')
if __name__=='__main__':freeze()
