"""Contract-only authoring; this file is not a V4-13 runtime producer."""
from scripts.v4_12_promotion_r14 import ROOT,ref,read,write,PERMISSIONS
from scripts.validate_v4_12_promotion_r14 import validate
P='config/v4_13_'
FIELDS=['primary_industry','supporting_concepts','algorithmic_support_sector','relative_sector_state','sector_context_state','sector_context_quality','rotation_structure_enrichment']
STRUCTURE=['active_anchor_id','anchor_view_asof_t','basic_breakout_state','basic_pullback_state','basic_recovery_state','support_state','acceptance_state','retest_count','structure_events','structure_health']
STRUCTURE_PATH={f:'active_projection.'+f for f in STRUCTURE}
STRUCTURE_PATH.update(active_anchor_id='active_selection.active_anchor_id',anchor_view_asof_t='selected_anchor_state.output_envelope.anchor_view_asof_t',basic_breakout_state='basic_breakout_state',structure_events='events',structure_health='selected_anchor_state.output_envelope.structure_health')
def contract(name,id,**values):write(P+name+'_v1.json',dict(contract_id=id,version='1.0.0',status='CONTRACT_FREEZE_ONLY',runtime_implemented=False,**values))
def run():
 assert validate(post=True)['status']=='PASS'
 stage=read('data/v4/V4_STAGE_ACCEPTED_HEAD.json');sector=stage['v4_08_binding']['path'];h=read(sector)
 owner=dict(V4_04=ref('data/v4/V4_04_ACCEPTED_HEAD.json'),V4_08=ref(sector),V4_12=ref('data/v4/V4_12_ACCEPTED_HEAD.json'))
 relative=ref('config/v4_04_algorithm_contracts_v3.json');parameters=ref(h['parameter_set']['path']);member=h['membership_binding']
 contract('parameter_set','V4_13_PARAMETER_SET_V1',parameters=[dict(parameter_id='profile_concept_display_cap',value=8,unit='display_items',status='ENGINEERING_CANDIDATE',algorithmic_effect=False)],inherited=parameters,threshold_claims='NO_PROFITABILITY_STATISTICAL_OPTIMALITY_OR_PRODUCTION_CLAIM')
 contract('loo_context','LOO_CONTEXT_V1',accepted_owner_bindings=owner,membership_authority=member,accepted_sector_dependencies={n:h[n] for n in ['native_contract','b0_contract','b2_contract','rotation_contract','field_registry','parameter_set']},
  identity_fields=['target_security_id','sector_id','trade_date','revision','membership_snapshot_id','membership_source_revision','cutoff','excluded_target_id','loo_history_digest'],
  membership=dict(validity='EXACT_TRADE_DATE_ACCEPTED_SNAPSHOT_NO_CARRY_FORWARD',identity='ACCEPTED_SOURCE_BYTES_AND_REVISION',historical_pit='ONLY_ACCEPTED_PROVIDER_AVAILABILITY_AND_EFFECTIVE_DATE_EVIDENCE',historical_current='CURRENT_MEMBERSHIP_REPLAY_DIAGNOSTIC_NOT_PIT',unknown='UNKNOWN_NOT_FALSE',types=['INDUSTRY','THEME']),
  recipe=['REMOVE_TARGET_FROM_EVERY_SECTOR_BEFORE_ALL_CALCULATIONS','REBUILD_NATIVE_RET_MEDIANS_BREADTH_MA_WIDTH_AMOUNT_CONCENTRATION','REBUILD_BASE_SEED_AGGREGATES_K_N_UNKNOWN_AND_WILSON_ORDERING','REBUILD_FULL_QUALIFIED_SECTOR_UNIVERSE_RANKS_AND_MEDIANS','REBUILD_B0_B2_RAW_WITH_EXACT_ACCEPTED_CONTRACT_AST','REBUILD_EVERY_REQUIRED_HISTORICAL_ENDPOINT_AND_COMMON_MEMBER_COHORT_WITH_TARGET_REMOVED','REBUILD_ROTATION_HISTORY_FROM_INDEPENDENT_LOO_LINEAGE_OR_MARK_UNAVAILABLE'],
  forbidden=['SUBTRACT_ONLY_COUNTS','RETAIN_SELF_INCLUDING_RANK_MEDIAN_STATE','USE_SELF_INCLUDING_HISTORICAL_STATE','RAW_RECONSTRUCTION_TO_BYPASS_OWNER_AUTHORITY'],
  denominator=dict(ret_sector='MEDIAN_OF_KNOWN_ELIGIBLE_NON_TARGET_MEMBER_RETURNS',rel_sector='STOCK_RETURN_MINUS_LOO_SECTOR_RETURN_PERCENTAGE_POINTS',coverage='KNOWN_QUOTED_NON_TARGET_MEMBERS / ELIGIBLE_NON_TARGET_MEMBERS',minimum_members='V4_08_SECTOR_MIN_MEMBERS',minimum_coverage='V4_08_SECTOR_MIN_QUOTE_COVERAGE',zero_members='NOT_APPLICABLE_IF_COMPLETE_KNOWN_MEMBERSHIP_ELSE_UNKNOWN',below_minimum='UNKNOWN_INSUFFICIENT_LOO_MEMBERS',incomplete='UNKNOWN_NO_ZERO_IMPUTATION'),
  relative_state=dict(contract_id='RELATIVE_STATE_V1',owner=relative,rule_pointer='/rules/RELATIVE_STATE_V1',field_substitution={'rel_market_1':'rel_sector_1','rel_market_5':'rel_sector_5'},other_fields='UNCHANGED_ACCEPTED_CORE_OWNER_FIELDS',priority_and_thresholds='EXACT_OWNER_AST_NO_SECOND_RULE_SET',required=['rps5','rps20','rps20_delta3','rel_sector_1','rel_sector_5','compression_state','ma_structure_state']),
  selection=dict(primary_industry='ACCEPTED_OFFICIAL_CLASSIFICATION_PRIORITY_ASC_TAXONOMY_DEPTH_DESC_SECTOR_ID_ASC; missing conflict metadata UNKNOWN; no membership NOT_APPLICABLE',primary_not_daily_strength=True,supporting_concepts='ALL_DATE_VALID_THEME_RELATIONS; complete underlying set; membership unknown remains UNKNOWN; stable membership_quality then sector_id ASC',display_cap='profile_concept_display_cap_ONLY_VIEW_NEVER_ALGORITHMIC_SET',algorithmic_support_sector_sort=['LOO_confirmed_raw_DESC','LOO_warm_raw_DESC','emergence_HIGH_MEDIUM_LOW_DESC','adjusted_seed_width_DESC','sector_id_ASC'],sector_type='INDUSTRY_OR_THEME_ONLY',eligible_quality='READY_ONLY_ALL_REQUIRED_LOO_AUTHORITY_AVAILABLE',rotation_and_relative_evidence='PRESERVED_EXPLANATORY_FIELDS_NOT_NEW_SORT_RULES',no_eligible='NOT_APPLICABLE_ONLY_COMPLETE_KNOWN_SET_ELSE_UNKNOWN'),
  publication=dict(namespace='CONTEXT_LOO',append_only=True,same_day_revision='ALL_USE_EXACT_T_MINUS_1_PREDECESSOR',membership_correction='NEW_REVISION_WITH_OLD_IMMUTABLE',availability='EVERY_SOURCE_AVAILABLE_AT_LE_CUTOFF',qualification_effect='NONE'),required_producer_capability='NOT_IMPLEMENTED_V4_13_RUNTIME; do not alias accepted self-including sector output as LOO')
 rows=[]
 for f in FIELDS+STRUCTURE:
  structure=f in STRUCTURE;producer='PROFILE_ADVANCED_PROJECTION_V1' if structure else 'LOO_CONTEXT_V1'
  source='V4_12_ACCEPTED_HEAD_V1' if structure else 'V4_08_ACCEPTED_MEMBERSHIP_AND_LOO_CONTEXT_V1'
  rows.append(dict(field=f,owner_stage='V4-13',producer_contract_id=producer,source_owner=source,source_field=f if structure else {'primary_industry':'date_valid_industry_relations','supporting_concepts':'date_valid_theme_relations','algorithmic_support_sector':'loo_candidate_set','relative_sector_state':'RELATIVE_STATE_V1_WITH_LOO_SUBSTITUTION','sector_context_state':'loo_raw_context_state','sector_context_quality':'loo_quality_and_membership_basis','rotation_structure_enrichment':'rotation_core_state_PLUS_READ_ONLY_D1'}[f],source_binding=owner['V4_12'] if structure else owner['V4_08'],time_role='T_READ_ONLY_ACCEPTED_D1' if structure else 'T_WITH_EXACT_T_MINUS_1_LOO_HISTORY',publication_namespace='ADVANCED_PROFILE_PROJECTION' if structure else 'CONTEXT_LOO',data_type='array' if f in ['supporting_concepts','structure_events'] else 'integer' if f=='retest_count' else 'object' if f in ['anchor_view_asof_t','rotation_structure_enrichment'] else 'enum_or_identity',unit='count' if f=='retest_count' else 'NOT_APPLICABLE_TYPED_VALUE',required=True,missing='UNKNOWN_NOT_FALSE',runtime_capability='NOT_IMPLEMENTED',blocked_reason='V4_13_RUNTIME_NOT_AUTHORIZED',raw_reconstruction=False))
 contract('field_registry','V4_13_FIELD_REGISTRY_V1',fields=rows)
 input_fields=[]
 for f,unit,source in [('membership_snapshot','date_valid_relation','V4_08'),('member_ret1','percent','V4_04'),('member_ret5','percent','V4_04'),('member_ret20','percent','V4_04'),('member_amount','CNY','V4_04'),('member_amount_ratio20','ratio','V4_04'),('member_close','price_basis_units','V4_04'),('member_ma20','price_basis_units','V4_04'),('member_base_seed_raw','boolean','V4_05'),('member_quality','quality_enum','V4_04'),('rps5','percentile_points','V4_04'),('rps20','percentile_points','V4_04'),('rps20_delta3','percentile_point_delta','V4_04'),('stock_ret1','percent','V4_04'),('stock_ret5','percent','V4_04'),('compression_state','enum','V4_04'),('ma_structure_state','enum','V4_04'),('loo_history','immutable_revision_lineage','V4_08')]:
  binding=owner[source] if source in owner else ref(stage['v4_05_binding']['path'])
  input_fields.append(dict(field=f,unit=unit,accepted_owner=source,owner_binding=binding,time_role='T_MINUS_K_EXACT_SOURCE' if f=='loo_history' else 'T_CUTOFF',required=True,missing='UNKNOWN_ACCEPTED_CAPABILITY_UNAVAILABLE',reconstruction=False))
 for row in rows:
  if row['field'] in STRUCTURE:row['source_field']=STRUCTURE_PATH[row['field']]
 contract('field_registry','V4_13_FIELD_REGISTRY_V1',fields=rows,input_fields=input_fields)
 contract('producer_registry','V4_13_PRODUCER_REGISTRY_V1',producers=[dict(producer_contract_id='LOO_CONTEXT_V1',outputs=FIELDS,source_authorities=owner,runtime='NOT_IMPLEMENTED',publication='CONTEXT_LOO',requiredness='ALL_AUTHORITY_GATED'),dict(producer_contract_id='PROFILE_ADVANCED_PROJECTION_V1',outputs=STRUCTURE,source_authority=owner['V4_12'],runtime='NOT_IMPLEMENTED',publication='ADVANCED_PROFILE_PROJECTION',operation='LOSSLESS_READ_ONLY_PROJECT')])
 contract('time_role_registry','V4_13_TIME_ROLE_REGISTRY_V1',fields=[dict(field=r['field'],role=r['time_role'],availability='SOURCE_AVAILABLE_AT_LE_CUTOFF',prior='EXACT_PREVIOUS_ACCEPTED_MARKET_SESSION_NOT_SAME_DAY_REVISION') for r in rows],input_fields=[dict(field=r['field'],role=r['time_role'],availability='SOURCE_AVAILABLE_AT_LE_CUTOFF') for r in input_fields],future_outcome_allowed=False)
 contract('input_schema','V4_13_INPUT_SCHEMA_V1',required=['security_id','trade_date','revision','cutoff','accepted_source_refs','membership_snapshot','non_target_member_facts','loo_history','stock_core_facts','v4_12_publication'],reference_required=['path','sha256','bytes','producer_contract_id','trade_date','available_at','source_revision','quality'],membership_required=['sector_id','security_id','membership_asof_date','membership_basis','provider_available_at','source_revision','quality'],accepted_only=True,missing_authority='UNKNOWN_ACCEPTED_CAPABILITY_UNAVAILABLE',raw_fallback=False)
 contract('output_schema','V4_13_OUTPUT_SCHEMA_V1',fields=FIELDS+STRUCTURE,field_envelope=['value','quality','reason','source_identity','membership_basis','loo_basis'],publication_identity=['security_id','trade_date','revision','contract_digest','membership_digest','loo_history_digest','structure_source_digest','prior_session_ref'],candidate_set_complete=True,raw_qualification_refs=['A_BASE_SEED_RAW','C_STOCK_PREWATCH_RAW'],raw_qualification_mutable=False)
 contract('projection','PROFILE_ADVANCED_PROJECTION_V1',source=owner['V4_12'],fields=STRUCTURE,source_field_paths=STRUCTURE_PATH,source_publication_contract='V4_12_R13_RUNTIME_CANDIDATE_MANIFEST',mode='COPY_VALUE_QUALITY_REASON_PRODUCER_IDENTITY_SOURCE_REF_NO_RECOMPUTATION',qualified_publication='SHA_BOUND_PUBLICATION_AUTHORIZED_BY_V4_12_ACCEPTED_HEAD',unsupported_authority='UNKNOWN_ACCEPTED_CAPABILITY_UNAVAILABLE',missing_component='NOT_IMPLEMENTED_COMPONENT_ONLY',preserve=['UNKNOWN','NOT_APPLICABLE','DEGRADED','RECONSTRUCTED_CORRECTED','AS_RECORDED_FALSE'],recompute=['FORBIDDEN_ANCHOR','FORBIDDEN_BREAKOUT','FORBIDDEN_SUPPORT','FORBIDDEN_ACCEPTANCE'],rotation=dict(core_owner='V4_08_rotation_core_state',destination='D3_CONTEXT_ENRICHMENT_ONLY',core_mutation=False),stock_raw_qualification_mutation=False)
 allowed=[('F0','A','base_seed_primitives','T','BASE_SEED_V1'),('F0','B0','sector_native','T','V4_08_SECTOR_NATIVE_V1'),('A','B0','base_seed_aggregates','T','BASE_SEED_V1'),('B0','B1','rotation_core_state','T','V4_08_ROTATION_CORE_V1'),('B0','B2','sector_raw_qualification','T','V4_08_SECTOR_PREWATCH_V1'),('F0','C','stock_core','T','STOCK_PREWATCH_V1'),('A','C','base_seed_raw','T','BASE_SEED_V1'),('C','D0','stock_prewatch_raw','T','CONFIRMATION_EVENT_V1'),('F0','D1','core_facts','T','STRUCTURE_EVENT_V1'),('D1','D1','frozen_anchor_event','T_MINUS_1','STRUCTURE_EVENT_V1'),('D0','D2','confirmation','T','STATE_EVENT_V1'),('D1','D2','structure','T','STRUCTURE_EVENT_V1'),('C','D2','stock_raw','T','STATE_EVENT_V1'),('B0','CONTEXT','non_target_sector_raw','T','LOO_CONTEXT_V1'),('B1','CONTEXT','loo_rotation_history','T_MINUS_1','LOO_CONTEXT_V1'),('B2','CONTEXT','non_target_sector_raw','T','LOO_CONTEXT_V1'),('F0','CONTEXT','accepted_membership_and_non_target_primitives','T','LOO_CONTEXT_V1'),('D1','PROFILE','structure_projection','T','PROFILE_ADVANCED_PROJECTION_V1'),('CONTEXT','PROFILE','context_fields','T','LOO_CONTEXT_V1'),('D1','D3','rotation_structure_enrichment','T','PROFILE_ADVANCED_PROJECTION_V1')]
 edges=[dict(producer=a,consumer=b,field=f,time_role=t,contract_id=id,version='EXACT_ACCEPTED_OWNER_VERSION',required=b not in ['D3'],namespace='LOO_RECOMPUTED_OWNER_LINEAGE' if b=='CONTEXT' else 'READ_ONLY_ACCEPTED_OWNER',quality_propagation='UNKNOWN_NEVER_FALSE; capability-scoped degradation preserved',runtime_implemented=False) for a,b,f,t,id in allowed]
 owners={n:ref(stage['v4_'+num+'_binding']['path']) for n,num in [('A','05'),('B0','08'),('B1','08'),('B2','08'),('C','09'),('D0','11'),('D1','12'),('D2','10')]}
 for edge in edges:
  producer=edge['producer'];consumer=edge['consumer']
  edge['source_owner_binding']=owners.get(producer,owner['V4_04'])
  path=P+'loo_context_v1.json' if consumer=='CONTEXT' or producer=='CONTEXT' else P+'projection_v1.json' if consumer in ['PROFILE','D3'] else h['b0_contract']['path'] if consumer=='B0' else h['rotation_contract']['path'] if consumer=='B1' else h['b2_contract']['path'] if consumer=='B2' else 'config/v4_09_stock_prewatch_contract_v1.json' if consumer=='C' else 'config/v4_11_confirmation_detector_contract_r2.json' if consumer=='D0' else 'config/v4_12_structure_event_contract_v1.json' if consumer=='D1' else 'config/v4_10_research_state_contract_r1_2.json' if consumer=='D2' else 'data/v4/V4_05_ACCEPTED_HEAD.json'
  artifact=read(path);edge['contract_binding']=ref(path);edge['contract_id']=artifact.get('contract_id',artifact.get('model_contract_id'));edge['version']=artifact.get('version',edge['contract_binding']['sha256'])
 forbidden=[['D2','D1','T'],['D1','B0','T'],['D1','B1','T'],['D1','B2','T'],['CONTEXT','A','T'],['CONTEXT','C','T'],['Focus/UI','QUALIFICATION','ANY'],['Supplemental','Core','ANY'],['FUTURE_OUTCOME','SAME_DAY_STATE','ANY']]
 contract('dag_edge_registry','V4_13_DAG_INTEGRATION_INTERFACE_V1',edges=edges,forbidden_edges=forbidden,LOO_B_stage_outputs='CONTEXT_ONLY_RECOMPUTED_LINEAGE_NOT_THE_SELF_INCLUDING_CORE_PUBLICATION',accepted_execution=False,V4_14_acceptance='NOT_YET_ACCEPTED_V4_14',algorithm_state_replay_pass=False)
 contract('quality_map','V4_13_QUALITY_DEGRADATION_V1',map={'READY':dict(value='KNOWN',eligibility='CONTEXT_ONLY'),'CURRENT_MEMBERSHIP_REPLAY':dict(value='DEGRADED',origin='CURRENT_MEMBERSHIP_REPLAY',pit=False,formal_context_eligible=False),'UNKNOWN':dict(value='UNKNOWN',weak_sector=False,missing_is_false=False),'NOT_APPLICABLE':dict(value=None,condition='KNOWN_COMPLETE_NO_ELIGIBLE_SECTOR'),'BLOCKED_WITH_EXPLICIT_REASON':dict(value='UNKNOWN',reason='ACCEPTED_CAPABILITY_UNAVAILABLE'),'NOT_IMPLEMENTED':dict(value=None,reason='V4_13_RUNTIME_NOT_IMPLEMENTED')},upstream_degradation='LOSSLESS_PRESERVE_NO_UPGRADE')
 from scripts.v4_13_contract_vectors import VECTORS
 contract('machine_vectors','V4_13_INDEPENDENT_MACHINE_VECTORS_V1',oracle='HAND_WRITTEN_INDEPENDENT_CONTRACT_WITNESSES_NOT_RUNTIME_OUTPUTS',vectors=VECTORS)
 files=sorted(p.relative_to(ROOT).as_posix() for p in (ROOT/'config').glob('v4_13_*.json'))
 entry=dict(contract_id='V4_13_PROFILE_ADVANCED_PROJECTION_STAGE_ENTRY_V1',status='AUTHORIZED_CONTRACT_DESIGN_ONLY',accepted_parent=owner['V4_12'],stage_name='Profile Advanced Projection',runtime_implemented=False,contracts=[ref(p) for p in files],next='WAIT_EXTERNAL_AUDIT_THEN_SEPARATE_V4_13_RUNTIME_IMPLEMENTATION_TASKS',**PERMISSIONS)
 write('reports/v4_13_r1/V4_13_STAGE_ENTRY.json',entry);write('reports/v4_13_r1/.gitattributes',b'* -text\n',True)
 print('V4_13_RUNTIME=NOT_IMPLEMENTED')
if __name__=='__main__':run()
