"""Candidate evidence manifest, scoped external-review questions, and append-only R5 audit ledger."""
import copy,json,sys,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path[:0]=[str(ROOT),str(ROOT/'src')]
from scripts.build_v4_08_r2_membership_evidence import atomic_json,atomic_bytes
from scripts.enter_source_authority_remediation_r2 import bind
P='reports/audits/A12_R2_'
STATUS='A12_R2_REAL_DATED_OWNER_CANDIDATE_READY_FOR_EXTERNAL_REAUDIT'
def read(p):return json.loads((ROOT/p).read_text(encoding='utf8'))
def main():
    entry=read(P+'STAGE_ENTRY_R1.json');assert all(bind(b['path'])['sha256']==b['sha256'] for b in entry['protected_bindings'])
    assert read('data/v4/V4_SOURCE_AUTHORITY_ACCEPTED_OWNER_REGISTRY.json')['owners']==[]
    oracle=read(P+'INDEPENDENT_REAL_SOURCE_ORACLE_R1.json');quality=read(P+'PRICE_AND_REMAINING_QUALITY_PROOF_R1.json');cascade=read(P+'DOWNSTREAM_CASCADE_AND_FULL_BUSINESS_DIFF_R1.json');execution=read(P+'TRUE_REPLAY_EXECUTION_R1.json')
    assert oracle['status_differences']==oracle['st_differences']==0 and execution['status'].startswith('PASS')
    assert quality['all_price_business_differences']==0
    assert all(s['algorithm_parameters_changed'] is False for s in cascade['stages'].values())
    empty=read('data/v4/source_evidence/a12_r2/PROVIDER_EMPTY_RETURN_CAPTURE_R1.json');assert len(empty['results'])==3 and all(not r['rows'] for r in empty['results'])
    temporal=read(P+'TEMPORAL_AND_R1_RESTORATION_PROOF_R1.json');assert temporal['formal_publication'] is False
    inventory=read(P+'SOURCE_ARCHAEOLOGY_R1.json');inventory['supersedes']=bind(P+'SOURCE_ARCHAEOLOGY_R1.json')
    rules=[p.relative_to(ROOT).as_posix() for p in (ROOT/'data/v4/source_evidence/v4_02_r3').iterdir() if p.is_file() and 'code_change' not in p.name]
    inventory['sources'].append(dict(source_family='OFFICIAL_GENERAL_TRADING_RISK_RULES',sources=[bind(p) for p in rules],dated=True,historical_queryable=False,mutable_current=False,source_class='OFFICIAL',can_prove='Versioned board-level ST/risk-warning ratios and trading regimes; original price-policy rules remain bound',cannot_prove='Per-security historical ST or suspension effective intervals; rule applicability must use original dated policy',revision_semantics='Published effective rule versions and immutable capture bytes; 2026 rules cannot retroactively replace 2023 rules',knowledge_time_semantics='Publication/effective date separate from capture time; no first-availability inference'))
    atomic_json(ROOT/(P+'SOURCE_ARCHAEOLOGY_R2.json'),inventory)
    matrix=read(P+'REAL_SAMPLE_MATRIX_R1.json');gap=read(P+'REAL_DATA_GAP_MATRIX_R1.json')
    matrix.update(supersedes=bind(P+'REAL_SAMPLE_MATRIX_R1.json'),samples=matrix['samples']+gap['samples'],real_data_gap_source=bind(P+'REAL_DATA_GAP_MATRIX_R1.json'),data_gap_scope_limit=gap['scope'],external_acceptance=None)
    atomic_json(ROOT/(P+'REAL_SAMPLE_MATRIX_R2.json'),matrix)
    amendment=read(P+'MASTER_SOURCE_AUTHORITY_AMENDMENT_CANDIDATE_R1.json')
    amendment.update(supersedes=bind(P+'MASTER_SOURCE_AUTHORITY_AMENDMENT_CANDIDATE_R1.json'),sample_matrix=bind(P+'REAL_SAMPLE_MATRIX_R2.json'),observed_daily_owner_proposal=bind(P+'OBSERVED_DAILY_AUTHORITY_PROPOSAL_R1.json'),source_evidence_supplement='Corrects data-gap evidence scope: twelve 9/28 local misses are suspended; actual 9/30 should-trade vs frozen 9/28 local input is capture lag. Historical owners and all values unchanged.',real_empty_returns=bind('data/v4/source_evidence/a12_r2/PROVIDER_EMPTY_RETURN_CAPTURE_R1.json'))
    atomic_json(ROOT/(P+'MASTER_SOURCE_AUTHORITY_AMENDMENT_CANDIDATE_R2.json'),amendment)
    scope=dict(audit_id='A12_R2_POSITIVE_ST_CODE_CHANGE_SCOPE',status='OPEN',scope='ST source semantics at actual numeric code-change boundary',evidence=[bind(P+'REAL_SAMPLE_MATRIX_R1.json'),bind('data/v4/bootstrap/dated_security_alias_r7.jsonl')],finding='The sole accepted numeric code-change identity has 391 predecessor plus 395 successor rows, all isST=0. Real boundary verification passed; a positive ST-during-code-change example does not exist in required scope.',acceptance_independent=True,external_acceptance=None,formal_consumer_authorization=False,next_step='External auditor must explicitly adjudicate this negative scope census or prescribe a separately bound real positive fixture; no fabricated ST state and no self-waiver')
    atomic_json(ROOT/(P+'ST_CODE_CHANGE_SCOPE_AUDIT_R1.json'),scope)
    gap_scope=dict(audit_id='A12_R2_INTERIOR_DATA_GAP_SCOPE',status='OPEN',scope='Same-cutoff interior historical missing bar with provider should-trade=1',evidence=[bind(P+'REAL_DATA_GAP_MATRIX_R1.json'),bind(P+'INDEPENDENT_REAL_SOURCE_ORACLE_R1.json')],finding='Historical required missing rows and twelve 9/28 local misses are provider=0 suspension. Actual 9/30 provider=1 vs frozen 9/28 package proves capture lag only, not an interior missing history bar.',external_acceptance=None,formal_consumer_authorization=False,next_step='External disposition of capture-lag real data-gap case and negative interior-gap census; prescribe separately dated real source fixture if required')
    atomic_json(ROOT/(P+'INTERIOR_DATA_GAP_SCOPE_AUDIT_R1.json'),gap_scope)
    scope_evidence=[P+n+'_R1.json' for n in ['SOURCE_ARCHAEOLOGY','PROVIDER_SEMANTICS_AND_REVISION','REAL_SAMPLE_MATRIX','REAL_DATA_GAP_MATRIX','SOURCE_REVISION_RECOVERY_BINDING','MASTER_SOURCE_AUTHORITY_AMENDMENT_CANDIDATE','OBSERVED_DAILY_AUTHORITY_PROPOSAL','V4_02_FULL_HISTORICAL_REPAIR_AND_DIFF','FORMAL_PERIOD_AUTHORITY_REBIND','INDEPENDENT_REAL_SOURCE_ORACLE','UNCHANGED_REPLAY_SOURCE_PROOFS','TRUE_REPLAY_EXECUTION','V4_04_TRUE_REPLAY','DOWNSTREAM_CASCADE_AND_FULL_BUSINESS_DIFF','PRICE_AND_REMAINING_QUALITY_PROOF','SOURCE_NOTICE_SEMANTIC_AUDIT','ST_CODE_CHANGE_SCOPE_AUDIT']]
    scope_evidence.extend([P+'REAL_SAMPLE_MATRIX_R2.json',P+'MASTER_SOURCE_AUTHORITY_AMENDMENT_CANDIDATE_R2.json',P+'INTERIOR_DATA_GAP_SCOPE_AUDIT_R1.json',P+'SOURCE_ARCHAEOLOGY_R2.json',P+'TEMPORAL_AND_R1_RESTORATION_PROOF_R1.json'])
    atomic_json(ROOT/(P+'CANDIDATE_EVIDENCE_MANIFEST_R1.json'),dict(contract_id='A12_R2_REAL_SOURCE_CANDIDATE_MANIFEST_V1',status='ENGINEERING_REPLAY_COMPLETE_SOURCE_SCOPE_DISPOSITION_PENDING',evidence=[bind(p) for p in scope_evidence],stage_contract=entry['contract_id'],scope_limits=[scope['finding'],gap_scope['finding']],formal_consumer_authorization=False,owner_registry_written=False,dm01_final_all_nine='BLOCKED',accepted_heads_unchanged=True,external_acceptance=None))
    gates={f'A12R2-G{i:02d}':'PASS_ENGINEERING' for i in range(1,18)}
    gates['A12R2-G01']=gates['A12R2-G02']='PENDING_INDEPENDENT_EXTERNAL_AUDIT';gates['A12R2-G16']='PENDING_CLEAN_DETACHED';gates['A12R2-G17']='PENDING_INDEPENDENT_EXTERNAL_AUDIT'
    atomic_json(ROOT/(P+'ENGINEERING_GATES_R1.json'),dict(status='PENDING_CLEAN_DETACHED',allowed_candidate_status=STATUS,gates=gates,evidence_manifest=bind(P+'CANDIDATE_EVIDENCE_MANIFEST_R1.json'),gate_notes={'A12R2-G01':'Real required history cases plus independently verified delayed 9/28 DATA_GAP source bytes; no future row appended to historical rebuild','A12R2-G02':'Real ST changes/removal/suspended/new listing and code-change non-ST census supplied. Positive ST code-change case is not present in required scope: external disposition required, not an engineering PASS claim. Delisting-board vs isST taxonomy conflict is explicit, not a fabricated numeric provider disagreement.','A12R2-G09':'Actual registry unchanged and pending owners rejected. Exact externally accepted prospective fixtures pass A10 proof only inside pytest temporary roots.','A12R2-G10':'Full status/ST producer rebuild. Every original price-base dependency equal on 4,035,729 rows; original generic R6 price kernel rerun, not a fitted count.','A12R2-G12':'True V4-04 replay; remaining quality unknowns separately proven. Core Profile business completion is not asserted.'},next_stage='Independent A12 R2 source semantics/amendment reaudit, including positive ST code-change scope disposition. Only a later explicit promotion card may register accepted owners or amend business heads. DM01 final all-nine remains BLOCKED.',external_acceptance=None))
    ledger=copy.deepcopy(read('reports/audits/V4_CROSS_STAGE_OPEN_AUDIT_REMEDIATION_REGISTRY_R4.json'))
    ledger.update(contract_id='V4_CROSS_STAGE_OPEN_AUDIT_REMEDIATION_REGISTRY_R5',supersedes=bind('reports/audits/V4_CROSS_STAGE_OPEN_AUDIT_REMEDIATION_REGISTRY_R4.json'),baseline_commit=entry['baseline_commit'],authority=entry['task'],business_accepted_heads_modified=False,accepted_source_authority_owners=[])
    for e in ledger['entries']:
        if e['work_package']=='WP-A12-V4-02-STATUS-ST-AUTHORITY':
            e['prior_transition_r4']=e.get('transition')
            e.update(status='OPEN',implementation_status=STATUS,external_acceptance='PENDING',formal_consumer_authorization=False,latest_task=entry['task'],status_path=P+'ENGINEERING_GATES_R1.json',transition=dict(status='OPEN',implementation_status=STATUS,external_acceptance='PENDING',formal_consumer_authorization=False),evidence=e.get('evidence',[])+[bind(P+'CANDIDATE_EVIDENCE_MANIFEST_R1.json')],next_step='External Path B amendment acceptance including scope audits, then separate authorized owner registration')
    for item in [read(P+'SOURCE_NOTICE_SEMANTIC_AUDIT_R1.json'),scope,gap_scope]:
        ledger['entries'].append(dict(audit_id=item['audit_id'],work_package='WP-INDEPENDENT-'+item['audit_id'],status='OPEN',implementation_status='EVIDENCE_FROZEN_EXTERNAL_DISPOSITION_PENDING',priority='P1',scope=item['scope'],evidence=item['evidence'],external_acceptance=None,formal_consumer_authorization=False,depends_on=[],does_not_block_engineering_stage=True,next_step=item.get('next_step',item.get('next_stage')),acceptance_independent_from_a12=True))
        ledger['dependency_graph']['WP-INDEPENDENT-'+item['audit_id']]=[]
    ledger['audit_count']=len(ledger['entries']);atomic_json(ROOT/'reports/audits/V4_CROSS_STAGE_OPEN_AUDIT_REMEDIATION_REGISTRY_R5.json',ledger)
    stats=read(P+'V4_02_FULL_HISTORICAL_REPAIR_AND_DIFF_R1.json')['counts']
    text='''# A12 R2 候选阶段交付（外部接受待定）\n\n阶段合同：WP-A12-R2-REAL-DATED-STATUS-ST-AUTHORITY。A10 基础设施接受已正式登记；当前 owner registry 仍为空。\n\n唯一选择 Path B：历史 BaoStock 字段作为 reconstructed provider authority 的 amendment candidate；TDX 实际 bar 优先。所有 source observation 时间保留，禁止 AS_RECORDED 回填。观察日常流的候选合同只覆盖实际捕获的 9/28 与 9/30，不授权未捕获日期。\n\n全历史 4,035,729 行：ACTUAL_TRADED 4,026,611、SUSPENDED 9,118、DATA_GAP 0、UNKNOWN 0；ST=0 3,913,800、ST=1 121,929、UNKNOWN 0。4 个 provider=0/TDX 实际 bar 冲突均保留本地实际。既有 9/28 原始捕获与原生 TDX zip 独立证明 12 个 should-trade local gap；没有为 DM01 重复联网。\n\n原价格 runtime 全历史重跑，business fields 与 accepted R6 全行一致；周/月 RAW/QFQ 逐列一致，另从 source bytes 重算每个 period 的状态计数。V4-03/04/05/07/08/09 使用原算法，12 份 entrypoint 的 AST 可逆路径替换证明与 R1 一致。统计、剩余 UNKNOWN 原因和全量业务 diff 见 A12_R2_PRICE_AND_REMAINING_QUALITY_PROOF_R1.json 与 A12_R2_DOWNSTREAM_CASCADE_AND_FULL_BUSINESS_DIFF_R1.json。Core Profile 的业务质量修复完成尚未声明。\n\nST 正样本代码变更的限制：唯一 accepted 数字 alias 共 786 行均为非 ST。真实负边界已验证，正样本不存在于本轮 required scope。G02 保留 PENDING_INDEPENDENT_EXTERNAL_AUDIT，必须由外部审查明确处置；没有伪造样本或自行豁免。IPO 延期误标 suspension 的来源语义问题作为独立 OPEN audit 记录在 R5，所有旧 ledger 与 accepted heads 保持字节不变。\n\n最终仅为 A12_R2_REAL_DATED_OWNER_CANDIDATE_READY_FOR_EXTERNAL_REAUDIT。Clean detached 结果与提交绑定见阶段 closure。G17 外部独立接受待定，DM01 final all-nine、owner promotion、production、shadow、focus 均未授权。下一阶段需独立审计，然后另发 promotion/amendment card。\n'''
    text=text.replace('既有 9/28 原始捕获与原生 TDX zip 独立证明 12 个 should-trade local gap','既有 9/28 原始捕获与原生 TDX zip 独立证明 12 个停牌缺 bar，均非 DATA_GAP；已有 9/30 provider=1 与冻结于 9/28 的本地输入构成真实捕获滞后缺口样本，不能称历史内部缺 bar')
    text=text.replace('G02 保留','G01 的历史内部缺口正样本限制与 G02 的 ST 代码变更正样本限制均保留')
    text+='\n真实 V4-04 replay：'+json.dumps(quality['profile_quality']['V4_04']['quality_counts'],ensure_ascii=False)+'；V4-05：'+json.dumps(quality['profile_quality']['V4_05']['quality_counts'],ensure_ascii=False)+'。价格已知 '+str(quality['known'])+' 行，UNKNOWN '+str(quality['unknown'])+' 行；UNKNOWN 原因逐项保留。\n'
    atomic_bytes(ROOT/'docs/audits/A12_R2_REAL_DATED_OWNER_CANDIDATE_CLOSURE_20261001.md',text.encode('utf8'))
    print('A12_R2_GATES_FROZEN; G01/G02/G17 remain external pending; clean pending')
if __name__=='__main__':main()
