"""Record exact local-data continuation conclusions, preserving prior receipts."""
from immediate_r3_common import *
from datetime import datetime,timezone
from collections import Counter

def main():
    out=OUT/'09_CONTINUATION';stage=load(out/'STAGE_CONTRACT.json');alg=load(out/'UPSTREAM_ORACLE_RESULT.json');amount=load(out/'AMOUNT_REPRESENTATION_RESULT.json');loo=load(out/'FULL_LOO_ORACLE_RESULT.json');pulse=load(out/'PULSE_SOURCE_ORACLE_RESULT.json');h=load('data/v4/V4_OPERATIONAL_RESEARCH_HEAD.json');day=h['accepted_trade_date'];policy=load('config/v4_10_input_provenance_r1_2.json')
    for ref in stage['protected']:checked(ref)
    missing={k:v for k,v in policy['fields'].items() if 'SECTOR' in v['accepted_entity_types'] and not v['implemented']}
    write(out/'SECTOR_D2_EXACT_CONTRACT_GAPS.json',dict(contract_binding=binding('config/v4_10_input_provenance_r1_2.json'),entity_scope=policy['entity_scope'],missing_fields=missing,dated_candidate_adapter=binding('src/v4/confirmation_d2_candidate_r5.py'),candidate_adapter_scope='STOCK_ONLY',b0_prewatch_is_not_sector_maturity=True,blocker='FORMAL_SECTOR_EXTRACTION_ENTRY_CONTRACT_REQUIRED',prohibited_shortcut='Do not relabel stock producers, B0 prewatch or Rotation phase as sector D2 maturity/health',next_action='Version sector WARM/CONFIRMED/frozen-invalidation extraction and entry semantics before a valid dated candidate can be built'))
    actual=load(h['owners'][day]['sector']);rot={r['sector_id']:r for r in load(h['owners'][day]['rotation'])}
    # Materialize per-entity readiness only; never fabricate a D2 result.
    rows=[dict(entity_id=r['sector_id'],entity_type='SECTOR',trade_date=day,dq5=rot.get(r['sector_id'],{}).get('rotation',{}).get('fields',{}).get('dq5'),missing_contract_fields=sorted(missing),maturity=dict(value='UNKNOWN',quality='SOURCE_INCOMPLETE'),health=dict(value='UNKNOWN',quality='SOURCE_INCOMPLETE'),accepted=False,publishable=False,reason='FORMAL_SECTOR_EXTRACTION_ENTRY_CONTRACT_REQUIRED') for r in actual]
    write(out/'SECTOR_D2_DATED_READINESS_CANDIDATE.json',dict(contract='SECTOR_D2_READINESS_ONLY_R3_V1',source_refs=[h['owners'][day]['sector'],h['owners'][day]['rotation']],rows=rows,production_enabled=False,not_a_formal_D2_owner=True))
    snapshot=load(h['membership_snapshot']);member=load(snapshot['memberships']);bj={r['source_security_key'] for r in member if r.get('source_security_key','').startswith('BJ.')};wanted={r['raw_id'] for r in load(out/'MEMBER27_OFFICIAL_ALIAS_INVESTIGATION.json')['items'] if r['raw_id'].startswith('BJ.')}
    write(out/'BSE_DEFERRED_SCOPE.json',dict(user_instruction='Skip BSE requiring public-web verification; current priority is TDX-local plus daily baostock data closure',industry_T0706_deferred_raw_ids=sorted(wanted),all_snapshot_BSE_unique_raw_ids=len(bj),official_web_capture_used_for_production=False,previous_official_investigation='Retained as historical investigation only; not identity authority',rows_deleted=False,pool_expanded=False,status='USER_DEFERRED'))
    owner=load(h['owners'][day]['diagnostic'])['owner'];identity=load(owner['sources']['identity']);import zipfile
    with zipfile.ZipFile(checked(owner['sources']['package'])) as z:entries=[n for n in z.namelist() if '001235' in n]
    bao=load(out/'SZ001235_BAOSTOCK_DIAGNOSTIC.json');assert all(r['error_code']=='0' and not r['rows'] for r in bao['requests'])
    write(out/'SZ001235_LOCAL_DATA_DISPOSITION.json',dict(raw_id='SZ.001235',tdx_package=owner['sources']['package'],tdx_matching_day_entries=entries,accepted_identity_source=owner['sources']['identity'],accepted_matching_rows=[r for r in identity['rows'] if r.get('source_security_key')=='SZ.001235'],baostock=binding(out/'SZ001235_BAOSTOCK_DIAGNOSTIC.json'),status='SOURCE_NOT_PRESENT_IN_CURRENT_TWO_FEEDS',reason='Frozen package has no day entry; accepted identity has no row; bounded baostock basic/daily requests succeed with empty rows',not_listed_claim=False,identity_created=False))
    write(out/'CONTINUATION_ACCEPTANCE.json',dict(algorithm=dict(checks=alg['checks'],errors=alg['errors'],unknown_endpoint_window_checks=len(alg['unknown_quality_branches']),scope='Observed ATR/structure/base values plus independently unavailable windows/endpoints'),full_current_LOO=loo,first_pulse=dict(checks=pulse['checks'],errors=pulse['errors'],real_rows=pulse['observed_pulse_rows']),amount=dict(exact_representation_counts=amount['counts'],unexplained_representation=amount['counts'].get('UNEXPLAINED_REPRESENTATION',0),provider_algorithm_proven=False,formal_authority_changed=False),cohort=dict(regression_passed=14,fix='Bound first availability to immutable T0 freeze, independent of later read cutoff; absent-owner counts remain unknown',owner_permission='NOT_GRANTED'),sector_candidate_rows=len(rows),BSE='USER_DEFERRED',protected_heads='UNCHANGED'))
    stage['acceptance']='PASS_SCOPED_WITH_EXACT_SOURCE_AND_CONTRACT_GAPS';stage['finished_at']=datetime.now(timezone.utc).isoformat();write(out/'STAGE_CONTRACT.json',stage)
    ledger=load(OUT/'08_REMAINING_LEDGER.json')
    for issue in ledger['appended_R3']:
        if 'R3-UPSTREAM' in issue['issue_id']:
            issue.update(status='PASS_SCOPED_CURRENT_PUBLISHED_NUMERIC_CHAIN',scope='ATR/structural values and unavailable endpoints; all current operational LOO contexts; first-pulse baskets',evidence='09_CONTINUATION/CONTINUATION_ACCEPTANCE.json',next_action='Future full LOO rank/recursive-episode production scope needs separately published owner; not present in this operational owner')
        if 'R3-MEMBER27' in issue['issue_id']:issue.update(status='26_USER_DEFERRED_1_CURRENT_TWO_FEEDS_ABSENT',next_action='Do not acquire public-network BSE evidence; preserve raw rows. Recheck SZ.001235 only when actual local/Bao feed provides data',evidence='09_CONTINUATION/SZ001235_LOCAL_DATA_DISPOSITION.json')
        if issue['issue_id']=='M10/DD-A05/R3':issue.update(status='REPRESENTATION_PASS_SCOPED_AUTHORITY_SEPARATE',next_action='Keep original Native authority; exact representation audit is closed for sampled actual captures. Economic-equivalence and formal sector Amount A remain separate',evidence='09_CONTINUATION/AMOUNT_REPRESENTATION_RESULT.json')
    ledger.setdefault('continuation_R3',[]).append(dict(observed_at=stage['finished_at'],evidence='09_CONTINUATION/CONTINUATION_ACCEPTANCE.json',ATR_structure=f'{alg["checks"]} independent checks incl325 unavailable windows/endpoints passed',full_current_LOO=f'{loo["pairs"]} pairs; {loo["checks"]} checks; zero differences',first_pulse=f'{pulse["checks"]} comparisons on2 actual pulse sources',amount345='All345 exact whole-yuan HALF_UP then binary32; empirical representation proof, no provider implementation claim',BSE='USER_DEFERRED',sector='Exact missing extraction/entry contracts identified, dated readiness candidate produced',cohort='T0 first-availability leak corrected, 14 tests passed',remaining='Formal sector extraction/entry contracts and cohort/model/grant/as-recorded sources; no permission is manufactured'))
    ledger['overall']='CURRENT_LOCAL_DATA_AUDIT_PASS_SCOPED_FORMAL_CAPABILITIES_SEPARATE'
    write(OUT/'08_REMAINING_LEDGER.json',ledger)
    markdown(out/'CONTINUATION_RESULT.md',f'# R3 继续处理结果\n\n上轮停止过早，本轮继续完成数据侧可执行闭环；保留此前收据，最新判定追加到任务清单。\n\n- ATR、前高低、斜率及结构基础字段：{alg["checks"]}项独立比较、{alg["errors"]}差异，包含325项窗口不足/端点缺失的未知值证明。\n- 当前全量LOO：{loo["pairs"]}组合、{loo["checks"]}项比较、零差异。当前Owner实际提供剔除自身中位数和相对状态，不提供全LOO截面排名/递归episode；后者独立域缺源，不能用含自身前态替代。\n- 两个真实pulse：{pulse["checks"]}项冻结篮子及原始前日/当日价格基线比较，零差异；第一日有限窗口重置是corrected研究边界，不冒称历史episode不存在。\n- 原345条金额残差全部由“按元HALF_UP后转binary32”精确复现，不新增容差、不改原始金额。15,632条可比较记录均有精确表示路径。此为表示兼容性证明，不推定供应商内部实现、经济等价或正式Amount A权限。\n- Cohort修复历史首次可用晚于T0冻结仍被后续读取接纳的漏洞；14项针对性测试通过，缺Owner样本数改为未知。\n- 板块400条日期化readiness隔离候选落盘；正式合同明确规定WARM/CONFIRMED等SECTOR extraction/entry未接纳，当前adapter仅STOCK。不是简单把接口类型改为SECTOR即可合法完成，具体缺口见SECTOR_D2_EXACT_CONTRACT_GAPS.json。\n- 按用户最新指令：26个北交所成员暂缓，不继续网络求证、不扩池；SZ.001235冻结通达信日线包/身份池无记录，baostock基本信息/指定日期日线成功返回空记录，精确标SOURCE_NOT_PRESENT，不推定未上市。\n\nCohort/FEP正式域缺AS_RECORDED enrollment/model/grant，当前可开发读取契约已修复；不能从corrected行情伪造历史首次可用、独立入组和授权预测。保护Head SHA不变；临时数据均在G盘。当前本地+baostock数据审计PASS_SCOPED，正式能力和外部发布门仍单列。\n')
    print(json.dumps(dict(algorithm_checks=alg['checks'],algorithm_errors=alg['errors'],unexplained_representation=amount['counts'].get('UNEXPLAINED_REPRESENTATION',0),sector_readiness_rows=len(rows))))
if __name__=='__main__':main()
