"""Hand-authored R15 semantic oracle; no runtime/helper-generated expected values."""
REF = {'path':'SYNTHETIC_ENGINEERING_ONLY/source.json','sha256':'0000000000000000000000000000000000000000000000000000000000000000','bytes':0,'producer_contract_id':'SYNTHETIC_CONTRACT_WITNESS','trade_date':'2026-09-30','available_at':'2026-09-30T23:00:00+08:00','source_revision':'SYNTHETIC_R1','sector_id':'I1','target_security_id':'s','loo_lineage_id':'SYNTHETIC_LOO_LINEAGE'}
COMPONENTS={
 'loo_b0_raw':{'value':True,'quality':'KNOWN','reasons':[],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_B0_REF.json')]},
 'loo_confirmed_raw':{'value':None,'quality':'NOT_IMPLEMENTED','reasons':['B2_LEGACY_NOT_IMPLEMENTED'],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_B2_REF.json')]},
 'loo_warm_raw':{'value':None,'quality':'NOT_IMPLEMENTED','reasons':['B2_LEGACY_NOT_IMPLEMENTED'],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_B2_REF.json')]},
 'emergence':{'value':'HIGH','quality':'KNOWN','reasons':[],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_NATIVE_REF.json')]},
 'adjusted_seed_width':{'value':0.3,'quality':'KNOWN','reasons':[],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_07_SEED_REF.json')]},
 'rotation_core_state':{'value':'STABLE','quality':'KNOWN','reasons':[],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_ROTATION_REF.json')]},
 'relative_sector_state':{'value':'NEUTRAL','quality':'KNOWN','reasons':[],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_RELATIVE_REF.json')]}}
SNAPSHOT={'selected_sector_id':'I1','sector_type':'INDUSTRY',**COMPONENTS,'membership_basis':'PIT_OBSERVED','context_quality':'DEGRADED','reasons':['B2_LEGACY_NOT_IMPLEMENTED'],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/MEMBERSHIP_REF.json'),dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_CONTEXT_REF.json')]}
VECTORS=[
 {'id':'R15-01','alias':'T01','kind':'relationships','input':{'membership_quality':'KNOWN','industry':'I1','concepts':['C1','C2'],'loo_history':None},'expected':{'primary_industry':{'value':'I1','quality':'KNOWN'},'supporting_concepts':{'value':['C1','C2'],'quality':'KNOWN'}}},
 {'id':'R15-02','alias':'T02','kind':'relationships','input':{'membership_quality':'UNKNOWN','industry':None,'concepts':None,'loo_history':None},'expected':{'primary_industry':{'value':None,'quality':'UNKNOWN'},'supporting_concepts':{'value':None,'quality':'UNKNOWN'}}},
 {'id':'R15-03','kind':'dependencies','input':{'all_current_sources_known':True,'loo_history':None},'expected':{'primary_industry':'KNOWN','supporting_concepts':'KNOWN','algorithmic_support_sector':'UNKNOWN','relative_sector_state':'KNOWN'}},
 {'id':'R15-04','alias':'S01','kind':'sector_snapshot','input':SNAPSHOT,'expected':SNAPSHOT},
 {'id':'R15-05','kind':'membership_authority','input':{},'expected':{'membership_owner':'data/v4/V4_08_PIT_MEMBERSHIP_ACCEPTED_HEAD_R1.json','scope':'ENGINEERING_CONSUMER_SCOPE_PROVEN','production':False}},
 {'id':'R15-06','kind':'core_authority','input':{},'expected':{'non_target_core_facts':'data/v4/V4_04_ACCEPTED_HEAD.json','non_target_native_facts':'data/v4/V4_05_ACCEPTED_HEAD.json'}},
 {'id':'R15-07','kind':'seed_authority','input':{},'expected':{'non_target_base_seed_raw':'data/v4/V4_07_ACCEPTED_HEAD.json'}},
 {'id':'R15-08','kind':'dual_binding','input':{},'expected':{'rotation_source':'data/v4/V4_08_ACCEPTED_HEAD_AMENDED_R1.json','structure_source':'data/v4/V4_12_ACCEPTED_HEAD.json'}},
 {'id':'R15-09','kind':'enrichment','input':{'rotation_core_state':'STABLE','rotation_quality':'KNOWN','rotation_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_08_ROTATION.json'),'structure_component':None,'structure_quality':'NOT_IMPLEMENTED','structure_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_12_STRUCTURE.json'),'reasons':['D1_UNAVAILABLE']},'expected':{'rotation_core_state':'STABLE','rotation_quality':'KNOWN','rotation_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_08_ROTATION.json'),'structure_component':None,'structure_quality':'NOT_IMPLEMENTED','structure_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_12_STRUCTURE.json'),'combined_quality':'DEGRADED','reasons':['D1_UNAVAILABLE']}},
 {'id':'R15-10','kind':'D1_perturbation','input':{'B1':'STABLE','D1_before':'IDLE','D1_after':'HELD_CONFIRMED'},'expected':{'B1_before':'STABLE','B1_after':'STABLE'}},
 {'id':'R15-11','kind':'context_perturbation','input':{'A':True,'C':False,'context_before':'UNKNOWN','context_after':'READY'},'expected':{'A':True,'C':False}},
 {'id':'R15-12','kind':'predecessor','input':{'target':'2026-09-30','calendar':['2026-09-24','2026-09-28','2026-09-29','2026-09-30'],'revisions':['r1','r2','r3']},'expected':{'predecessors':['2026-09-29','2026-09-29','2026-09-29']}},
 {'id':'R15-13','alias':'S02','kind':'sector_snapshot','input':{**SNAPSHOT,'relative_sector_state':{'value':None,'quality':'UNKNOWN','reasons':['RELATIVE_MISSING'],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_RELATIVE_REF.json')]},'reasons':['B2_LEGACY_NOT_IMPLEMENTED','RELATIVE_MISSING']},'expected':{**SNAPSHOT,'relative_sector_state':{'value':None,'quality':'UNKNOWN','reasons':['RELATIVE_MISSING'],'source_refs':[dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/LOO_RELATIVE_REF.json')]},'reasons':['B2_LEGACY_NOT_IMPLEMENTED','RELATIVE_MISSING']}},
 {'id':'R15-14','kind':'enrichment','input':{'rotation_core_state':None,'rotation_quality':'UNKNOWN','rotation_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_08_ROTATION.json'),'structure_component':{'support_state':'TESTING'},'structure_quality':'KNOWN','structure_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_12_STRUCTURE.json'),'reasons':['ROTATION_MISSING']},'expected':{'rotation_core_state':None,'rotation_quality':'UNKNOWN','rotation_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_08_ROTATION.json'),'structure_component':{'support_state':'TESTING'},'structure_quality':'KNOWN','structure_source_ref':dict(REF, path='SYNTHETIC_ENGINEERING_ONLY/V4_12_STRUCTURE.json'),'combined_quality':'DEGRADED','reasons':['ROTATION_MISSING']}}]
