"""Atomic additive R30 contract authoring; never opens live observation storage."""
import hashlib
import json
import os
from pathlib import Path
import subprocess

ROOT=Path(__file__).resolve().parents[2]
BASE='c38c25dd189b3996f53e85dc64bbc142db1c188e'


def sha(path):
    with path.open('rb') as stream: return hashlib.file_digest(stream,'sha256').hexdigest()


def write(path,value):
    assert path.startswith(('reports/r30/','docs/evidence/r30/','config/v4_21_'))
    target=ROOT/path; target.parent.mkdir(parents=True,exist_ok=True)
    data=value if isinstance(value,str) else json.dumps(value,indent=2,ensure_ascii=False,sort_keys=True)+'\n'
    staging=target.with_name(target.name+'.r30-staging')
    with staging.open('wb') as stream:
        stream.write(data.replace('\r\n','\n').encode('utf8')); stream.flush(); os.fsync(stream.fileno())
    os.replace(staging,target)


def build():
    from reports.r30.design_ledger import CAPS,LANES,PARTITION,STATES
    upgrade='docs/evidence/A_SHARE_RESEARCH_SYSTEM_V4_2_2_FINAL_EXECUTABLE_CONTRACT_REV4_FEP_R2_20260930.md'
    documents=[]
    for name in ('V4_NEXT_ROUND_EXECUTION_MASTER_R30_20261004.md','V4_21_R30_CONTINUED_FORWARD_OBSERVATION_CONTRACT_DESIGN_TASK_20261004.md','V4_R29_V4_20_DEFAULT_UI_CUTOVER_CONTRACT_DESIGN_FINAL_INDEPENDENT_EXTERNAL_AUDIT_R1_20261004.md'):
        source=Path('D:/Users/lps/Desktop/阶段任务')/name
        documents.append(dict(source=str(source),original_sha256=sha(source),copy='docs/evidence/r30/'+name)); write(documents[-1]['copy'],source.read_text(encoding='utf8'))
    write('reports/r30/STAGE_CONTRACT.json',dict(stage='V4-21',mode='CONTRACT_DESIGN_ONLY',baseline=BASE,upgrade=dict(path=upgrade,sha256=sha(ROOT/upgrade),sections=['45A','46','46A','47','51A','52A','78/V4-21','81.4']),documents=documents,allowed=['config/v4_21_*','reports/r30/*','docs/evidence/r30/*','tests/test_v4_21_forward_observation_contract.py'],forbidden=['settlement engine','real observation writer','authority or UI/Focus routing changes','accepted heads','TDX writes'],acceptance='PENDING_LOCAL_DESIGN_VALIDATION',next='STOP_WAIT_R30_INDEPENDENT_EXTERNAL_AUDIT'))
    names=subprocess.check_output(['git','ls-tree','-r','--name-only',BASE],cwd=ROOT,text=True,encoding='utf8').splitlines()
    unrelated=subprocess.check_output(['git','ls-files','--others','--exclude-standard','-z'],cwd=ROOT).decode('utf8').split('\0')
    write('reports/r30/PROTECTED_BASELINE.json',dict(baseline=BASE,tracked={n:sha(ROOT/n) for n in names if (ROOT/n).is_file()},unrelated={n:sha(ROOT/n) for n in unrelated if n and not n.startswith(('reports/r30/','docs/evidence/r30/','config/v4_21_','tests/test_v4_21_'))}))
    owners=['config/v4_15_cohort_contract_v1.json','config/v4_15_control_assignment_contract_v1.json','config/v4_15_due_planner_contract_v1.json','config/v4_15_outcome_status_contract_v1.json','config/v4_15_settlement_revision_contract_v1.json','config/v4_16_settlement_worker_contract_v1.json','config/v4_19_focus_source_cutover_contract_v1.json']
    common=['observation_namespace','evidence_lane','capability','model_contract_id','parameter_digest','state_lineage_id','source_publication','source_digest','evidence_origin','execution_mode','accepted_at','source_quality']
    def schema(fields,key,owner): return dict(required=common+fields,identity_key=key,owner=owner,append_only=True,physical_storage='DESIGN_ONLY_NOT_CREATED; ACCEPTED_STORAGE_BINDING_REQUIRED',missing='BLOCKED_AFFECTED_SCOPE_WITH_REASON')
    c=dict(contract_id='V4_21_CONTINUED_FORWARD_OBSERVATION_CONTRACT_V1',version='1.0.0',stage='V4-21',mode='CONTRACT_DESIGN_ONLY',baseline=BASE,status='LOCAL_DESIGN_PENDING_EXTERNAL_AUDIT',owner_bindings=[dict(path=p,sha256=sha(ROOT/p),contract_id=json.loads((ROOT/p).read_text(encoding='utf8'))['contract_id']) for p in owners],capabilities=list(CAPS),partition_keys=list(PARTITION),
        evidence_lanes={lane:dict(namespace={'SHADOW_REAL':'SHADOW_V4','PRODUCTION_REAL':'V4_PRODUCTION_FUTURE','HISTORICAL_REPLAY':'REPLAY','RECONSTRUCTED_ASOF':'RECONSTRUCTED_ASOF','ACTIVATION_SIMULATION':'ACTIVATION_SIMULATION'}[lane],real_eligible=lane in ('SHADOW_REAL','PRODUCTION_REAL'),required_origin='PIT_OBSERVED' if lane in ('SHADOW_REAL','PRODUCTION_REAL') else 'EXACT_NATIVE_DIAGNOSTIC_ORIGIN',required_publication='EXACT_ACCEPTED_REAL_PUBLICATION_WITH_OWNER_CAPABILITY_AND_ASOF_VISIBILITY_PROOF' if lane in ('SHADOW_REAL','PRODUCTION_REAL') else 'DIAGNOSTIC_ONLY_NEVER_REAL_GATE') for lane in LANES},
        session_ledger=schema(['trade_date','market_session_id','market_session_ordinal','calendar_identity','slot_status','publication_id','publication_revision','source_availability','evaluable','missed_reason','session_receipt_id','slot_receipt_digest'],list(PARTITION)+['market_session_id'],'V4_16_ACCEPTED_SLOT_AND_PUBLICATION_OWNER; V4_21_READ_ONLY_CANONICAL_PROJECTION'),
        event_cohort_ledger=schema(['logical_event_id','event_type','entity_id','T0','enrollment_id','cohort_namespace','original_revision','eligible','displayed','control_assignment_ids','benchmark_ids','calendar_identity','adjustment_identity'],['logical_event_id','enrollment_id'],'COHORT_V1_AND_V4_15_CONTROL_ASSIGNMENT; NO_SECOND_ORIGINAL'),
        due_outcome_ledger=schema(['due_id','enrollment_id','horizon','due_date','status','native_status','outcome_id','outcome_contract_id','evaluation_source_digest','outcome_revision','source_identity','observed_at','right_censor_reason','reason_codes','suspension_handling','delisting_handling','missing_handling','benchmark_control_outcome_refs','accepted_metric_refs','supersedes','first_observed_id','latest_corrected_id'],['enrollment_id','horizon','outcome_contract_id','evaluation_source_digest'],'DUE_PLANNER_V1_OUTCOME_STATUS_V1_OUTCOME_REVISION_V1; KEEP_NATIVE_DUE_ID_AND_DATE'),
        ledger_rules=dict(session='ONE_CANONICAL_ROW_PER_PARTITION_MARKET_SESSION; RETAIN_ALL_NATIVE_APPEND_REVISIONS_AND_COMPLETE_CALENDAR_DENOMINATOR; SAME_REVISION_CONFLICT_BLOCKED',session_order='EXACT_ACCEPTED_CALENDAR_ORDER_NOT_FILE_ORDER; MISSED_OR_NON_EVALUABLE_BREAKS_STREAK_WITH_EXPLICIT_REASON',eligible_population='ALL_ACCEPTED_ELIGIBLE_LOGICAL_EVENTS_NOT_UI_SELECTION; HIDDEN_OR_EXITED_CONTINUE_FOLLOWUP',duplicate='IDENTICAL_NATIVE_ID_CONTENT_IDEMPOTENT; SAME_ID_DIFFERENT_CONTENT_OR_SECOND_ORIGINAL_BLOCKED',control_benchmark='FROZEN_T0_IDENTITIES_NO_REDRAW_NO_FUTURE_REFILL',metrics='MFE_MAE_MDD_ONLY_READ_ACCEPTED_V4_15_METRIC_REFS_WITH_QUALITY_AND_UNITS; NO_R30_CALCULATIONS'),
        right_censor=dict(states=list(STATES),native_statuses=json.loads((ROOT/'config/v4_15_outcome_status_contract_v1.json').read_text(encoding='utf8'))['states'],mapping={'PENDING_NOT_DUE':'NATIVE_PENDING_AND_OWNER_DUE_STATE_NOT_YET_DUE','PENDING_SOURCE_UNAVAILABLE':'DUE_BUT_REQUIRED_ACCEPTED_SOURCE_UNAVAILABLE_KEEP_NATIVE_REASON_STATUS','RIGHT_CENSORED':'NATIVE_RIGHT_CENSORED_REPORT_CUTOFF_UNFINISHED_TIME_TO_EVENT_ONLY','OBSERVED':'NATIVE_OBSERVED_WITH_ACCEPTED_VERIFIED_ENDPOINT_COMMON_BASIS','INVALIDATED_BY_CONTRACT':'ONLY_EXPLICIT_ACCEPTED_OWNER_RETRACTION_OR_CONTRACT_INVALIDATION_RECEIPT; NEVER_EVENT_FAILURE'},preserve_native=['SUSPENDED_AT_HORIZON','MATURED_DATA_MISSING','DELISTED_BEFORE_HORIZON','IDENTITY_UNKNOWN','ADJUSTMENT_UNKNOWN'],denominator='KEEP_PENDING_CENSORED_INVALIDATED_AND_ALL_SOURCE_UNAVAILABLE_ROWS_WITH_REASON; ANY_EXCLUSION_REQUIRES_EXPLICIT_VERSIONED_OWNER_RULE_AND_FULL_DENOMINATOR_RECONCILIATION',prohibited=['pending converted to success/failure','censor treated as competing event','matured missing treated as censor','delisting terminal return imputed zero or minus100','missing metric filled zero']),
        stratification=dict(keys=['capability','execution_lane','model_contract_id','parameter_digest','state_lineage_id','market_regime','sector_context_where_valid','event_type','signal_date','horizon','quality_stratum'],asof='ACCEPTED_T0_CONTEXT_AND_VERSIONED_QUALITY_REF; UNKNOWN_STRATA_EXPLICIT_NEVER_DROPPED',purpose='READ_ONLY_ANALYSIS_NEVER_CHANGE_ELIGIBILITY',windows=['exact accepted session/date range','explicit report_cutoff and available_at','cumulative exact partition'],first_vs_corrected='SEPARATE_FIRST_OBSERVED_AND_LATEST_CORRECTED_VIEWS; REVISION_NOT_NEW_MATURED_EVENT',thresholds='NO_POST_OUTCOME_THRESHOLD_RETUNING_OR_WINNER_REGIME_SELECTION'),
        continuity=dict(lanes_remain_distinct=True,compatible_keys=['capability','model_contract_id','parameter_digest','state_lineage_id'],migration='EXACT_ACCEPTED_V4_18_LINEAGE_MAPPING_AND_V4_19_PRODUCTION_ROUTE_REQUIRED; NO_SHADOW_RELABEL',original_enrollment='KEEP_ORIGINAL_EVENT_AND_ENROLLMENT_LANE_IMMUTABLE; FOLLOWUP_EVALUATION_EXECUTION_LANE_RECORDED_SEPARATELY',combined='ONLY_EXPLICIT_COMPATIBLE_REPORT_WITH_PER_LANE_DENOMINATORS_AND_GLOBAL_LOGICAL_EVENT_DUE_DEDUP; NEVER_COMBINE_LANES_TO_SATISFY_CAPABILITY_GATES',model_parameter_change='NEW_PARTITION_COHORT_BOUNDARY; RESET_AFFECTED_CONSECUTIVE_WINDOW_ONLY; PRESERVE_PRIOR_PARTITIONS'),
        gate_readback=dict(fields=['SHADOW_STABLE_PASS[capability]','FORWARD_GATE[capability]','MIGRATION_REPLAY_PASS[capability]','production_permission[capability]'],owners={'SHADOW_STABLE_PASS':'V4_17G','FORWARD_GATE':'V4_17G','MIGRATION_REPLAY_PASS':'V4_18_RUNTIME','production_permission':'V4_19'},binding='EXACT_ACCEPTED_AUTHORITY_RECEIPT_DIGEST_CAPABILITY_MODEL_PARAMETER_LINEAGE_AND_ASOF_HEAD; MISSING_UNKNOWN_NOT_GRANTED',read_only=True,auto_grant=False),
        daily_operation=['accepted exact target-session publication','append canonical accepted-session projection including misses','append eligible event/cohort references under existing owner','process already-due obligations through existing settlement owner','append accepted outcome revision references','refresh read-only exact-partition aggregates','emit future observation receipt'],
        recovery=dict(identities=['session_receipt_id','event_ledger_id','due_id','outcome_id','aggregate_snapshot_id','expected_prior_observation_head'],encoding='SHA256_UTF8_SORTED_COMPACT_TYPED_JSON_NO_NAN_OF_CONTRACT_PARTITION_EXACT_INPUT_IDS_AND_DIGESTS',identical='SAME_RECEIPT_NO_DUPLICATE_SESSION_EVENT_DUE_OR_DOUBLE_COUNT',changed_source='APPEND_SUPERSEDING_RECEIPT_AND_SOURCE_REVISION; NEVER_OVERWRITE_OLD_EVIDENCE',cas='EXPECTED_PRIOR_OBSERVATION_HEAD_MISMATCH_BLOCKS_AFFECTED_SCOPE_WITH_NO_PARTIAL_ACCEPTANCE',recovery='RESUME_FROM_EXACT_ACCEPTED_RECEIPT_AND_OUTBOX_CHECKPOINT; DO_NOT_RERUN_T0_SELECTION_OR_RECOMPUTE_SETTLEMENT',implemented=False),
        receipt_schema=dict(required=['receipt_id','trade_date','capability','evidence_lane','model_contract_id','parameter_digest','state_lineage_id','publication_id','publication_revision','accepted_session_status','new_events','eligible_population_count','due_count','observed_outcomes','pending_outcomes','right_censored_outcomes','quality_summary','prior_observation_head','receipt_digest','accepted_at'],additional=['contract_digest','exact_source_manifest_digest','ledger_revision_refs','outcome_view','invalidated_outcomes','native_status_breakdown','report_cutoff','supersedes','gate_readback_receipt_refs'],counts='NONNEGATIVE_INTEGERS_WITH_EXACT_DENOMINATOR_RECONCILIATION; NO_REAL_COUNTS_FROM_DIAGNOSTIC_LANES',digest='SHA256_CANONICAL_TYPED_JSON_EXCLUDING_receipt_digest',current_real_receipt=None),
        prohibited=['new settlement engine','real observation writer in R30','same-day outcome feedback to T0 eligibility','lower thresholds for small sample','change event definitions after outcomes','drop failed events from denominator','change model boundary to preserve streak','winning regimes only','cross-capability sample borrowing'],
        current_state=dict(R25='WAIT_ACCEPTED_DAILY_INPUT',REAL_SHADOW_OBSERVATIONS=0,PIT_OBSERVED_REAL_SAMPLES=0,V4_17G='NOT_GRANTED',MIGRATION_REPLAY_PASS='NOT_GRANTED',production_permission={cap:False for cap in CAPS},DEFAULT_UI_CUTOVER=False,Focus_source_cutover=False,REAL_CONTINUED_FORWARD_OBSERVATION='NOT_STARTED',V4_21_ACCEPTED_HEAD='NOT_CREATED',R28_P2_TRANSITIVE_ROLLBACK_VECTOR_COVERAGE='CLOSED_EXTERNAL_R29'),
        implementation_entry=dict(status='BLOCKED_WAIT_REAL_OBSERVATION',required_all=['accepted real V4_16 Shadow publication','accepted V4_15 settlement owner/runtime binding','accepted observation storage contract','accepted capability/model/lineage binding'],receipts=[None]*4),next_stage='STOP_WAIT_R30_INDEPENDENT_EXTERNAL_AUDIT')
    descriptions=['accepted real Shadow session counts','simulation does not count','historical replay does not count','reconstructed asof does not count','missed session denominator/streak break','non-evaluable session retained','hidden eligible event retained','duplicate original rejected','T5 pending not observed','right censor not failure','correction supersedes without double count','model change new partition','parameter change affected partition only','Stock counts cannot satisfy Sector','Shadow rows not relabeled Production','Production same lineage separate lane','identical source rerun idempotent','stale prior-head CAS conflict','same-day outcome feedback rejected','aggregate lane/model/capability breakdown']
    c['vectors']=[dict(id=f'F21-{i:02}',description=d,kind='CONTRACT_DESIGN_SIMULATION_NOT_REAL_FORWARD_EVIDENCE',fixture='reports/r30/design_ledger.py::scenario',independent_assertions='tests/test_v4_21_forward_observation_contract.py',expected_status='BLOCKED_AFFECTED_SCOPE' if i in (8,18,19) else 'PASS_DESIGN_ONLY',expected_real_rows_written=0,expected_production_grant=False) for i,d in enumerate(descriptions,1)]
    write('config/v4_21_continued_forward_observation_contract_v1.json',c)
    mapping={'EVIDENCE_LANE_REGISTRY':'evidence_lanes','ACCEPTED_SESSION_LEDGER_SCHEMA':'session_ledger','EVENT_COHORT_LEDGER_SCHEMA':'event_cohort_ledger','DUE_OUTCOME_LEDGER_SCHEMA':'due_outcome_ledger','RIGHT_CENSOR_POLICY':'right_censor','STRATIFICATION_POLICY':'stratification','SHADOW_PRODUCTION_CONTINUITY':'continuity','GATE_READBACK_POLICY':'gate_readback','OBSERVATION_RECEIPT_SCHEMA':'receipt_schema','FORWARD_VECTOR_REGISTRY':'vectors','CURRENT_OBSERVATION_GATE':'current_state'}
    for name,section in mapping.items(): write('reports/r30/'+name+'.json',dict(contract='config/v4_21_continued_forward_observation_contract_v1.json',contract_sha256=sha(ROOT/'config/v4_21_continued_forward_observation_contract_v1.json'),section=section,definition=c[section],scope='CONTRACT_DESIGN_ONLY'))


if __name__=='__main__':
    import sys
    sys.path.insert(0,str(ROOT)); build()
