"""Atomic R28 design/evidence authoring; no live source or routing operations."""
import hashlib
import json
import os
from pathlib import Path
import subprocess

ROOT=Path(__file__).resolve().parents[2]
BASE='94635fa369c60b3f8182cb4d813751a453682d88'


def sha(path):
    with path.open('rb') as stream: return hashlib.file_digest(stream,'sha256').hexdigest()


def write(path,value):
    assert path.startswith(('reports/r28/','docs/evidence/r28/','config/v4_19_'))
    target=ROOT/path; target.parent.mkdir(parents=True,exist_ok=True)
    data=value if isinstance(value,str) else json.dumps(value,indent=2,ensure_ascii=False,sort_keys=True)+'\n'
    staging=target.with_name(target.name+'.r28-staging')
    with staging.open('wb') as stream:
        stream.write(data.replace('\r\n','\n').encode('utf8')); stream.flush(); os.fsync(stream.fileno())
    os.replace(staging,target)


def build():
    from reports.r28.design_oracle import CAPS,DEPS,FIELDS
    upgrade='docs/evidence/A_SHARE_RESEARCH_SYSTEM_V4_2_2_FINAL_EXECUTABLE_CONTRACT_REV4_FEP_R2_20260930.md'
    documents=[]
    for name in ('V4_NEXT_ROUND_EXECUTION_MASTER_R28_20261004.md','V4_19_R28_FOCUS_SOURCE_CUTOVER_CONTRACT_DESIGN_TASK_20261004.md','V4_R27_V4_18_MIGRATION_REPLAY_CONTRACT_DESIGN_FINAL_INDEPENDENT_EXTERNAL_AUDIT_R1_20261004.md'):
        source=Path('D:/Users/lps/Desktop/阶段任务')/name
        documents.append(dict(source=str(source),original_sha256=sha(source),copy='docs/evidence/r28/'+name))
        write(documents[-1]['copy'],source.read_text(encoding='utf8'))
    write('reports/r28/STAGE_CONTRACT.json',dict(stage='V4-19',mode='CONTRACT_DESIGN_ONLY',baseline=BASE,upgrade=dict(path=upgrade,sha256=sha(ROOT/upgrade),sections=['51A','52A','72','78','81.4','83']),documents=documents,allowed=['config/v4_19_*','reports/r28/*','docs/evidence/r28/*','tests/test_v4_19_focus_cutover_contract.py'],forbidden=['production writer','routing mutation','permission grant','accepted heads','TDX writes'],acceptance='PENDING_LOCAL_CONTRACT_VALIDATION',next='STOP_WAIT_R28_INDEPENDENT_EXTERNAL_AUDIT'))
    names=subprocess.check_output(['git','ls-tree','-r','--name-only',BASE],cwd=ROOT,text=True,encoding='utf8').splitlines()
    unrelated=subprocess.check_output(['git','ls-files','--others','--exclude-standard','-z'],cwd=ROOT).decode('utf8').split('\0')
    write('reports/r28/PROTECTED_BASELINE.json',dict(baseline=BASE,tracked={n:sha(ROOT/n) for n in names if (ROOT/n).is_file()},unrelated={n:sha(ROOT/n) for n in unrelated if n and not n.startswith(('reports/r28/','docs/evidence/r28/','config/v4_19_','tests/test_v4_19_'))}))
    registry={}
    for cap in CAPS:
        registry[cap]=dict(required_dependencies=DEPS[cap],shadow_gate='SHADOW_STABLE_PASS_EXACT_CAPABILITY_MODEL_PARAMETER_LINEAGE',forward_gate='STOCK_PROVISIONAL_FORWARD_GATE' if cap.startswith('STOCK') else cap+'_SEPARATELY_FROZEN_FORWARD_GATE',migration_gate='EXTERNALLY_ACCEPTED_V4_18_RUNTIME_REPLAY_EXACT_CAPABILITY',production_permission=False,accepted_receipts=dict(shadow=None,forward=None,migration=None,dependencies=None),fallback_mode='LEGACY_PRODUCTION_FOR_EXISTING_FOCUS; SHADOW_V4_READ_ONLY_DIAGNOSTICS',ui_label='SHADOW / NOT_GRANTED',focus_eligibility='V4_ACCEPTED_PUBLICATION_ONLY_AFTER_ALL_CAPABILITY_GATES_AND_ATOMIC_ROUTE_CAS',rollback_scope=dict(primary=cap,affected_consumers='TRANSITIVE_DEPENDENTS_FAIL_CLOSED; INDEPENDENT_CAPABILITIES_REMAIN_VALID'))
    c=dict(contract_id='V4_19_FOCUS_SOURCE_CUTOVER_CONTRACT_V1',version='1.0.0',policy_id='CUTOVER_V2',stage='V4-19',mode='CONTRACT_DESIGN_ONLY',baseline=BASE,status='LOCAL_DESIGN_PENDING_EXTERNAL_AUDIT',capability_registry=registry,
        permission_formula=dict(operator='AND',terms=['SHADOW_STABLE_PASS[capability]','FORWARD_GATE[capability]','MIGRATION_REPLAY_PASS[capability]','ALL(required_dependency_permissions)'],missing_unknown_stale_or_conflicting='FALSE_NO_CUTOVER',shared_raw_source='READ_CAPABILITY_ONLY_NEVER_PERMISSION_INHERITANCE',global_permission='FORBIDDEN',dependency_graph=DEPS,topological_order=['STOCK_CORE','SECTOR_STAGE','STOCK_SECTOR_DEPENDENT','ROTATION','SECTOR_RISK_CHANGE']),
        shadow_gate=dict(receipt_fields=['capability','model_contract_id','parameter_digest','state_lineage_id','accepted_session_ids','calendar_digest','slot_receipt_digests','leakage_count','duplicate_episode_corruption_count','core_identity_violation_count','p0_count','rollback_drill_receipt','available_at','external_acceptance_receipt'],same_model=True,minimum_consecutive_accepted_market_sessions=20,required_zero=['temporal_leakage','duplicate_episode_corruption','core_identity_violation','P0_state_violation'],rollback_drill='PASS_REQUIRED',missed_non_evaluable='DO_NOT_COUNT_AND_BREAK_CONSECUTIVE_ACCEPTED_MARKET_SESSION_WINDOW; KEEP_COMPLETE_SLOT_DENOMINATOR',reset=['P0','affected capability model change','affected capability parameter change','shared dependency change resets all affected consumers'],origin='PIT_OBSERVED',execution_mode='SHADOW',current_status='NOT_GRANTED'),
        forward_gates=dict(stock=dict(min_distinct_signal_dates=5,min_distinct_stocks=30,positive_event_types=['FIRST_PREWATCH','REENTRY_PREWATCH','NEW_CONFIRMED'],horizon=5,status='OBSERVED',same_model=True,settlement_p0=0,dedup_key='logical_event_id; revisions never add logical events or distinct stocks',excluded=['INVALIDATION','ESTIMATED','RECONSTRUCTED_ASOF','REPLAY'],quality_receipts=['controls coverage and quality strata','benchmark coverage and quality strata'],counts='DISTINCT_ACCEPTED_LOGICAL_EVENTS_AT_T5; DISTINCT_STOCK_IDS; DISTINCT_SIGNAL_DATES'),sector_stage=dict(event_types=['SECTOR_FIRST_PREWATCH','SECTOR_NEW_WARM','SECTOR_NEW_CONFIRMED'],policy='EXACT_ACCEPTED_V4_00H_SEPARATELY_FROZEN_THRESHOLDS_REQUIRED; NO_STOCK_COUNTS',required_parameters=['sector_min_unique_signal_dates','sector_min_unique_episodes','sector_min_matured_events_by_type','required_forward_quality'],threshold_receipt=None),rotation=dict(event_types=['ROTATION_PULSE','ROTATION_ACCEPTED','ROTATION_FAILED'],policy='FAILED_INCLUDED_AS_FAILURE_OBSERVATION_NOT_POSITIVE_ACCEPTED; PULSE_CANNOT_SUBSTITUTE_ACCEPTED',required_parameters=['rotation_min_accepted_episodes','sector_min_unique_signal_dates','sector_min_unique_episodes','sector_min_matured_events_by_type','required_forward_quality'],threshold_receipt=None),sector_risk_change=dict(policy='SEPARATE_ACCEPTED_EVENT_COMPLETENESS_RISK_CORRECTNESS_AND_SECTOR_PATH_POLICY; NO_STOCK_COUNT_BORROWING',threshold_receipt=None),sector_common='PER_TYPE_UNIQUE_EPISODES_SIGNAL_DATES_MATURED_EVENTS_T5_PRICE_PATH_QUALITY_STATE_RESULTS; SAME_EPISODE_MULTIPLE_TYPES_NOT_DISTINCT_EPISODES; UNFROZEN_POLICY_OR_MISSING_SAMPLE_IS_SHADOW_ONLY'),
        migration_gate=dict(required='MIGRATION_REPLAY_PASS[capability]',authority='EXTERNALLY_ACCEPTED_V4_18_RUNTIME_REPLAY',design_pass_satisfies=False,r27_contract_sha256=sha(ROOT/'config/v4_18_migration_replay_contract_v1.json'),current='NOT_GRANTED'),
        receipt_schema=dict(required=list(FIELDS),types={k:('boolean' if k=='production_permission' else 'integer' if k in ('shadow_sessions','unique_signal_dates') else 'object_per_event_type' if k=='matured_events' else 'exact_capability_dependency_receipt_map' if k=='dependency_scope' else 'exact_bound_accepted_reference' if k in ('source_publication','forward_quality','migration_gate','expected_route_head') else 'string') for k in FIELDS},additional_required=['receipt_id','request_id','contract_digest','gate_receipt_digests','dependency_receipt_digests','previous_receipt_digest','accepted_at','external_authority_receipt','evidence_class'],digest='SHA256_UTF8_SORTED_COMPACT_JSON_ALL_FIELDS_EXCEPT_receipt_digest; NO_NAN; TYPES_AND_NULL_EXPLICIT',identity_binding=['capability','model_contract_id','parameter_digest','state_lineage_id','source_publication','contract_digest'],freshness='VERIFY_NOT_SUPERSEDED_NOT_REVOKED_AND_EXACT_ACTIVE_RECEIPT_HEAD_AT_CAS; NO_ARBITRARY_AGE_THRESHOLD',evidence_class='PROVISIONAL_AFTER_VALID_FUTURE_CUTOVER; NOT_LONG_TERM_ADVANTAGE_PROOF',r28_receipt='NO_REAL_CUTOVER_RECEIPT_CREATED'),
        focus_routing=dict(states=['LEGACY_PRODUCTION','V4_PRODUCTION[capability]','SHADOW_V4'],current='LEGACY_PRODUCTION_UNCHANGED',eligible_publication='EXACT_ACCEPTED_V4_PUBLICATION_CAPABILITY_MODEL_PARAMETER_LINEAGE_AND_DIGEST_MATCH_ACTIVE_PERMISSION_RECEIPTS',shadow='READ_ONLY; NEVER_PRODUCTION_FOCUS_SOURCE',authority='EXPLICIT_EXTERNALLY_ACCEPTED_CUTOVER_AUTHORITY_AND_ATOMIC_CAS; NO_UI_OR_PAGE_AUTHORITY',user_pin='PRODUCT_STATE_ONLY; NEVER_ALGORITHM_EVIDENCE_OR_PERMISSION'),
        mixed_ui=dict(module_mode_labels=['PRODUCTION','SHADOW','LEGACY'],global_v4_production_label=False,context='ONE_EXACT_IMMUTABLE_CONTEXT_MANIFEST_PINNING_EACH_MODULE_NATIVE_PUBLICATION_ID_REVISION_NAMESPACE_MODEL_PARAMETER_LINEAGE_DIGEST_AND_MODE; HASHED_MANIFEST_TOKEN; NO_LATEST_FALLBACK',shadow_native_identity_fields=json.loads((ROOT/'config/v4_17_shadow_ui_contract_v1.json').read_text(encoding='utf8'))['identity_fields'],cross_module='SHARED_CONTEXT_MANIFEST_DOES_NOT_RELABEL_SHADOW_NATIVE_NAMESPACE_OR_GRANT_DEPENDENCY_PERMISSION',context_mismatch='FAIL_CLOSED_AFFECTED_MODULE; NEVER_SILENTLY_MIX_PUBLICATION_REVISIONS'),
        cutover_cas=dict(inputs=['expected_route_head','new_route','accepted_permission_receipts','cutover_authority'],additional_checks=['all receipt identities and active digests','source publication capability identity','transitive dependency permission heads','exact previous accepted route','cutover gap and pending settlement ownership manifest'],atomicity='APPEND_CUTOVER_RECEIPT_AND_CHANGE_EXACT_CAPABILITY_ROUTE_HEAD_IN_ONE_FUTURE_TRANSACTION; VERIFY_ALL_READ_HEADS_AT_CAS',mismatch=['NO_CUTOVER','NO_PARTIAL_ROUTE_CHANGE'],idempotency='SAME_REQUEST_ID_SAME_CANONICAL_PAYLOAD_RETURNS_SAME_RECEIPT; CHANGED_PAYLOAD_IDEMPOTENCY_CONFLICT',implemented=False),
        rollback=dict(scope='AFFECTED_CAPABILITY_AND_TRANSITIVE_DEPENDENT_CONSUMERS_ONLY; INDEPENDENT_VALID_CAPABILITIES_UNCHANGED',order=['fence new V4 Focus writes for affected capability','capture final cutover gap watermarks and ownership','restore exact previous accepted route with CAS','append rollback receipt and gap reconciliation manifest'],preserve=['accepted V4 facts','historical Shadow context','user pins/manual work','pending settlement ownership and frozen identities','outbox and receipts'],migration_binding='R27_EXACTLY_ONE_AUTHORIZED_WORKER_PER_EXISTING_DUE_ID; RETAIN_GAP_ACTIVITY; NO_BACKUP_ONLY_RESTORE',authority='EXACT_ACCEPTED_CAPABILITY_ROLLBACK_AUTHORITY; ALL_DEPENDENT_ROUTE_HEADS_CAS_ATOMIC_OR_NO_PARTIAL_CHANGE',implemented=False),
        prohibited=['GLOBAL_V4_PASS','GLOBAL_FOCUS_CUTOVER','cross-capability sample borrowing','historical replay counted as SHADOW_STABLE','RECONSTRUCTED_ASOF counted as PIT_OBSERVED','user pin counted as algorithm evidence','UI display counted as production permission'],
        current_state=dict(R25='WAIT_ACCEPTED_DAILY_INPUT',REAL_SHADOW_OBSERVATIONS=0,V4_17_FINAL_ACCEPTANCE='NOT_GRANTED',V4_17G='NOT_GRANTED',V4_18_CONTRACT_DESIGN='EXTERNALLY_ACCEPTED',V4_18_IMPLEMENTATION_ENTRY='BLOCKED_WAIT_REAL_SHADOW_GATE',MIGRATION_REPLAY_PASS='NOT_GRANTED',production_permission={cap:False for cap in CAPS},focus_source_cutover=False,V4_19_ACCEPTED_HEAD='NOT_CREATED'),
        implementation_entry=dict(status='BLOCKED_WAIT_REAL_GATES',required_all=['externally accepted V4_17 real readback and V4_17G capability stability/forward receipts','externally accepted V4_18 runtime replay capability receipts','accepted exact source publication and target routing storage contract','accepted capability cutover/rollback authority'],receipts=[None]*4),next_stage='STOP_WAIT_R28_INDEPENDENT_EXTERNAL_AUDIT')
    descriptions=['STOCK_CORE all gates pass -> hypothetical true','stock gate pass, sector insufficient -> sector false','sector pass, stock insufficient -> sector scope true if dependencies permit','STOCK_SECTOR_DEPENDENT blocked by Sector dependency','migration missing -> false','shadow stable missing -> false','forward missing -> false','model/parameter digest mismatch','source publication capability mismatch','route-head CAS conflict','mixed UI labels production/shadow correctly','user pin creates no permission','historical replay cannot satisfy Shadow sessions','RECONSTRUCTED_ASOF cannot satisfy real gate','rollback one capability only','global-pass attempt rejected','receipt missing dependency scope','stale permission receipt','corrected outcome does not double-count event','shared source implies no permission inheritance']
    blocked={'C03','C05','C06','C07','C08','C09','C10','C12','C13','C14','C16','C17','C18','C19'}
    core_false={'C03','C05','C06','C07','C08','C12','C13','C14','C16','C18','C19'}
    reasons={'C09':'SOURCE_PUBLICATION_IDENTITY_MISMATCH','C10':'ROUTE_CAS_CONFLICT','C16':'GLOBAL_PROMOTION_FORBIDDEN','C17':'RECEIPT_SCHEMA_INCOMPLETE'}
    c['vectors']=[dict(id=f'C{i:02}',description=d,kind='CONTRACT_DESIGN_SIMULATION_NOT_REAL_GATE',fixture_source='reports/r28/design_oracle.py::scenario',independent_expected_source='tests/test_v4_19_focus_cutover_contract.py',expected=dict(design_action='NO_CUTOVER' if f'C{i:02}' in blocked else 'ELIGIBLE_DESIGN_PROPOSAL',stock_core_permission=f'C{i:02}' not in core_false,reason=reasons.get(f'C{i:02}', 'CAPABILITY_PERMISSION_FALSE' if f'C{i:02}' in blocked else None),actual_production_grant=False,actual_route_changes=[]),future_evidence=['accepted gate and dependency receipts','exact source publication and route-head snapshot','independent identity/count/route reconciliation']) for i,d in enumerate(descriptions,1)]
    write('config/v4_19_focus_source_cutover_contract_v1.json',c)
    sections={'CAPABILITY_REGISTRY':'capability_registry','PERMISSION_FORMULA_GATE':'permission_formula','FOCUS_ROUTING_GATE':'focus_routing','MIXED_MODE_UI_POLICY':'mixed_ui','CUTOVER_RECEIPT_SCHEMA':'receipt_schema','ROLLBACK_POLICY':'rollback','CUTOVER_VECTOR_REGISTRY':'vectors','CURRENT_PERMISSION_GATE':'current_state'}
    for name,section in sections.items(): write('reports/r28/'+name+'.json',dict(contract='config/v4_19_focus_source_cutover_contract_v1.json',contract_sha256=sha(ROOT/'config/v4_19_focus_source_cutover_contract_v1.json'),section=section,definition=c[section],scope='CONTRACT_DESIGN_ONLY'))


if __name__=='__main__':
    import sys
    sys.path.insert(0,str(ROOT)); build()
